// ----------------------------------------------------
// Copyright (c) 2018-2025 Madrigal Ltd.
// This file is part of the Basis SDK, and is subject to the
// terms and conditions of the Basis SDK License Agreement.
// https://www.madrigalgames.com
// ----------------------------------------------------

// This file was generated by Sir Bindalot, the binding generator. Ne pas toucher!

const basis = @import("basis");
const merlin = @import("../merlin.zig");

// class MerlinManager

pub var _MerlinManager_loadEffect: merlin.bindings.generated_types.basis_zig_MerlinManager_loadEffect_cb = undefined;

// ===============================

// class EffectDescription

pub var _EffectDescription_createInstance: merlin.bindings.generated_types.basis_zig_EffectDescription_createInstance_cb = undefined;
pub var _EffectDescription_getParameterIndex: merlin.bindings.generated_types.basis_zig_EffectDescription_getParameterIndex_cb = undefined;

// ===============================

// class EffectInstance

pub var _EffectInstance_release: merlin.bindings.generated_types.basis_zig_EffectInstance_release_cb = undefined;
pub var _EffectInstance_releaseWhenFinished: merlin.bindings.generated_types.basis_zig_EffectInstance_releaseWhenFinished_cb = undefined;
pub var _EffectInstance_setTransform: merlin.bindings.generated_types.basis_zig_EffectInstance_setTransform_cb = undefined;
pub var _EffectInstance_getState: merlin.bindings.generated_types.basis_zig_EffectInstance_getState_cb = undefined;
pub var _EffectInstance_start: merlin.bindings.generated_types.basis_zig_EffectInstance_start_cb = undefined;
pub var _EffectInstance_pause: merlin.bindings.generated_types.basis_zig_EffectInstance_pause_cb = undefined;
pub var _EffectInstance_stop: merlin.bindings.generated_types.basis_zig_EffectInstance_stop_cb = undefined;
pub var _EffectInstance_stopEmitting: merlin.bindings.generated_types.basis_zig_EffectInstance_stopEmitting_cb = undefined;
pub var _EffectInstance_setIntParameter: merlin.bindings.generated_types.basis_zig_EffectInstance_setIntParameter_cb = undefined;
pub var _EffectInstance_setFloatParameter: merlin.bindings.generated_types.basis_zig_EffectInstance_setFloatParameter_cb = undefined;
pub var _EffectInstance_setVectorParameter: merlin.bindings.generated_types.basis_zig_EffectInstance_setVectorParameter_cb = undefined;

// ===============================

