// ----------------------------------------------------
// Copyright (c) 2018-2025 Madrigal Ltd.
// This file is part of the Basis SDK, and is subject to the
// terms and conditions of the Basis SDK License Agreement.
// https://www.madrigalgames.com
// ----------------------------------------------------

// This file was generated by Sir Bindalot, the binding generator. Ne pas toucher!

const basis = @import("basis");
const merlin = @import("../merlin.zig");

// class MerlinManager

export fn bindMerlinManager(
	loadEffect: merlin.bindings.generated_types.basis_zig_MerlinManager_loadEffect_cb,
) void {
	merlin.bindings.generated_function_pointers._MerlinManager_loadEffect = loadEffect;
}

// ===============================

// class EffectDescription

export fn bindEffectDescription(
	createInstance: merlin.bindings.generated_types.basis_zig_EffectDescription_createInstance_cb,
	getParameterIndex: merlin.bindings.generated_types.basis_zig_EffectDescription_getParameterIndex_cb,
) void {
	merlin.bindings.generated_function_pointers._EffectDescription_createInstance = createInstance;
	merlin.bindings.generated_function_pointers._EffectDescription_getParameterIndex = getParameterIndex;
}

// ===============================

// class EffectInstance

export fn bindEffectInstance(
	release: merlin.bindings.generated_types.basis_zig_EffectInstance_release_cb,
	releaseWhenFinished: merlin.bindings.generated_types.basis_zig_EffectInstance_releaseWhenFinished_cb,
	setTransform: merlin.bindings.generated_types.basis_zig_EffectInstance_setTransform_cb,
	getState: merlin.bindings.generated_types.basis_zig_EffectInstance_getState_cb,
	start: merlin.bindings.generated_types.basis_zig_EffectInstance_start_cb,
	pause: merlin.bindings.generated_types.basis_zig_EffectInstance_pause_cb,
	stop: merlin.bindings.generated_types.basis_zig_EffectInstance_stop_cb,
	stopEmitting: merlin.bindings.generated_types.basis_zig_EffectInstance_stopEmitting_cb,
	setIntParameter: merlin.bindings.generated_types.basis_zig_EffectInstance_setIntParameter_cb,
	setFloatParameter: merlin.bindings.generated_types.basis_zig_EffectInstance_setFloatParameter_cb,
	setVectorParameter: merlin.bindings.generated_types.basis_zig_EffectInstance_setVectorParameter_cb,
) void {
	merlin.bindings.generated_function_pointers._EffectInstance_release = release;
	merlin.bindings.generated_function_pointers._EffectInstance_releaseWhenFinished = releaseWhenFinished;
	merlin.bindings.generated_function_pointers._EffectInstance_setTransform = setTransform;
	merlin.bindings.generated_function_pointers._EffectInstance_getState = getState;
	merlin.bindings.generated_function_pointers._EffectInstance_start = start;
	merlin.bindings.generated_function_pointers._EffectInstance_pause = pause;
	merlin.bindings.generated_function_pointers._EffectInstance_stop = stop;
	merlin.bindings.generated_function_pointers._EffectInstance_stopEmitting = stopEmitting;
	merlin.bindings.generated_function_pointers._EffectInstance_setIntParameter = setIntParameter;
	merlin.bindings.generated_function_pointers._EffectInstance_setFloatParameter = setFloatParameter;
	merlin.bindings.generated_function_pointers._EffectInstance_setVectorParameter = setVectorParameter;
}

// ===============================

