// ----------------------------------------------------
// Copyright (c) 2018-2025 Madrigal Ltd.
// This file is part of the Basis SDK, and is subject to the
// terms and conditions of the Basis SDK License Agreement.
// https://www.madrigalgames.com
// ----------------------------------------------------

// This file was generated by Sir Bindalot, the binding generator. Ne pas toucher!

const basis = @import("basis");
const merlin = @import("../merlin.zig");

// class MerlinManager

pub const basis_zig_MerlinManager_loadEffect_cb = *const fn ([*c]const basis.bindings.InteropString) callconv(.c) u64;

// ===============================

// class EffectDescription

pub const basis_zig_EffectDescription_createInstance_cb = *const fn (u64, [*c]const basis.bindings.InteropMat43, c_int) callconv(.c) u64;
pub const basis_zig_EffectDescription_getParameterIndex_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) u8;

// ===============================

// class EffectInstance

pub const basis_zig_EffectInstance_release_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_EffectInstance_releaseWhenFinished_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_EffectInstance_setTransform_cb = *const fn (u64, [*c]const basis.bindings.InteropMat43) callconv(.c) void;
pub const basis_zig_EffectInstance_getState_cb = *const fn (u64) callconv(.c) u32;
pub const basis_zig_EffectInstance_start_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_EffectInstance_pause_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_EffectInstance_stop_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_EffectInstance_stopEmitting_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_EffectInstance_setIntParameter_cb = *const fn (u64, u8, c_int) callconv(.c) void;
pub const basis_zig_EffectInstance_setFloatParameter_cb = *const fn (u64, u8, f32) callconv(.c) void;
pub const basis_zig_EffectInstance_setVectorParameter_cb = *const fn (u64, u8, [*c]const basis.bindings.InteropVec4) callconv(.c) void;

// ===============================

