// ----------------------------------------------------
// Copyright (c) 2018-2026 Madrigal Ltd.
// This file is part of the Basis modding SDK, and is subject to the
// terms and conditions of the Basis modding SDK License Agreement.
// https://www.madrigalgames.com
// ----------------------------------------------------

// This file was generated by Sir Bindalot, the binding generator. Ne pas toucher!

const basis = @import("../basis.zig");

// class Core

pub const basis_zig_Core_showAssertDialog_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString) callconv(.c) c_int;
pub const basis_zig_Core_heapAlloc_cb = *const fn (u64, u64) callconv(.c) [*c]u8;
pub const basis_zig_Core_heapFree_cb = *const fn ([*c]u8) callconv(.c) void;
pub const basis_zig_Core_printOnHost_cb = *const fn ([*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_Core_beginProfilingSample_cb = *const fn ([*c]const u8) callconv(.c) void;
pub const basis_zig_Core_endProfilingSample_cb = *const fn () callconv(.c) void;
pub const basis_zig_Core_getRandomSeed_cb = *const fn () callconv(.c) u64;

// ===============================

// class App

pub const basis_zig_App_createApp_cb = *const fn (basis.bindings.InteropTypedPtr, u64) callconv(.c) u64;
pub const basis_zig_App_getAppMode_cb = *const fn (u64) callconv(.c) i32;
pub const basis_zig_App_getClient_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_App_getServer_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_App_addInput_cb = *const fn (u64, u16, c_int) callconv(.c) void;
pub const basis_zig_App_getInputBufferSize_cb = *const fn (u64) callconv(.c) u32;
pub const basis_zig_App_clearInputMappings_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_App_mapInput_cb = *const fn (u64, u16, c_int, u8, f32, c_int) callconv(.c) void;
pub const basis_zig_App_mapKeyboardInput_cb = *const fn (u64, u16, c_int, u8, c_int) callconv(.c) void;
pub const basis_zig_App_mapMouseButtonInput_cb = *const fn (u64, u16, c_int, u8, c_int) callconv(.c) void;
pub const basis_zig_App_mapGamepadButtonInput_cb = *const fn (u64, u16, c_int, u8, c_int) callconv(.c) void;
pub const basis_zig_App_registerMessage_cb = *const fn (u64, i32, i32) callconv(.c) void;
pub const basis_zig_App_getClientGameFlowStateMachine_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_App_getServerGameFlowStateMachine_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_App_createAndLoadSPGame_cb = *const fn (u64, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, u32, [*c]const u64, u32, c_int, basis.bindings.FP_void_IntPtr64_i32, u64) callconv(.c) void;
pub const basis_zig_App_createSPGame_cb = *const fn (u64, [*c]const basis.bindings.InteropString, c_int, basis.bindings.FP_void_IntPtr64_i32, u64) callconv(.c) void;
pub const basis_zig_App_loadSPGame_cb = *const fn (u64, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, u32, [*c]const u64, u32) callconv(.c) void;
pub const basis_zig_App_leaveGame_cb = *const fn (u64, c_int, basis.bindings.FP_void_IntPtr64_i32, u64) callconv(.c) void;
pub const basis_zig_App_isLocalServerRunning_cb = *const fn () callconv(.c) c_int;
pub const basis_zig_App_isServerThreadRunning_cb = *const fn () callconv(.c) c_int;
pub const basis_zig_App_hasCommandLineParameter_cb = *const fn ([*c]const basis.bindings.InteropString) callconv(.c) c_int;
pub const basis_zig_App_getCommandLineParameter_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_App_getConfigOptions_cb = *const fn () callconv(.c) u64;

// ===============================

// class ModController

pub const basis_zig_ModController_createModController_cb = *const fn (basis.bindings.InteropTypedPtr, u64) callconv(.c) u64;
pub const basis_zig_ModController_getAppMode_cb = *const fn (u64) callconv(.c) i32;
pub const basis_zig_ModController_getClient_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_ModController_getServer_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_ModController_registerMessage_cb = *const fn (u64, i32, i32) callconv(.c) void;

// ===============================

// class Client

pub const basis_zig_Client_getHostID_cb = *const fn (u64) callconv(.c) i32;
pub const basis_zig_Client_getRenderer_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_Client_getGameSession_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_Client_getGameState_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_Client_getPhysicsEnginePtr_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_Client_getPrimaryPhysicsScene_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_Client_getInterpolationFactor_cb = *const fn (u64) callconv(.c) f64;
pub const basis_zig_Client_createMessageNode_cb = *const fn (basis.bindings.InteropTypedPtr, u64, [*c]const basis.bindings.InteropString, u64) callconv(.c) u64;
pub const basis_zig_Client_addRPCListener_cb = *const fn (u64, u64, u64) callconv(.c) u64;
pub const basis_zig_Client_removeRPCListener_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_Client_sendNetworkMessageToHostID_cb = *const fn (u64, [*c]const u8, u32, c_int, c_int) callconv(.c) void;
pub const basis_zig_Client_sendNetworkMessageToPeer_cb = *const fn (u64, [*c]const u8, u32, c_int, u64) callconv(.c) void;
pub const basis_zig_Client_isConnected_cb = *const fn (u64) callconv(.c) c_int;

// ===============================

// class Server

pub const basis_zig_Server_getGameSession_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_Server_getGameState_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_Server_getPhysicsEnginePtr_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_Server_getPrimaryPhysicsScene_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_Server_createMessageNode_cb = *const fn (basis.bindings.InteropTypedPtr, u64, [*c]const basis.bindings.InteropString, u64) callconv(.c) u64;
pub const basis_zig_Server_addRPCListener_cb = *const fn (u64, u64, u64) callconv(.c) u64;
pub const basis_zig_Server_removeRPCListener_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_Server_sendNetworkMessageToHostID_cb = *const fn (u64, [*c]const u8, u32, c_int, c_int) callconv(.c) void;
pub const basis_zig_Server_sendNetworkMessageToPeer_cb = *const fn (u64, [*c]const u8, u32, c_int, u64) callconv(.c) void;
pub const basis_zig_Server_endGameSession_cb = *const fn (u64) callconv(.c) void;

// ===============================

// class CommandPrompt

pub const basis_zig_CommandPrompt_parseCommand_cb = *const fn ([*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_CommandPrompt_registerIntValue_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, basis.bindings.FP_void_i32, basis.bindings.FP_i32, c_int, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_CommandPrompt_registerFloatValue_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, basis.bindings.FP_void_f32, basis.bindings.FP_f32, c_int, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_CommandPrompt_registerBoolValue_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, basis.bindings.FP_void_bool, basis.bindings.FP_bool, c_int, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_CommandPrompt_registerFunction_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, basis.bindings.FP_void, [*c]i32, u32, c_int, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_CommandPrompt_unregister_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_CommandPrompt_outputLine_cb = *const fn ([*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_CommandPrompt_outputErrorLine_cb = *const fn ([*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_CommandPrompt_getIntParameter_cb = *const fn () callconv(.c) i32;
pub const basis_zig_CommandPrompt_getFloatParameter_cb = *const fn () callconv(.c) f32;
pub const basis_zig_CommandPrompt_getBoolParameter_cb = *const fn () callconv(.c) c_int;
pub const basis_zig_CommandPrompt_getStringParameter_cb = *const fn ([*c]basis.bindings.InteropString) callconv(.c) void;

// ===============================

// class ConfigOptions

pub const basis_zig_ConfigOptions_addString_cb = *const fn (u64, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_ConfigOptions_addFloat_cb = *const fn (u64, [*c]const basis.bindings.InteropString, f32) callconv(.c) void;
pub const basis_zig_ConfigOptions_addInteger_cb = *const fn (u64, [*c]const basis.bindings.InteropString, c_int) callconv(.c) void;
pub const basis_zig_ConfigOptions_addBool_cb = *const fn (u64, [*c]const basis.bindings.InteropString, c_int) callconv(.c) void;
pub const basis_zig_ConfigOptions_getString_cb = *const fn (u64, [*c]const basis.bindings.InteropString, [*c]basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_ConfigOptions_getFloat_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) f32;
pub const basis_zig_ConfigOptions_getInteger_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) c_int;
pub const basis_zig_ConfigOptions_getBool_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) c_int;
pub const basis_zig_ConfigOptions_setString_cb = *const fn (u64, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_ConfigOptions_setFloat_cb = *const fn (u64, [*c]const basis.bindings.InteropString, f32) callconv(.c) void;
pub const basis_zig_ConfigOptions_setInteger_cb = *const fn (u64, [*c]const basis.bindings.InteropString, c_int) callconv(.c) void;
pub const basis_zig_ConfigOptions_setBool_cb = *const fn (u64, [*c]const basis.bindings.InteropString, c_int) callconv(.c) void;
pub const basis_zig_ConfigOptions_hasString_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) c_int;
pub const basis_zig_ConfigOptions_hasFloat_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) c_int;
pub const basis_zig_ConfigOptions_hasInteger_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) c_int;
pub const basis_zig_ConfigOptions_hasBool_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) c_int;
pub const basis_zig_ConfigOptions_save_cb = *const fn (u64) callconv(.c) void;

// ===============================

// class PlayerController

pub const basis_zig_PlayerController_getClient_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) u64;
pub const basis_zig_PlayerController_getServer_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) u64;
pub const basis_zig_PlayerController_getInputRange_cb = *const fn (basis.bindings.InteropTypedPtr, u16) callconv(.c) f32;
pub const basis_zig_PlayerController_getInputState_cb = *const fn (basis.bindings.InteropTypedPtr, u16) callconv(.c) c_int;
pub const basis_zig_PlayerController_getInputAction_cb = *const fn (basis.bindings.InteropTypedPtr, u16) callconv(.c) c_int;
pub const basis_zig_PlayerController_subscribeToMessageCategory_cb = *const fn (basis.bindings.InteropTypedPtr, i32) callconv(.c) void;
pub const basis_zig_PlayerController_allocMsgParams_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) u64;
pub const basis_zig_PlayerController_sendMessage_cb = *const fn (basis.bindings.InteropTypedPtr, i32, u64) callconv(.c) void;

// ===============================

// class DebugDraw

pub const basis_zig_DebugDraw_drawLine2D_cb = *const fn (c_int, c_int, c_int, c_int, [*c]const basis.bindings.InteropColor, [*c]const basis.bindings.InteropColor) callconv(.c) void;
pub const basis_zig_DebugDraw_drawLine3D_cb = *const fn ([*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropColor, [*c]const basis.bindings.InteropColor) callconv(.c) void;
pub const basis_zig_DebugDraw_drawAxisCross_cb = *const fn ([*c]const basis.bindings.InteropVec3, f32) callconv(.c) void;
pub const basis_zig_DebugDraw_drawSphere_cb = *const fn ([*c]const basis.bindings.InteropVec3, f32, [*c]const basis.bindings.InteropColor, c_int) callconv(.c) void;
pub const basis_zig_DebugDraw_drawTriangle3D_cb = *const fn ([*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropColor, [*c]const basis.bindings.InteropColor, [*c]const basis.bindings.InteropColor) callconv(.c) void;
pub const basis_zig_DebugDraw_drawString_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropColor) callconv(.c) void;
pub const basis_zig_DebugDraw_drawStringXY_cb = *const fn ([*c]const basis.bindings.InteropString, c_int, c_int, [*c]const basis.bindings.InteropColor, c_int) callconv(.c) void;

// ===============================

// class GameObject

pub const basis_zig_GameObject_getName_cb = *const fn (u64, [*c]basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_GameObject_getType_cb = *const fn (u64, [*c]basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_GameObject_getComponentPtrByShortName_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) u64;
pub const basis_zig_GameObject_getComponentPtrByTypeName_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) u64;
pub const basis_zig_GameObject_addGameObjectMeshInstanceMapping_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_GameObject_removeGameObjectMeshInstanceMapping_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_GameObject_getNameHash_cb = *const fn (u64) callconv(.c) u32;
pub const basis_zig_GameObject_getWorldTransform_cb = *const fn (u64, [*c]basis.bindings.InteropVec3, [*c]basis.bindings.InteropQuaternion) callconv(.c) c_int;
pub const basis_zig_GameObject_setWorldTransform_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion, c_int) callconv(.c) c_int;
pub const basis_zig_GameObject_getMeshComponentData_cb = *const fn (u64, [*c]const basis.bindings.InteropString, [*c]u64, [*c]u64, [*c]u64) callconv(.c) c_int;
pub const basis_zig_GameObject_getPhysicsActor_cb = *const fn (u64, [*c]u64, [*c]u32) callconv(.c) c_int;
pub const basis_zig_GameObject_setGameTag_cb = *const fn (u64, u32) callconv(.c) void;
pub const basis_zig_GameObject_getGameTag_cb = *const fn (u64) callconv(.c) u32;
pub const basis_zig_GameObject_getRenderSceneNode_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_GameObject_getNavMeshObstacleIDs_cb = *const fn (u64, u32, [*c]u32, u32) callconv(.c) u32;

// ===============================

// class ComponentContext

pub const basis_zig_ComponentContext_getName_cb = *const fn (basis.bindings.InteropTypedPtr, [*c]basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_ComponentContext_onClient_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) c_int;
pub const basis_zig_ComponentContext_inEditor_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) c_int;
pub const basis_zig_ComponentContext_getClient_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) u64;
pub const basis_zig_ComponentContext_getServer_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) u64;
pub const basis_zig_ComponentContext_getGameObject_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) u64;
pub const basis_zig_ComponentContext_subscribeToMessageCategory_cb = *const fn (basis.bindings.InteropTypedPtr, i32) callconv(.c) void;
pub const basis_zig_ComponentContext_allocMsgParams_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) u64;
pub const basis_zig_ComponentContext_sendMessage_cb = *const fn (basis.bindings.InteropTypedPtr, i32, u64) callconv(.c) void;
pub const basis_zig_ComponentContext_getPhysicsEnginePtr_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) u64;
pub const basis_zig_ComponentContext_getPrimaryPhysicsScene_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) u64;
pub const basis_zig_ComponentContext_getRenderer_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) u64;
pub const basis_zig_ComponentContext_getGameSession_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) u64;
pub const basis_zig_ComponentContext_getGameState_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) u64;
pub const basis_zig_ComponentContext_getPosition_cb = *const fn (basis.bindings.InteropTypedPtr, [*c]basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_ComponentContext_setPosition_cb = *const fn (basis.bindings.InteropTypedPtr, [*c]const basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_ComponentContext_getOrientation_cb = *const fn (basis.bindings.InteropTypedPtr, [*c]basis.bindings.InteropQuaternion) callconv(.c) void;
pub const basis_zig_ComponentContext_setOrientation_cb = *const fn (basis.bindings.InteropTypedPtr, [*c]const basis.bindings.InteropQuaternion) callconv(.c) void;
pub const basis_zig_ComponentContext_getLinearVelocity_cb = *const fn (basis.bindings.InteropTypedPtr, [*c]basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_ComponentContext_getAngularVelocity_cb = *const fn (basis.bindings.InteropTypedPtr, [*c]basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_ComponentContext_setTransform_cb = *const fn (basis.bindings.InteropTypedPtr, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion, c_int) callconv(.c) void;
pub const basis_zig_ComponentContext_setTransformWithVelocities_cb = *const fn (basis.bindings.InteropTypedPtr, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropVec3, c_int) callconv(.c) void;
pub const basis_zig_ComponentContext_getWorldMatrix_cb = *const fn (basis.bindings.InteropTypedPtr, [*c]basis.bindings.InteropMat43) callconv(.c) void;
pub const basis_zig_ComponentContext_getRenderSceneNode_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) u64;
pub const basis_zig_ComponentContext_isClientLocalAvatar_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) c_int;
pub const basis_zig_ComponentContext_getAvatarHostID_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) i32;
pub const basis_zig_ComponentContext_getInputRange_cb = *const fn (basis.bindings.InteropTypedPtr, u16) callconv(.c) f32;
pub const basis_zig_ComponentContext_getInputState_cb = *const fn (basis.bindings.InteropTypedPtr, u16) callconv(.c) c_int;
pub const basis_zig_ComponentContext_getInputAction_cb = *const fn (basis.bindings.InteropTypedPtr, u16) callconv(.c) c_int;
pub const basis_zig_ComponentContext_getCharacterController_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) u64;
pub const basis_zig_ComponentContext_getPhysicsActor_cb = *const fn (basis.bindings.InteropTypedPtr, [*c]u64, [*c]u32) callconv(.c) c_int;
pub const basis_zig_ComponentContext_flushExposedProperties_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) void;
pub const basis_zig_ComponentContext_getParentGameObject_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) u64;
pub const basis_zig_ComponentContext_registerPipe_cb = *const fn (basis.bindings.InteropTypedPtr, [*c]const basis.bindings.InteropString, c_int, c_int) callconv(.c) u64;
pub const basis_zig_ComponentContext_writeToPipe_cb = *const fn (basis.bindings.InteropTypedPtr, u64, [*c]const u8, u32) callconv(.c) void;
pub const basis_zig_ComponentContext_callScriptOnTick_cb = *const fn (basis.bindings.InteropTypedPtr, f32) callconv(.c) void;
pub const basis_zig_ComponentContext_getScriptFunctionByDecl_cb = *const fn (basis.bindings.InteropTypedPtr, [*c]const basis.bindings.InteropString) callconv(.c) u64;
pub const basis_zig_ComponentContext_getScriptFunctionByASFuncPtr_cb = *const fn (basis.bindings.InteropTypedPtr, u64) callconv(.c) u64;
pub const basis_zig_ComponentContext_setScriptGlobalHandle_cb = *const fn (basis.bindings.InteropTypedPtr, [*c]const basis.bindings.InteropString, u64) callconv(.c) void;

// ===============================

// class AngelScriptFunction

pub const basis_zig_AngelScriptFunction_prepareCall_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_AngelScriptFunction_setBoolParam_cb = *const fn (u64, u32, c_int) callconv(.c) void;
pub const basis_zig_AngelScriptFunction_setIntParam_cb = *const fn (u64, u32, c_int) callconv(.c) void;
pub const basis_zig_AngelScriptFunction_setUintParam_cb = *const fn (u64, u32, u32) callconv(.c) void;
pub const basis_zig_AngelScriptFunction_setFloatParam_cb = *const fn (u64, u32, f32) callconv(.c) void;
pub const basis_zig_AngelScriptFunction_setStringParam_cb = *const fn (u64, u32, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_AngelScriptFunction_setGameObjectRefParam_cb = *const fn (u64, u32, u32, u64, c_int) callconv(.c) void;
pub const basis_zig_AngelScriptFunction_getReturnBool_cb = *const fn (u64) callconv(.c) c_int;
pub const basis_zig_AngelScriptFunction_getReturnInt_cb = *const fn (u64) callconv(.c) c_int;
pub const basis_zig_AngelScriptFunction_getReturnUint_cb = *const fn (u64) callconv(.c) u32;
pub const basis_zig_AngelScriptFunction_getReturnFloat_cb = *const fn (u64) callconv(.c) f32;
pub const basis_zig_AngelScriptFunction_executeCall_cb = *const fn (u64) callconv(.c) void;

// ===============================

// class MessageParameters

pub const basis_zig_MessageParameters_addInt_cb = *const fn (u64, i32) callconv(.c) void;
pub const basis_zig_MessageParameters_getInt_cb = *const fn (u64) callconv(.c) i32;
pub const basis_zig_MessageParameters_addUint_cb = *const fn (u64, u32) callconv(.c) void;
pub const basis_zig_MessageParameters_getUint_cb = *const fn (u64) callconv(.c) u32;
pub const basis_zig_MessageParameters_addUint64_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_MessageParameters_getUint64_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_MessageParameters_addFloat_cb = *const fn (u64, f32) callconv(.c) void;
pub const basis_zig_MessageParameters_getFloat_cb = *const fn (u64) callconv(.c) f32;
pub const basis_zig_MessageParameters_addVec3_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_MessageParameters_getVec3_cb = *const fn (u64, [*c]basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_MessageParameters_addVec4_cb = *const fn (u64, [*c]const basis.bindings.InteropVec4) callconv(.c) void;
pub const basis_zig_MessageParameters_getVec4_cb = *const fn (u64, [*c]basis.bindings.InteropVec4) callconv(.c) void;
pub const basis_zig_MessageParameters_addQuaternion_cb = *const fn (u64, [*c]const basis.bindings.InteropQuaternion) callconv(.c) void;
pub const basis_zig_MessageParameters_getQuaternion_cb = *const fn (u64, [*c]basis.bindings.InteropQuaternion) callconv(.c) void;
pub const basis_zig_MessageParameters_addString_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_MessageParameters_getString_cb = *const fn (u64, [*c]basis.bindings.InteropString) callconv(.c) void;

// ===============================

// class MessageNode

pub const basis_zig_MessageNode_destroy_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_MessageNode_subscribeToMessageCategory_cb = *const fn (u64, i32) callconv(.c) void;
pub const basis_zig_MessageNode_allocMsgParams_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_MessageNode_sendMessage_cb = *const fn (u64, i32, u64) callconv(.c) void;

// ===============================

// class InputManager

pub const basis_zig_InputManager_addGameInputContextToFront_cb = *const fn (u8) callconv(.c) void;
pub const basis_zig_InputManager_addGameInputContextToBack_cb = *const fn (u8) callconv(.c) void;
pub const basis_zig_InputManager_isGameInputContextEnabled_cb = *const fn (u8) callconv(.c) c_int;
pub const basis_zig_InputManager_removeGameInputContext_cb = *const fn (u8) callconv(.c) void;
pub const basis_zig_InputManager_getNFirstEnabledInputContexts_cb = *const fn ([*c]u8, u32) callconv(.c) u32;
pub const basis_zig_InputManager_isCursorLocked_cb = *const fn () callconv(.c) c_int;
pub const basis_zig_InputManager_lockCursor_cb = *const fn () callconv(.c) void;
pub const basis_zig_InputManager_releaseCursor_cb = *const fn () callconv(.c) void;
pub const basis_zig_InputManager_getGameInputMode_cb = *const fn () callconv(.c) i32;
pub const basis_zig_InputManager_isKeyPressed_cb = *const fn (u32) callconv(.c) c_int;
pub const basis_zig_InputManager_isMouseButtonPressed_cb = *const fn (u32) callconv(.c) c_int;
pub const basis_zig_InputManager_isGamepadButtonDown_cb = *const fn (i32) callconv(.c) c_int;
pub const basis_zig_InputManager_getGamepadThumbstick_cb = *const fn (i32, [*c]basis.bindings.InteropVec2) callconv(.c) void;
pub const basis_zig_InputManager_setGamepadVibration_cb = *const fn (i32, f32, f32) callconv(.c) void;
pub const basis_zig_InputManager_getMappedKeyCode_cb = *const fn (u16, u8, c_int, [*c]i32) callconv(.c) c_int;
pub const basis_zig_InputManager_getMappedMouseButton_cb = *const fn (u16, u8, c_int, [*c]i32) callconv(.c) c_int;
pub const basis_zig_InputManager_getMappedGamepadButton_cb = *const fn (u16, u8, c_int, [*c]i32) callconv(.c) c_int;
pub const basis_zig_InputManager_getMappedInputSource_cb = *const fn (u16, u8, c_int, c_int, [*c]i32) callconv(.c) c_int;
pub const basis_zig_InputManager_getFirstPressedKey_cb = *const fn () callconv(.c) i32;
pub const basis_zig_InputManager_getFirstPressedMouseButton_cb = *const fn () callconv(.c) i32;
pub const basis_zig_InputManager_getKeyName_cb = *const fn (u32, [*c]u8, u32) callconv(.c) u32;

// ===============================

// class PropagatedValue

pub const basis_zig_PropagatedValue_createFloat_cb = *const fn (basis.bindings.InteropTypedPtr, u64, [*c]const basis.bindings.InteropString, c_int, c_int, f32) callconv(.c) u64;
pub const basis_zig_PropagatedValue_createDouble_cb = *const fn (basis.bindings.InteropTypedPtr, u64, [*c]const basis.bindings.InteropString, c_int, c_int, f64) callconv(.c) u64;
pub const basis_zig_PropagatedValue_createInt32_cb = *const fn (basis.bindings.InteropTypedPtr, u64, [*c]const basis.bindings.InteropString, c_int, c_int, i32) callconv(.c) u64;
pub const basis_zig_PropagatedValue_createUint32_cb = *const fn (basis.bindings.InteropTypedPtr, u64, [*c]const basis.bindings.InteropString, c_int, c_int, u32) callconv(.c) u64;
pub const basis_zig_PropagatedValue_createInt16_cb = *const fn (basis.bindings.InteropTypedPtr, u64, [*c]const basis.bindings.InteropString, c_int, c_int, i16) callconv(.c) u64;
pub const basis_zig_PropagatedValue_createUint16_cb = *const fn (basis.bindings.InteropTypedPtr, u64, [*c]const basis.bindings.InteropString, c_int, c_int, u16) callconv(.c) u64;
pub const basis_zig_PropagatedValue_createInt64_cb = *const fn (basis.bindings.InteropTypedPtr, u64, [*c]const basis.bindings.InteropString, c_int, c_int, i64) callconv(.c) u64;
pub const basis_zig_PropagatedValue_createUint64_cb = *const fn (basis.bindings.InteropTypedPtr, u64, [*c]const basis.bindings.InteropString, c_int, c_int, u64) callconv(.c) u64;
pub const basis_zig_PropagatedValue_createInt8_cb = *const fn (basis.bindings.InteropTypedPtr, u64, [*c]const basis.bindings.InteropString, c_int, c_int, i8) callconv(.c) u64;
pub const basis_zig_PropagatedValue_createUint8_cb = *const fn (basis.bindings.InteropTypedPtr, u64, [*c]const basis.bindings.InteropString, c_int, c_int, u8) callconv(.c) u64;
pub const basis_zig_PropagatedValue_createBool_cb = *const fn (basis.bindings.InteropTypedPtr, u64, [*c]const basis.bindings.InteropString, c_int, c_int, c_int) callconv(.c) u64;
pub const basis_zig_PropagatedValue_createVec2_cb = *const fn (basis.bindings.InteropTypedPtr, u64, [*c]const basis.bindings.InteropString, c_int, c_int, [*c]const basis.bindings.InteropVec2) callconv(.c) u64;
pub const basis_zig_PropagatedValue_createVec3_cb = *const fn (basis.bindings.InteropTypedPtr, u64, [*c]const basis.bindings.InteropString, c_int, c_int, [*c]const basis.bindings.InteropVec3) callconv(.c) u64;
pub const basis_zig_PropagatedValue_createVec4_cb = *const fn (basis.bindings.InteropTypedPtr, u64, [*c]const basis.bindings.InteropString, c_int, c_int, [*c]const basis.bindings.InteropVec4) callconv(.c) u64;
pub const basis_zig_PropagatedValue_createQuaternion_cb = *const fn (basis.bindings.InteropTypedPtr, u64, [*c]const basis.bindings.InteropString, c_int, c_int, [*c]const basis.bindings.InteropQuaternion) callconv(.c) u64;
pub const basis_zig_PropagatedValue_createMat43_cb = *const fn (basis.bindings.InteropTypedPtr, u64, [*c]const basis.bindings.InteropString, c_int, c_int, [*c]const basis.bindings.InteropMat43) callconv(.c) u64;
pub const basis_zig_PropagatedValue_setFloat_cb = *const fn (u64, f32) callconv(.c) void;
pub const basis_zig_PropagatedValue_setDouble_cb = *const fn (u64, f64) callconv(.c) void;
pub const basis_zig_PropagatedValue_setInt32_cb = *const fn (u64, i32) callconv(.c) void;
pub const basis_zig_PropagatedValue_setUint32_cb = *const fn (u64, u32) callconv(.c) void;
pub const basis_zig_PropagatedValue_setInt16_cb = *const fn (u64, i16) callconv(.c) void;
pub const basis_zig_PropagatedValue_setUint16_cb = *const fn (u64, u16) callconv(.c) void;
pub const basis_zig_PropagatedValue_setInt64_cb = *const fn (u64, i64) callconv(.c) void;
pub const basis_zig_PropagatedValue_setUint64_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_PropagatedValue_setInt8_cb = *const fn (u64, i8) callconv(.c) void;
pub const basis_zig_PropagatedValue_setUint8_cb = *const fn (u64, u8) callconv(.c) void;
pub const basis_zig_PropagatedValue_setBool_cb = *const fn (u64, c_int) callconv(.c) void;
pub const basis_zig_PropagatedValue_setVec2_cb = *const fn (u64, [*c]const basis.bindings.InteropVec2) callconv(.c) void;
pub const basis_zig_PropagatedValue_setVec3_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_PropagatedValue_setVec4_cb = *const fn (u64, [*c]const basis.bindings.InteropVec4) callconv(.c) void;
pub const basis_zig_PropagatedValue_setQuaternion_cb = *const fn (u64, [*c]const basis.bindings.InteropQuaternion) callconv(.c) void;
pub const basis_zig_PropagatedValue_setMat43_cb = *const fn (u64, [*c]const basis.bindings.InteropMat43) callconv(.c) void;
pub const basis_zig_PropagatedValue_createAction_cb = *const fn (basis.bindings.InteropTypedPtr, u64, [*c]const basis.bindings.InteropString, c_int, c_int) callconv(.c) u64;
pub const basis_zig_PropagatedValue_fireAction_cb = *const fn (u64) callconv(.c) void;

// ===============================

// class SceneNode

pub const basis_zig_SceneNode_newNode_cb = *const fn () callconv(.c) u64;
pub const basis_zig_SceneNode_deleteNode_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_SceneNode_createChildNode_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_SceneNode_destroyChildNode_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_SceneNode_detachAll_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_SceneNode_destroyAllChildNodes_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_SceneNode_setPosition_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, c_int, c_int) callconv(.c) void;
pub const basis_zig_SceneNode_getPosition_cb = *const fn (u64, c_int, [*c]basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_SceneNode_setOrientation_cb = *const fn (u64, [*c]const basis.bindings.InteropQuaternion, c_int, c_int) callconv(.c) void;
pub const basis_zig_SceneNode_getOrientation_cb = *const fn (u64, c_int, [*c]basis.bindings.InteropQuaternion) callconv(.c) void;
pub const basis_zig_SceneNode_setScale_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, c_int) callconv(.c) void;
pub const basis_zig_SceneNode_getScale_cb = *const fn (u64, [*c]basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_SceneNode_translate_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, c_int, c_int) callconv(.c) void;
pub const basis_zig_SceneNode_yaw_cb = *const fn (u64, f32, c_int, c_int) callconv(.c) void;
pub const basis_zig_SceneNode_pitch_cb = *const fn (u64, f32, c_int, c_int) callconv(.c) void;
pub const basis_zig_SceneNode_roll_cb = *const fn (u64, f32, c_int, c_int) callconv(.c) void;
pub const basis_zig_SceneNode_lookAtSceneNode_cb = *const fn (u64, u64, c_int) callconv(.c) void;
pub const basis_zig_SceneNode_attachMeshInstance_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_SceneNode_detachMeshInstance_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_SceneNode_isMeshInstanceAttached_cb = *const fn (u64, u64) callconv(.c) i32;
pub const basis_zig_SceneNode_attachCamera_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_SceneNode_detachCamera_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_SceneNode_isCameraAttached_cb = *const fn (u64, u64) callconv(.c) i32;
pub const basis_zig_SceneNode_getLocalToParentTransform_cb = *const fn (u64, [*c]basis.bindings.InteropMat43) callconv(.c) void;
pub const basis_zig_SceneNode_getLocalToWorldTransform_cb = *const fn (u64, [*c]basis.bindings.InteropMat43) callconv(.c) void;
pub const basis_zig_SceneNode_getLocalToAncestorTransform_cb = *const fn (u64, u64, [*c]basis.bindings.InteropMat43) callconv(.c) void;

// ===============================

// class PhysicsScene

pub const basis_zig_PhysicsScene_addActor_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_PhysicsScene_removeActor_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_PhysicsScene_addVehicleController_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_PhysicsScene_removeVehicleController_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_PhysicsScene_addJoint_cb = *const fn (u64, u64, u32) callconv(.c) void;
pub const basis_zig_PhysicsScene_removeJoint_cb = *const fn (u64, u64, u32) callconv(.c) void;
pub const basis_zig_PhysicsScene_applyRadialForce_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, f32, f32, u32, c_int) callconv(.c) void;
pub const basis_zig_PhysicsScene_applyRadialImpulse_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, f32, f32, u32, c_int) callconv(.c) void;
pub const basis_zig_PhysicsScene_sphereSweep_cb = *const fn (u64, f32, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropVec3, f32, [*c]basis.bindings.PhysicsInteropRayCastResult) callconv(.c) c_int;
pub const basis_zig_PhysicsScene_sphereSweepEx_cb = *const fn (u64, f32, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropVec3, f32, [*c]basis.bindings.PhysicsInteropRayCastResult, u32, u32) callconv(.c) u32;
pub const basis_zig_PhysicsScene_getSphereOverlapping_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, f32) callconv(.c) u32;
pub const basis_zig_PhysicsScene_castRay_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropVec3, f32, [*c]basis.bindings.PhysicsInteropRayCastResult) callconv(.c) c_int;
pub const basis_zig_PhysicsScene_castRayEx_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropVec3, f32, [*c]basis.bindings.PhysicsInteropRayCastResult, u32) callconv(.c) c_int;
pub const basis_zig_PhysicsScene_castRayWithCallback_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropVec3, f32, [*c]basis.bindings.PhysicsInteropRayCastResult, u32, u64, c_int, basis.bindings.FP_i32_IntPtr_IntPtr64_u32, basis.bindings.FP_i32_IntPtr_IntPtr64_u32_Vec3_Vec3) callconv(.c) c_int;
pub const basis_zig_PhysicsScene_setCollisionCallbacksEnabled_cb = *const fn (u64, c_int) callconv(.c) void;

// ===============================

// class PhysicsMaterial

pub const basis_zig_PhysicsMaterial_getDefaultMaterial_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_PhysicsMaterial_getBaseMaterial_cb = *const fn (u64, u32) callconv(.c) u64;
pub const basis_zig_PhysicsMaterial_createMaterial_cb = *const fn (u64, c_int, f32, f32, f32, c_int, c_int) callconv(.c) u64;
pub const basis_zig_PhysicsMaterial_getBasePhysicsMaterialName_cb = *const fn (u64) callconv(.c) u32;
pub const basis_zig_PhysicsMaterial_addRef_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_PhysicsMaterial_release_cb = *const fn (u64) callconv(.c) void;

// ===============================

// class PhysicsShape

pub const basis_zig_PhysicsShape_createBox_cb = *const fn (u64, f32, f32, f32, u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion, c_int) callconv(.c) u64;
pub const basis_zig_PhysicsShape_createSphere_cb = *const fn (u64, f32, u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion, c_int) callconv(.c) u64;
pub const basis_zig_PhysicsShape_createCapsule_cb = *const fn (u64, f32, f32, u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion, c_int) callconv(.c) u64;
pub const basis_zig_PhysicsShape_createCylinder_cb = *const fn (u64, f32, f32, u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion, c_int) callconv(.c) u64;
pub const basis_zig_PhysicsShape_createCylinderX_cb = *const fn (u64, f32, f32, u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion, c_int) callconv(.c) u64;
pub const basis_zig_PhysicsShape_createCylinderZ_cb = *const fn (u64, f32, f32, u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion, c_int) callconv(.c) u64;
pub const basis_zig_PhysicsShape_addRef_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_PhysicsShape_release_cb = *const fn (u64) callconv(.c) void;

// ===============================

// class PhysicsActor

pub const basis_zig_PhysicsActor_createRigidBodyDynamic_cb = *const fn (u64, [*c]u64, u32, f32, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion, c_int, c_int) callconv(.c) u64;
pub const basis_zig_PhysicsActor_createRigidBodyStatic_cb = *const fn (u64, [*c]u64, u32, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion) callconv(.c) u64;
pub const basis_zig_PhysicsActor_createBoxTrigger_cb = *const fn (basis.bindings.InteropTypedPtr, u64, f32, f32, f32, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion, c_int, c_int) callconv(.c) u64;
pub const basis_zig_PhysicsActor_createSphereTrigger_cb = *const fn (basis.bindings.InteropTypedPtr, u64, f32, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion, c_int, c_int) callconv(.c) u64;
pub const basis_zig_PhysicsActor_setWorldTransform_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion) callconv(.c) void;
pub const basis_zig_PhysicsActor_getWorldTransform_cb = *const fn (u64, [*c]basis.bindings.InteropVec3, [*c]basis.bindings.InteropQuaternion) callconv(.c) void;
pub const basis_zig_PhysicsActor_setKinematicTarget_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion) callconv(.c) void;
pub const basis_zig_PhysicsActor_setMassData_cb = *const fn (u64, f32, [*c]const basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_PhysicsActor_setContactReportThreshold_cb = *const fn (u64, f32) callconv(.c) void;
pub const basis_zig_PhysicsActor_setSolverIterationCounts_cb = *const fn (u64, u32, u32) callconv(.c) void;
pub const basis_zig_PhysicsActor_setAngularDamping_cb = *const fn (u64, f32) callconv(.c) void;
pub const basis_zig_PhysicsActor_setMaxAngularVelocity_cb = *const fn (u64, f32) callconv(.c) void;
pub const basis_zig_PhysicsActor_getWorldBounds_cb = *const fn (u64, [*c]basis.bindings.InteropVec3, [*c]basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_PhysicsActor_associateWithGameObject_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_PhysicsActor_getAssociatedGameObject_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_PhysicsActor_isSleeping_cb = *const fn (u64) callconv(.c) c_int;
pub const basis_zig_PhysicsActor_wakeUp_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_PhysicsActor_putToSleep_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_PhysicsActor_setLinearVelocity_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_PhysicsActor_getLinearVelocity_cb = *const fn (u64, [*c]basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_PhysicsActor_setAngularVelocity_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_PhysicsActor_getAngularVelocity_cb = *const fn (u64, [*c]basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_PhysicsActor_addForce_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropVec3, c_int) callconv(.c) void;
pub const basis_zig_PhysicsActor_addImpulse_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropVec3, c_int) callconv(.c) void;
pub const basis_zig_PhysicsActor_addRef_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_PhysicsActor_release_cb = *const fn (u64) callconv(.c) void;

// ===============================

// class PhysicsJoint

pub const basis_zig_PhysicsJoint_createFixedJoint_cb = *const fn (u64, u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion, u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion) callconv(.c) u64;
pub const basis_zig_PhysicsJoint_createSphericalJoint_cb = *const fn (u64, u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion, u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion) callconv(.c) u64;
pub const basis_zig_PhysicsJoint_createDistanceJoint_cb = *const fn (u64, u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion, u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion) callconv(.c) u64;
pub const basis_zig_PhysicsJoint_createDof6Joint_cb = *const fn (u64, u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion, u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion) callconv(.c) u64;
pub const basis_zig_PhysicsJoint_createSphericalSpringJoint_cb = *const fn (u64, u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion, u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion, f32, f32, f32) callconv(.c) u64;
pub const basis_zig_PhysicsJoint_enableProjection_cb = *const fn (u64, u32, c_int, f32, f32) callconv(.c) void;
pub const basis_zig_PhysicsJoint_setBreakForce_cb = *const fn (u64, u32, f32, f32) callconv(.c) void;
pub const basis_zig_PhysicsJoint_setDof6Motion_cb = *const fn (u64, u32, u32) callconv(.c) void;
pub const basis_zig_PhysicsJoint_setDof6Drive_cb = *const fn (u64, u32, f32, f32, f32, c_int) callconv(.c) void;
pub const basis_zig_PhysicsJoint_setDof6TwistLimit_cb = *const fn (u64, f32, f32) callconv(.c) void;
pub const basis_zig_PhysicsJoint_setDriveGoalPose_cb = *const fn (u64, u32, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion) callconv(.c) void;
pub const basis_zig_PhysicsJoint_getConstraintForce_cb = *const fn (u64, u32, [*c]basis.bindings.InteropVec3, [*c]basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_PhysicsJoint_setInvMassScale0_cb = *const fn (u64, u32, f32) callconv(.c) void;
pub const basis_zig_PhysicsJoint_setInvInertiaScale0_cb = *const fn (u64, u32, f32) callconv(.c) void;
pub const basis_zig_PhysicsJoint_setInvMassScale1_cb = *const fn (u64, u32, f32) callconv(.c) void;
pub const basis_zig_PhysicsJoint_setInvInertiaScale1_cb = *const fn (u64, u32, f32) callconv(.c) void;
pub const basis_zig_PhysicsJoint_getInvMassScale0_cb = *const fn (u64, u32) callconv(.c) f32;
pub const basis_zig_PhysicsJoint_getInvInertiaScale0_cb = *const fn (u64, u32) callconv(.c) f32;
pub const basis_zig_PhysicsJoint_getInvMassScale1_cb = *const fn (u64, u32) callconv(.c) f32;
pub const basis_zig_PhysicsJoint_getInvInertiaScale1_cb = *const fn (u64, u32) callconv(.c) f32;
pub const basis_zig_PhysicsJoint_addRef_cb = *const fn (u64, u32) callconv(.c) void;
pub const basis_zig_PhysicsJoint_release_cb = *const fn (u64, u32) callconv(.c) void;

// ===============================

// class PhysicsTriMesh

pub const basis_zig_PhysicsTriMesh_createTriMesh_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) u64;
pub const basis_zig_PhysicsTriMesh_getTriangleCount_cb = *const fn (u64) callconv(.c) u32;
pub const basis_zig_PhysicsTriMesh_getTriangleVertices_cb = *const fn (u64, u32, [*c]basis.bindings.InteropVec3, [*c]basis.bindings.InteropVec3, [*c]basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_PhysicsTriMesh_pointDistance_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion, [*c]basis.bindings.InteropVec3, [*c]u32) callconv(.c) f32;
pub const basis_zig_PhysicsTriMesh_addRef_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_PhysicsTriMesh_release_cb = *const fn (u64) callconv(.c) void;

// ===============================

// class CharacterController

pub const basis_zig_CharacterController_setMovementVector_cb = *const fn (u64, [*c]const basis.bindings.InteropVec2) callconv(.c) void;
pub const basis_zig_CharacterController_getMovementVector_cb = *const fn (u64, [*c]basis.bindings.InteropVec2) callconv(.c) void;
pub const basis_zig_CharacterController_getLinearVelocity_cb = *const fn (u64, [*c]basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_CharacterController_addRef_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_CharacterController_release_cb = *const fn (u64) callconv(.c) void;

// ===============================

// class VehicleController

pub const basis_zig_VehicleController_createVehicleController_cb = *const fn (u64, [*c]const basis.bindings.InteropVehCtrlDesc, i32) callconv(.c) u64;
pub const basis_zig_VehicleController_reinit_cb = *const fn (u64, [*c]const basis.bindings.InteropVehCtrlDesc) callconv(.c) void;
pub const basis_zig_VehicleController_setInputData_cb = *const fn (u64, [*c]const basis.bindings.InteropVehInputData) callconv(.c) void;
pub const basis_zig_VehicleController_getInputData_cb = *const fn (u64, [*c]basis.bindings.InteropVehInputData) callconv(.c) void;
pub const basis_zig_VehicleController_startGearChange_cb = *const fn (u64, i32) callconv(.c) void;
pub const basis_zig_VehicleController_forceGearChange_cb = *const fn (u64, i32) callconv(.c) void;
pub const basis_zig_VehicleController_freezeInputData_cb = *const fn (u64, c_int) callconv(.c) void;
pub const basis_zig_VehicleController_unfreezeInputData_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_VehicleController_getWheelCount_cb = *const fn (u64) callconv(.c) u32;
pub const basis_zig_VehicleController_getWheelStateInfo_cb = *const fn (u64, u32, [*c]basis.bindings.InteropVehWheelStateInfo) callconv(.c) void;
pub const basis_zig_VehicleController_getStateInfo_cb = *const fn (u64, [*c]basis.bindings.InteropVehStateInfo) callconv(.c) void;
pub const basis_zig_VehicleController_getFastestWheelRotationSpeed_cb = *const fn (u64) callconv(.c) f32;
pub const basis_zig_VehicleController_addRef_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_VehicleController_release_cb = *const fn (u64) callconv(.c) void;

// ===============================

// class ResourceManager

pub const basis_zig_ResourceManager_init_cb = *const fn () callconv(.c) u64;
pub const basis_zig_ResourceManager_deinit_cb = *const fn () callconv(.c) void;
pub const basis_zig_ResourceManager_acquireResource_cb = *const fn (u64, [*c]const basis.bindings.InteropString, i32) callconv(.c) u64;
pub const basis_zig_ResourceManager_lock_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_ResourceManager_unlock_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_ResourceManager_registerResourceReloadedCallback_cb = *const fn (u64, u32) callconv(.c) void;
pub const basis_zig_ResourceManager_unregisterResourceReloadedCallback_cb = *const fn (u64, u32) callconv(.c) void;
pub const basis_zig_ResourceManager_beginGetResourcesWithFileExtension_cb = *const fn (u64, [*c]const basis.bindings.InteropString, [*c]u32) callconv(.c) [*c]const basis.bindings.InteropString;
pub const basis_zig_ResourceManager_endGetResourcesWithFileExtension_cb = *const fn () callconv(.c) void;
pub const basis_zig_ResourceManager_addLooseFileResourcePack_cb = *const fn (u64, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropLooseFileMapping, u32) callconv(.c) void;
pub const basis_zig_ResourceManager_getSourceFilePathForResource_cb = *const fn (u64, [*c]const basis.bindings.InteropString, [*c]basis.bindings.InteropString) callconv(.c) c_int;

// ===============================

// class Resource

pub const basis_zig_Resource_getSharedMesh_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_Resource_hasPhysicsMesh_cb = *const fn (u64) callconv(.c) c_int;
pub const basis_zig_Resource_getPhysicsMeshData_cb = *const fn (u64, [*c]basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_Resource_getSharedMaterial_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_Resource_getRawData_cb = *const fn (u64, [*c]basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_Resource_addRef_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_Resource_release_cb = *const fn (u64) callconv(.c) void;

// ===============================

// class Renderer

pub const basis_zig_Renderer_getPrimaryScene_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_Renderer_addCameraToBackOfQueue_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_Renderer_addCameraToFrontOfQueue_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_Renderer_removeCameraFromQueue_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_Renderer_getMainCamera_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_Renderer_getWindowWidth_cb = *const fn (u64) callconv(.c) u32;
pub const basis_zig_Renderer_getWindowHeight_cb = *const fn (u64) callconv(.c) u32;
pub const basis_zig_Renderer_getRenderWidth_cb = *const fn (u64) callconv(.c) u32;
pub const basis_zig_Renderer_getRenderHeight_cb = *const fn (u64) callconv(.c) u32;
pub const basis_zig_Renderer_getRenderScale_cb = *const fn (u64) callconv(.c) f32;
pub const basis_zig_Renderer_setRenderScale_cb = *const fn (u64, f32) callconv(.c) void;
pub const basis_zig_Renderer_setGraphicsOption_cb = *const fn (u64, c_int, c_int) callconv(.c) void;
pub const basis_zig_Renderer_createMesh_cb = *const fn (u64, u64, c_int, [*c]const basis.bindings.InteropString) callconv(.c) u64;
pub const basis_zig_Renderer_createMeshManual_cb = *const fn (u64, c_int, u32, u32, [*c]const basis.bindings.InteropString) callconv(.c) u64;
pub const basis_zig_Renderer_captureSinglePre2DFrame_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_Renderer_captureSingleFullEndUserFrame_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_Renderer_captureSingleFullFrame_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_Renderer_startCapturingPre2DFrames_cb = *const fn (u64, [*c]const basis.bindings.InteropString, c_int, u32) callconv(.c) void;
pub const basis_zig_Renderer_startCapturingFullEndUserFrames_cb = *const fn (u64, [*c]const basis.bindings.InteropString, c_int, u32) callconv(.c) void;
pub const basis_zig_Renderer_startCapturingFullFrames_cb = *const fn (u64, [*c]const basis.bindings.InteropString, c_int, u32) callconv(.c) void;
pub const basis_zig_Renderer_stopCapturingFrames_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_Renderer_applyDisplayOptions_cb = *const fn (u64, c_int, c_int, c_int, c_int, c_int) callconv(.c) void;
pub const basis_zig_Renderer_applyVsyncAndFramerateLimit_cb = *const fn (u64, c_int, c_int) callconv(.c) void;
pub const basis_zig_Renderer_getWindowMode_cb = *const fn (u64) callconv(.c) c_int;
pub const basis_zig_Renderer_getDisplacementEffectRenderer_cb = *const fn (u64) callconv(.c) u64;

// ===============================

// class RenderScene

pub const basis_zig_RenderScene_getRootSceneNode_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_RenderScene_destroySceneNode_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_RenderScene_createCamera_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_RenderScene_destroyCamera_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_RenderScene_createDynamicMeshInstance_cb = *const fn (u64, u64, [*c]u64, u32) callconv(.c) u64;
pub const basis_zig_RenderScene_createStaticMeshInstance_cb = *const fn (u64, u64, [*c]u64, u32, c_int) callconv(.c) u64;
pub const basis_zig_RenderScene_destroyMeshInstance_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_RenderScene_castRay_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropVec3, [*c]basis.bindings.RendererInteropRayCastResult, u32, c_int) callconv(.c) c_int;
pub const basis_zig_RenderScene_getTireTrackRenderer_cb = *const fn (u64) callconv(.c) u64;

// ===============================

// class TireTrackRenderer

pub const basis_zig_TireTrackRenderer_clear_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_TireTrackRenderer_registerTire_cb = *const fn (u64, f32, c_int, u32) callconv(.c) u32;
pub const basis_zig_TireTrackRenderer_unregisterTire_cb = *const fn (u64, u32) callconv(.c) void;
pub const basis_zig_TireTrackRenderer_beginTireTrack_cb = *const fn (u64, u32) callconv(.c) void;
pub const basis_zig_TireTrackRenderer_endTireTrack_cb = *const fn (u64, u32) callconv(.c) void;
pub const basis_zig_TireTrackRenderer_updateTireTrack_cb = *const fn (u64, u32, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropVec3, f32, f32, [*c]const basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_TireTrackRenderer_beginStaticTireTrack_cb = *const fn (u64, f32, c_int, u32) callconv(.c) u32;
pub const basis_zig_TireTrackRenderer_addPointToStaticTireTrack_cb = *const fn (u64, u32, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropVec3, f32, f32, [*c]const basis.bindings.InteropVec3, f32) callconv(.c) void;
pub const basis_zig_TireTrackRenderer_endStaticTireTrack_cb = *const fn (u64, u32) callconv(.c) void;
pub const basis_zig_TireTrackRenderer_removeStaticTireTrack_cb = *const fn (u64, u32) callconv(.c) void;

// ===============================

// class MeshGeometry

pub const basis_zig_MeshGeometry_newGeometry_cb = *const fn () callconv(.c) u64;
pub const basis_zig_MeshGeometry_deleteGeometry_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_MeshGeometry_clear_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_MeshGeometry_addLodLevel_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_MeshGeometry_getLodLevel_cb = *const fn (u64, u8) callconv(.c) u64;
pub const basis_zig_MeshGeometry_getLodLevelCount_cb = *const fn (u64) callconv(.c) u8;

// ===============================

// class MeshGeometryLodLevel

pub const basis_zig_MeshGeometryLodLevel_clear_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_MeshGeometryLodLevel_addSubMesh_cb = *const fn (u64, c_int) callconv(.c) u64;
pub const basis_zig_MeshGeometryLodLevel_getSubMesh_cb = *const fn (u64, u8) callconv(.c) u64;
pub const basis_zig_MeshGeometryLodLevel_getSubMeshCount_cb = *const fn (u64) callconv(.c) u8;

// ===============================

// class MeshGeometrySubMesh

pub const basis_zig_MeshGeometrySubMesh_clear_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_MeshGeometrySubMesh_addIndex_cb = *const fn (u64, u16) callconv(.c) void;
pub const basis_zig_MeshGeometrySubMesh_addFace_cb = *const fn (u64, u16, u16, u16) callconv(.c) void;
pub const basis_zig_MeshGeometrySubMesh_addVertex_cb = *const fn (u64, [*c]const u8, u32) callconv(.c) void;
pub const basis_zig_MeshGeometrySubMesh_getVertexFormatType_cb = *const fn (u64) callconv(.c) c_int;
pub const basis_zig_MeshGeometrySubMesh_getVertexCount_cb = *const fn (u64) callconv(.c) u32;
pub const basis_zig_MeshGeometrySubMesh_getIndexCount_cb = *const fn (u64) callconv(.c) u32;

// ===============================

// class Mesh

pub const basis_zig_Mesh_getLodLevelCount_cb = *const fn (u64) callconv(.c) u8;
pub const basis_zig_Mesh_getLodLevel_cb = *const fn (u64, u8) callconv(.c) u64;
pub const basis_zig_Mesh_addRef_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_Mesh_release_cb = *const fn (u64) callconv(.c) void;

// ===============================

// class MeshLodLevel

pub const basis_zig_MeshLodLevel_getSubMeshCount_cb = *const fn (u64) callconv(.c) u8;
pub const basis_zig_MeshLodLevel_setSubMeshCount_cb = *const fn (u64, u8) callconv(.c) void;
pub const basis_zig_MeshLodLevel_getSubMesh_cb = *const fn (u64, u8) callconv(.c) u64;
pub const basis_zig_MeshLodLevel_getBounds_cb = *const fn (u64, [*c]basis.bindings.InteropVec3, [*c]basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_MeshLodLevel_setBounds_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropVec3) callconv(.c) void;

// ===============================

// class MeshSubMesh

pub const basis_zig_MeshSubMesh_getVertexFormatType_cb = *const fn (u64) callconv(.c) c_int;
pub const basis_zig_MeshSubMesh_getVertexCount_cb = *const fn (u64) callconv(.c) u32;
pub const basis_zig_MeshSubMesh_setVertexCount_cb = *const fn (u64, u32) callconv(.c) void;
pub const basis_zig_MeshSubMesh_getIndexCount_cb = *const fn (u64) callconv(.c) u32;
pub const basis_zig_MeshSubMesh_setIndexCount_cb = *const fn (u64, u32) callconv(.c) void;
pub const basis_zig_MeshSubMesh_getVertices_cb = *const fn (u64, [*c]u32) callconv(.c) [*c]u8;
pub const basis_zig_MeshSubMesh_getIndices_cb = *const fn (u64, [*c]u32) callconv(.c) [*c]u16;

// ===============================

// class Material

pub const basis_zig_Material_addRef_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_Material_release_cb = *const fn (u64) callconv(.c) void;

// ===============================

// class MeshInstance

pub const basis_zig_MeshInstance_setVisible_cb = *const fn (u64, c_int) callconv(.c) void;
pub const basis_zig_MeshInstance_isVisible_cb = *const fn (u64) callconv(.c) c_int;
pub const basis_zig_MeshInstance_getMaterial_cb = *const fn (u64, u32) callconv(.c) u64;
pub const basis_zig_MeshInstance_setMaterial_cb = *const fn (u64, u64, u32) callconv(.c) void;
pub const basis_zig_MeshInstance_getFlags_cb = *const fn (u64) callconv(.c) c_int;
pub const basis_zig_MeshInstance_isFlagSet_cb = *const fn (u64, c_int) callconv(.c) c_int;
pub const basis_zig_MeshInstance_setFlagValue_cb = *const fn (u64, c_int, c_int) callconv(.c) void;
pub const basis_zig_MeshInstance_updateLightProbeData_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_MeshInstance_getParentSceneNode_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_MeshInstance_setCullDistanceMultiplier_cb = *const fn (u64, f32) callconv(.c) void;
pub const basis_zig_MeshInstance_getCullDistanceMultiplier_cb = *const fn (u64) callconv(.c) f32;

// ===============================

// class Camera

pub const basis_zig_Camera_setPerspective_cb = *const fn (u64, f32, f32, f32, f32) callconv(.c) void;
pub const basis_zig_Camera_setOrthographic_cb = *const fn (u64, f32, f32, f32, f32) callconv(.c) void;
pub const basis_zig_Camera_getWorldPosition_cb = *const fn (u64, [*c]basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_Camera_getForwardDirection_cb = *const fn (u64, [*c]basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_Camera_getFovY_cb = *const fn (u64) callconv(.c) f32;
pub const basis_zig_Camera_getFovX_cb = *const fn (u64) callconv(.c) f32;
pub const basis_zig_Camera_getNearClip_cb = *const fn (u64) callconv(.c) f32;
pub const basis_zig_Camera_getFarClip_cb = *const fn (u64) callconv(.c) f32;
pub const basis_zig_Camera_getPickRay_cb = *const fn (u64, c_int, c_int, c_int, [*c]basis.bindings.InteropVec3, [*c]basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_Camera_worldToScreen_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, [*c]f32, [*c]f32) callconv(.c) c_int;
pub const basis_zig_Camera_worldToScreenUnbounded_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, [*c]f32, [*c]f32) callconv(.c) void;
pub const basis_zig_Camera_getViewMatrix_cb = *const fn (u64, [*c]basis.bindings.InteropMat43) callconv(.c) void;
pub const basis_zig_Camera_getProjectionMatrix_cb = *const fn (u64, [*c]basis.bindings.InteropMat4) callconv(.c) void;
pub const basis_zig_Camera_getParentSceneNode_cb = *const fn (u64) callconv(.c) u64;

// ===============================

// class DisplacementEffectRenderer

pub const basis_zig_DisplacementEffectRenderer_createShockwaveEffect_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, f32, f32) callconv(.c) u32;
pub const basis_zig_DisplacementEffectRenderer_createForceFieldEffect_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, f32, f32) callconv(.c) u32;
pub const basis_zig_DisplacementEffectRenderer_createGravityCraneEffect_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, f32, f32) callconv(.c) u32;
pub const basis_zig_DisplacementEffectRenderer_setEffectCutoffDistance_cb = *const fn (u64, u32, f32) callconv(.c) void;
pub const basis_zig_DisplacementEffectRenderer_setEffectPosition_cb = *const fn (u64, u32, [*c]const basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_DisplacementEffectRenderer_setEffectStrength_cb = *const fn (u64, u32, f32) callconv(.c) void;
pub const basis_zig_DisplacementEffectRenderer_stopEffect_cb = *const fn (u64, u32) callconv(.c) void;
pub const basis_zig_DisplacementEffectRenderer_killEffect_cb = *const fn (u64, u32) callconv(.c) void;
pub const basis_zig_DisplacementEffectRenderer_killAllEffects_cb = *const fn (u64) callconv(.c) void;

// ===============================

// class GameSession

pub const basis_zig_GameSession_getSessionType_cb = *const fn (u64) callconv(.c) i32;
pub const basis_zig_GameSession_getClientCount_cb = *const fn (u64) callconv(.c) u32;
pub const basis_zig_GameSession_getClient_cb = *const fn (u64, u32, [*c]basis.bindings.InteropClientProxy) callconv(.c) void;
pub const basis_zig_GameSession_isPaused_cb = *const fn (u64) callconv(.c) i32;
pub const basis_zig_GameSession_requestPause_cb = *const fn (u64, i32) callconv(.c) void;
pub const basis_zig_GameSession_getTickLevel_cb = *const fn (u64) callconv(.c) u32;
pub const basis_zig_GameSession_setTickLevel_cb = *const fn (u64, u32) callconv(.c) void;
pub const basis_zig_GameSession_requestSetTickLevel_cb = *const fn (u64, u32) callconv(.c) void;
pub const basis_zig_GameSession_hasStarted_cb = *const fn (u64) callconv(.c) i32;
pub const basis_zig_GameSession_hasEnded_cb = *const fn (u64) callconv(.c) i32;
pub const basis_zig_GameSession_getLevelData_cb = *const fn (u64) callconv(.c) u64;
pub const basis_zig_GameSession_isContinuousSession_cb = *const fn (u64) callconv(.c) i32;

// ===============================

// class GameState

pub const basis_zig_GameState_getGameObject_cb = *const fn (u64, u32) callconv(.c) u64;
pub const basis_zig_GameState_getGameObjectFromRenderable_cb = *const fn (u64, u64) callconv(.c) u64;
pub const basis_zig_GameState_createGameObject_cb = *const fn (u64, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, c_int) callconv(.c) void;
pub const basis_zig_GameState_createGameObjectWithStartTransform_cb = *const fn (u64, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion, c_int) callconv(.c) void;
pub const basis_zig_GameState_createGameObjectWithSpawnPointIndex_cb = *const fn (u64, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, u32, c_int) callconv(.c) void;
pub const basis_zig_GameState_createGameObjectWithSpawnPointName_cb = *const fn (u64, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, c_int) callconv(.c) void;
pub const basis_zig_GameState_createGameObjectWithParameters_cb = *const fn (u64, u64, c_int) callconv(.c) void;
pub const basis_zig_GameState_destroyGameObject_cb = *const fn (u64, u32, c_int, c_int) callconv(.c) void;
pub const basis_zig_GameState_hasGameObject_cb = *const fn (u64, u32) callconv(.c) c_int;
pub const basis_zig_GameState_setAvatarObject_cb = *const fn (u64, u32, i32) callconv(.c) void;
pub const basis_zig_GameState_clearAvatarObject_cb = *const fn (u64, i32) callconv(.c) void;
pub const basis_zig_GameState_getAvatarObjectByHostID_cb = *const fn (u64, c_int) callconv(.c) u32;
pub const basis_zig_GameState_getHostIDByAvatarObject_cb = *const fn (u64, u32) callconv(.c) c_int;
pub const basis_zig_GameState_broadcastScriptMessage_cb = *const fn (u64, u64, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_GameState_sendScriptMessageToGameObject_cb = *const fn (u64, u64, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_GameState_generateGameObjectName_cb = *const fn (u64, [*c]const basis.bindings.InteropString, c_int, [*c]basis.bindings.InteropString) callconv(.c) void;

// ===============================

// class LevelData

pub const basis_zig_LevelData_getDataBlockManager_cb = *const fn (u64) callconv(.c) u64;

// ===============================

// class LevelDataBlockManager

pub const basis_zig_LevelDataBlockManager_getDataBlock_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) u64;
pub const basis_zig_LevelDataBlockManager_addDataBlock_cb = *const fn (u64, [*c]const basis.bindings.InteropString, u32) callconv(.c) u64;
pub const basis_zig_LevelDataBlockManager_addDataBlockIfDoesNotExist_cb = *const fn (u64, [*c]const basis.bindings.InteropString, u32) callconv(.c) u64;
pub const basis_zig_LevelDataBlockManager_getMutableDataBlock_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) u64;
pub const basis_zig_LevelDataBlockManager_hasDataBlock_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) c_int;

// ===============================

// class LevelDataBlock

pub const basis_zig_LevelDataBlock_getReadBuffer_cb = *const fn (u64, [*c]u32) callconv(.c) [*c]const u8;
pub const basis_zig_LevelDataBlock_getChunkStartReadBufferPosition_cb = *const fn (u64, u32) callconv(.c) u32;
pub const basis_zig_LevelDataBlock_setReadBufferPosition_cb = *const fn (u64, u32) callconv(.c) void;
pub const basis_zig_LevelDataBlock_getWriteBuffer_cb = *const fn (u64, [*c]u32) callconv(.c) [*c]u8;
pub const basis_zig_LevelDataBlock_beginWritingChunk_cb = *const fn (u64) callconv(.c) u32;
pub const basis_zig_LevelDataBlock_finishWritingChunk_cb = *const fn (u64, u32) callconv(.c) void;
pub const basis_zig_LevelDataBlock_getChunkCount_cb = *const fn (u64) callconv(.c) u32;

// ===============================

// class NavMeshRuntime

pub const basis_zig_NavMeshRuntime_hasNavMesh_cb = *const fn (u32) callconv(.c) c_int;
pub const basis_zig_NavMeshRuntime_findPath_cb = *const fn (u32, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropNavMeshQueryFilter, [*c]basis.bindings.InteropVec3, u32, [*c]u32, f32, [*c]const u32, u32) callconv(.c) i32;
pub const basis_zig_NavMeshRuntime_findClosestPointOnNavMesh_cb = *const fn (u32, [*c]const basis.bindings.InteropVec3, [*c]basis.bindings.InteropVec3, f32) callconv(.c) i32;
pub const basis_zig_NavMeshRuntime_findRandomPointAroundCircle_cb = *const fn (u32, [*c]const basis.bindings.InteropVec3, f32, [*c]basis.bindings.InteropVec3, f32) callconv(.c) i32;
pub const basis_zig_NavMeshRuntime_overlapsNavMesh_cb = *const fn (u32, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropNavMeshQueryFilter, [*c]const basis.bindings.InteropVec3) callconv(.c) c_int;
pub const basis_zig_NavMeshRuntime_addObstacle_cb = *const fn (u32, f32, u32, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropVec3) callconv(.c) u32;
pub const basis_zig_NavMeshRuntime_updateObstacle_cb = *const fn (u32, u32, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_NavMeshRuntime_removeObstacle_cb = *const fn (u32, u32) callconv(.c) void;

// ===============================

// class StreamingUtils

pub const basis_zig_StreamingUtils_setStreamingPosition_cb = *const fn ([*c]const basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_StreamingUtils_getStreamingPosition_cb = *const fn ([*c]basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_StreamingUtils_setStreamingPositionUpdateMode_cb = *const fn (c_int) callconv(.c) void;
pub const basis_zig_StreamingUtils_getStreamingPositionUpdateMode_cb = *const fn () callconv(.c) c_int;

// ===============================

// class ScreenFade

pub const basis_zig_ScreenFade_isActive_cb = *const fn () callconv(.c) c_int;
pub const basis_zig_ScreenFade_fade_cb = *const fn ([*c]const basis.bindings.InteropColor, [*c]const basis.bindings.InteropColor, f32) callconv(.c) void;
pub const basis_zig_ScreenFade_fadeWithCallback_cb = *const fn ([*c]const basis.bindings.InteropColor, [*c]const basis.bindings.InteropColor, f32, basis.bindings.FP_void) callconv(.c) void;
pub const basis_zig_ScreenFade_setColor_cb = *const fn ([*c]const basis.bindings.InteropColor) callconv(.c) void;
pub const basis_zig_ScreenFade_clear_cb = *const fn () callconv(.c) void;

// ===============================

// class StateMachine

pub const basis_zig_StateMachine_registerFlowState_cb = *const fn (basis.bindings.InteropTypedPtr, u64, [*c]const basis.bindings.InteropString, u64, c_int, [*c]basis.bindings.InteropTypedPtr) callconv(.c) void;
pub const basis_zig_StateMachine_setCallbacksForGroup_cb = *const fn (u64, [*c]const basis.bindings.InteropString, basis.bindings.FP_void, basis.bindings.FP_void) callconv(.c) void;
pub const basis_zig_StateMachine_clearCallbacksForGroup_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) void;

// ===============================

// class FlowState

pub const basis_zig_FlowState_startTransition_cb = *const fn (basis.bindings.InteropTypedPtr, [*c]const u8, u32) callconv(.c) void;
pub const basis_zig_FlowState_subscribeToMessageCategory_cb = *const fn (basis.bindings.InteropTypedPtr, i32) callconv(.c) void;
pub const basis_zig_FlowState_allocMsgParams_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) u64;
pub const basis_zig_FlowState_sendMessage_cb = *const fn (basis.bindings.InteropTypedPtr, i32, u64) callconv(.c) void;
pub const basis_zig_FlowState_getClient_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) u64;
pub const basis_zig_FlowState_getServer_cb = *const fn (basis.bindings.InteropTypedPtr) callconv(.c) u64;

// ===============================

// class DebugOverlay

pub const basis_zig_DebugOverlay_isVisible_cb = *const fn () callconv(.c) c_int;
pub const basis_zig_DebugOverlay_setImGuiMenuBarCallbackEnabled_cb = *const fn (basis.bindings.InteropTypedPtr, c_int) callconv(.c) void;
pub const basis_zig_DebugOverlay_setImGuiCallbackEnabled_cb = *const fn (basis.bindings.InteropTypedPtr, c_int) callconv(.c) void;
pub const basis_zig_DebugOverlay_debugTrace_cb = *const fn ([*c]const u8, u32) callconv(.c) void;
pub const basis_zig_DebugOverlay_debugWarning_cb = *const fn ([*c]const u8, u32) callconv(.c) void;
pub const basis_zig_DebugOverlay_areDebugObjectWindowKeysPressed_cb = *const fn () callconv(.c) c_int;
pub const basis_zig_DebugOverlay_showDebugActionAtPosition_cb = *const fn ([*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropVec3) callconv(.c) void;
pub const basis_zig_DebugOverlay_addDebugSpawnableObjectType_cb = *const fn ([*c]const basis.bindings.InteropString, f32) callconv(.c) void;

// ===============================

// class Editor

pub const basis_zig_Editor_printInfo_cb = *const fn ([*c]const u8, u32) callconv(.c) void;
pub const basis_zig_Editor_printWarning_cb = *const fn ([*c]const u8, u32) callconv(.c) void;
pub const basis_zig_Editor_printError_cb = *const fn ([*c]const u8, u32) callconv(.c) void;
pub const basis_zig_Editor_getEditorCamera_cb = *const fn () callconv(.c) u64;

// ===============================

// class ImGui

pub const basis_zig_ImGui_begin_cb = *const fn ([*c]const basis.bindings.InteropString, c_int) callconv(.c) c_int;
pub const basis_zig_ImGui_beginEx_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]bool, c_int) callconv(.c) c_int;
pub const basis_zig_ImGui_end_cb = *const fn () callconv(.c) void;
pub const basis_zig_ImGui_beginMenu_cb = *const fn ([*c]const basis.bindings.InteropString, c_int) callconv(.c) c_int;
pub const basis_zig_ImGui_endMenu_cb = *const fn () callconv(.c) void;
pub const basis_zig_ImGui_menuItem_cb = *const fn ([*c]const basis.bindings.InteropString, c_int, c_int) callconv(.c) c_int;
pub const basis_zig_ImGui_openPopup_cb = *const fn ([*c]const basis.bindings.InteropString, i32) callconv(.c) void;
pub const basis_zig_ImGui_beginPopup_cb = *const fn ([*c]const basis.bindings.InteropString, i32) callconv(.c) c_int;
pub const basis_zig_ImGui_endPopup_cb = *const fn () callconv(.c) void;
pub const basis_zig_ImGui_beginPopupModal_cb = *const fn ([*c]const basis.bindings.InteropString, c_int) callconv(.c) c_int;
pub const basis_zig_ImGui_closeCurrentPopup_cb = *const fn () callconv(.c) void;
pub const basis_zig_ImGui_setItemDefaultFocus_cb = *const fn () callconv(.c) void;
pub const basis_zig_ImGui_dummy_cb = *const fn ([*c]const basis.bindings.InteropVec2) callconv(.c) void;
pub const basis_zig_ImGui_getMainViewportCenter_cb = *const fn ([*c]basis.bindings.InteropVec2) callconv(.c) void;
pub const basis_zig_ImGui_pushStyleColor_cb = *const fn (i32, [*c]const basis.bindings.InteropColor) callconv(.c) void;
pub const basis_zig_ImGui_popStyleColor_cb = *const fn (c_int) callconv(.c) void;
pub const basis_zig_ImGui_separator_cb = *const fn () callconv(.c) void;
pub const basis_zig_ImGui_text_cb = *const fn ([*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_ImGui_textColored_cb = *const fn ([*c]const basis.bindings.InteropColor, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_ImGui_sameline_cb = *const fn (f32, f32) callconv(.c) void;
pub const basis_zig_ImGui_collapsingHeader_cb = *const fn ([*c]const basis.bindings.InteropString, i32) callconv(.c) c_int;
pub const basis_zig_ImGui_button_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropVec2) callconv(.c) c_int;
pub const basis_zig_ImGui_isItemHovered_cb = *const fn (i32) callconv(.c) c_int;
pub const basis_zig_ImGui_setTooltip_cb = *const fn ([*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_ImGui_endTooltip_cb = *const fn () callconv(.c) void;
pub const basis_zig_ImGui_setNextWindowPos_cb = *const fn ([*c]const basis.bindings.InteropVec2, i32, [*c]const basis.bindings.InteropVec2) callconv(.c) void;
pub const basis_zig_ImGui_setNextWindowSize_cb = *const fn ([*c]const basis.bindings.InteropVec2, i32) callconv(.c) void;
pub const basis_zig_ImGui_setNextWindowBgAlpha_cb = *const fn (f32) callconv(.c) void;
pub const basis_zig_ImGui_beginListBox_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropVec2) callconv(.c) c_int;
pub const basis_zig_ImGui_endListBox_cb = *const fn () callconv(.c) void;
pub const basis_zig_ImGui_radioButton_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]c_int, c_int) callconv(.c) c_int;
pub const basis_zig_ImGui_getScrollX_cb = *const fn () callconv(.c) f32;
pub const basis_zig_ImGui_getScrollY_cb = *const fn () callconv(.c) f32;
pub const basis_zig_ImGui_setScrollX_cb = *const fn (f32) callconv(.c) void;
pub const basis_zig_ImGui_setScrollY_cb = *const fn (f32) callconv(.c) void;
pub const basis_zig_ImGui_getScrollMaxX_cb = *const fn () callconv(.c) f32;
pub const basis_zig_ImGui_getScrollMaxY_cb = *const fn () callconv(.c) f32;
pub const basis_zig_ImGui_setScrollHereX_cb = *const fn (f32) callconv(.c) void;
pub const basis_zig_ImGui_setScrollHereY_cb = *const fn (f32) callconv(.c) void;
pub const basis_zig_ImGui_setScrollFromPosX_cb = *const fn (f32, f32) callconv(.c) void;
pub const basis_zig_ImGui_setScrollFromPosY_cb = *const fn (f32, f32) callconv(.c) void;
pub const basis_zig_ImGui_dragFloat_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]f32, f32, f32, f32, [*c]const basis.bindings.InteropString, c_int) callconv(.c) c_int;
pub const basis_zig_ImGui_dragInt_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]c_int, f32, c_int, c_int, [*c]const basis.bindings.InteropString, c_int) callconv(.c) c_int;
pub const basis_zig_ImGui_sliderFloat_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]f32, f32, f32, [*c]const basis.bindings.InteropString, c_int) callconv(.c) c_int;
pub const basis_zig_ImGui_sliderInt_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]c_int, c_int, c_int, [*c]const basis.bindings.InteropString, c_int) callconv(.c) c_int;
pub const basis_zig_ImGui_plotMultiLines_cb = *const fn ([*c]const u8, u32, basis.bindings.ImguiPlotMultiLinesGetter) callconv(.c) void;
pub const basis_zig_ImGui_getContentRegionAvail_cb = *const fn ([*c]basis.bindings.InteropVec2) callconv(.c) void;
pub const basis_zig_ImGui_pushID_cb = *const fn (c_int) callconv(.c) void;
pub const basis_zig_ImGui_pushIDPtr_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_ImGui_popID_cb = *const fn () callconv(.c) void;

// ===============================

// class ImPlot

pub const basis_zig_ImPlot_beginPlot_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropVec2, c_int) callconv(.c) c_int;
pub const basis_zig_ImPlot_endPlot_cb = *const fn () callconv(.c) void;
pub const basis_zig_ImPlot_setupAxis_cb = *const fn (c_int, [*c]const basis.bindings.InteropString, c_int) callconv(.c) void;
pub const basis_zig_ImPlot_setupAxisLimits_cb = *const fn (c_int, f32, f32, c_int) callconv(.c) void;
pub const basis_zig_ImPlot_setupLegend_cb = *const fn (c_int, c_int) callconv(.c) void;
pub const basis_zig_ImPlot_plotLine_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]const f32, [*c]const f32, c_int) callconv(.c) void;
pub const basis_zig_ImPlot_plotLineEx_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]const f32, [*c]const f32, c_int, [*c]const u8, u32) callconv(.c) void;
pub const basis_zig_ImPlot_plotScatter_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]const f32, [*c]const f32, c_int) callconv(.c) void;
pub const basis_zig_ImPlot_plotScatterEx_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]const f32, [*c]const f32, c_int, [*c]const u8, u32) callconv(.c) void;
pub const basis_zig_ImPlot_dragPoint_cb = *const fn (c_int, [*c]f64, [*c]f64, [*c]const basis.bindings.InteropColor, f32, c_int, [*c]bool, [*c]bool, [*c]bool) callconv(.c) c_int;

// ===============================

// class GameObjectCreationParameters

pub const basis_zig_GameObjectCreationParameters_newParams_cb = *const fn () callconv(.c) u64;
pub const basis_zig_GameObjectCreationParameters_newParamsWithNameAndType_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString) callconv(.c) u64;
pub const basis_zig_GameObjectCreationParameters_deleteParams_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_GameObjectCreationParameters_setStartTransform_cb = *const fn (u64, [*c]const basis.bindings.InteropVec3, [*c]const basis.bindings.InteropQuaternion) callconv(.c) void;
pub const basis_zig_GameObjectCreationParameters_setPropertyBundlePath_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) void;

// ===============================

// class OSUtility

pub const basis_zig_OSUtility_writeStringToClipboard_cb = *const fn ([*c]const basis.bindings.InteropString) callconv(.c) c_int;
pub const basis_zig_OSUtility_readStringFromClipboard_cb = *const fn ([*c]basis.bindings.InteropString) callconv(.c) c_int;

// ===============================

// class ExposedPropertyLayoutReader

pub const basis_zig_ExposedPropertyLayoutReader_init_cb = *const fn (u64, i32) callconv(.c) void;
pub const basis_zig_ExposedPropertyLayoutReader_processProperty_cb = *const fn (u64, [*c]const basis.bindings.InteropString, i32, [*c]const u8, u32, i32, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_ExposedPropertyLayoutReader_processString_cb = *const fn (u64, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, i32, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_ExposedPropertyLayoutReader_processResourceRef_cb = *const fn (u64, [*c]const basis.bindings.InteropString, i32, [*c]const basis.bindings.InteropString, i32, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_ExposedPropertyLayoutReader_processButton_cb = *const fn (u64, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_ExposedPropertyLayoutReader_processCategory_cb = *const fn (u64, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_ExposedPropertyLayoutReader_processEnum_cb = *const fn (u64, [*c]const basis.bindings.InteropString, u32, [*c]const basis.bindings.InteropString, [*c]const u32, u32, c_int, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_ExposedPropertyLayoutReader_allPropertiesProcessed_cb = *const fn (u64) callconv(.c) void;

// ===============================

// class ZigAngelScriptTypeRegistration

pub const basis_zig_ZigAngelScriptTypeRegistration_registerEnumType_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_ZigAngelScriptTypeRegistration_registerEnumValue_cb = *const fn (u64, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, c_int) callconv(.c) void;

// ===============================

// class ZigAngelScriptComponentRegistration

pub const basis_zig_ZigAngelScriptComponentRegistration_registerComponentType_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_ZigAngelScriptComponentRegistration_registerComponentMethod_cb = *const fn (u64, [*c]const basis.bindings.InteropString, u64) callconv(.c) void;
pub const basis_zig_ZigAngelScriptComponentRegistration_registerComponentEventAutoComplete_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) void;

// ===============================

// class AngelScriptUtils

pub const basis_zig_AngelScriptUtils_getStringRefConstIn_cb = *const fn (u64, [*c]basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_AngelScriptUtils_setStringRefOut_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_AngelScriptUtils_getGameObjectRefConstIn_cb = *const fn (u64, [*c]basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_AngelScriptUtils_getHashFromGameObjectRefConstIn_cb = *const fn (u64) callconv(.c) u32;
pub const basis_zig_AngelScriptUtils_setGameObjectRefOut_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_AngelScriptUtils_getColorRefConstIn_cb = *const fn (u64, [*c]basis.bindings.InteropColor) callconv(.c) void;
pub const basis_zig_AngelScriptUtils_setColorRefOut_cb = *const fn (u64, [*c]const basis.bindings.InteropColor) callconv(.c) void;
pub const basis_zig_AngelScriptUtils_addRefToASFuncPtr_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_AngelScriptUtils_releaseASFuncPtr_cb = *const fn (u64) callconv(.c) void;

// ===============================

