// ----------------------------------------------------
// Copyright (c) 2018-2026 Madrigal Ltd.
// This file is part of the Basis modding SDK, and is subject to the
// terms and conditions of the Basis modding SDK License Agreement.
// https://www.madrigalgames.com
// ----------------------------------------------------

// This file was generated by Sir Bindalot, the binding generator. Ne pas toucher!

const basis = @import("../basis.zig");

// class Core

pub var _Core_showAssertDialog: basis.bindings.generated_types.basis_zig_Core_showAssertDialog_cb = undefined;
pub var _Core_heapAlloc: basis.bindings.generated_types.basis_zig_Core_heapAlloc_cb = undefined;
pub var _Core_heapFree: basis.bindings.generated_types.basis_zig_Core_heapFree_cb = undefined;
pub var _Core_printOnHost: basis.bindings.generated_types.basis_zig_Core_printOnHost_cb = undefined;
pub var _Core_beginProfilingSample: basis.bindings.generated_types.basis_zig_Core_beginProfilingSample_cb = undefined;
pub var _Core_endProfilingSample: basis.bindings.generated_types.basis_zig_Core_endProfilingSample_cb = undefined;
pub var _Core_getRandomSeed: basis.bindings.generated_types.basis_zig_Core_getRandomSeed_cb = undefined;

// ===============================

// class App

pub var _App_createApp: basis.bindings.generated_types.basis_zig_App_createApp_cb = undefined;
pub var _App_getAppMode: basis.bindings.generated_types.basis_zig_App_getAppMode_cb = undefined;
pub var _App_getClient: basis.bindings.generated_types.basis_zig_App_getClient_cb = undefined;
pub var _App_getServer: basis.bindings.generated_types.basis_zig_App_getServer_cb = undefined;
pub var _App_addInput: basis.bindings.generated_types.basis_zig_App_addInput_cb = undefined;
pub var _App_getInputBufferSize: basis.bindings.generated_types.basis_zig_App_getInputBufferSize_cb = undefined;
pub var _App_clearInputMappings: basis.bindings.generated_types.basis_zig_App_clearInputMappings_cb = undefined;
pub var _App_mapInput: basis.bindings.generated_types.basis_zig_App_mapInput_cb = undefined;
pub var _App_mapKeyboardInput: basis.bindings.generated_types.basis_zig_App_mapKeyboardInput_cb = undefined;
pub var _App_mapMouseButtonInput: basis.bindings.generated_types.basis_zig_App_mapMouseButtonInput_cb = undefined;
pub var _App_mapGamepadButtonInput: basis.bindings.generated_types.basis_zig_App_mapGamepadButtonInput_cb = undefined;
pub var _App_registerMessage: basis.bindings.generated_types.basis_zig_App_registerMessage_cb = undefined;
pub var _App_getClientGameFlowStateMachine: basis.bindings.generated_types.basis_zig_App_getClientGameFlowStateMachine_cb = undefined;
pub var _App_getServerGameFlowStateMachine: basis.bindings.generated_types.basis_zig_App_getServerGameFlowStateMachine_cb = undefined;
pub var _App_createAndLoadSPGame: basis.bindings.generated_types.basis_zig_App_createAndLoadSPGame_cb = undefined;
pub var _App_createSPGame: basis.bindings.generated_types.basis_zig_App_createSPGame_cb = undefined;
pub var _App_loadSPGame: basis.bindings.generated_types.basis_zig_App_loadSPGame_cb = undefined;
pub var _App_leaveGame: basis.bindings.generated_types.basis_zig_App_leaveGame_cb = undefined;
pub var _App_isLocalServerRunning: basis.bindings.generated_types.basis_zig_App_isLocalServerRunning_cb = undefined;
pub var _App_isServerThreadRunning: basis.bindings.generated_types.basis_zig_App_isServerThreadRunning_cb = undefined;
pub var _App_hasCommandLineParameter: basis.bindings.generated_types.basis_zig_App_hasCommandLineParameter_cb = undefined;
pub var _App_getCommandLineParameter: basis.bindings.generated_types.basis_zig_App_getCommandLineParameter_cb = undefined;
pub var _App_getConfigOptions: basis.bindings.generated_types.basis_zig_App_getConfigOptions_cb = undefined;

// ===============================

// class ModController

pub var _ModController_createModController: basis.bindings.generated_types.basis_zig_ModController_createModController_cb = undefined;
pub var _ModController_getAppMode: basis.bindings.generated_types.basis_zig_ModController_getAppMode_cb = undefined;
pub var _ModController_getClient: basis.bindings.generated_types.basis_zig_ModController_getClient_cb = undefined;
pub var _ModController_getServer: basis.bindings.generated_types.basis_zig_ModController_getServer_cb = undefined;
pub var _ModController_registerMessage: basis.bindings.generated_types.basis_zig_ModController_registerMessage_cb = undefined;

// ===============================

// class Client

pub var _Client_getHostID: basis.bindings.generated_types.basis_zig_Client_getHostID_cb = undefined;
pub var _Client_getRenderer: basis.bindings.generated_types.basis_zig_Client_getRenderer_cb = undefined;
pub var _Client_getGameSession: basis.bindings.generated_types.basis_zig_Client_getGameSession_cb = undefined;
pub var _Client_getGameState: basis.bindings.generated_types.basis_zig_Client_getGameState_cb = undefined;
pub var _Client_getPhysicsEnginePtr: basis.bindings.generated_types.basis_zig_Client_getPhysicsEnginePtr_cb = undefined;
pub var _Client_getPrimaryPhysicsScene: basis.bindings.generated_types.basis_zig_Client_getPrimaryPhysicsScene_cb = undefined;
pub var _Client_getInterpolationFactor: basis.bindings.generated_types.basis_zig_Client_getInterpolationFactor_cb = undefined;
pub var _Client_createMessageNode: basis.bindings.generated_types.basis_zig_Client_createMessageNode_cb = undefined;
pub var _Client_addRPCListener: basis.bindings.generated_types.basis_zig_Client_addRPCListener_cb = undefined;
pub var _Client_removeRPCListener: basis.bindings.generated_types.basis_zig_Client_removeRPCListener_cb = undefined;
pub var _Client_sendNetworkMessageToHostID: basis.bindings.generated_types.basis_zig_Client_sendNetworkMessageToHostID_cb = undefined;
pub var _Client_sendNetworkMessageToPeer: basis.bindings.generated_types.basis_zig_Client_sendNetworkMessageToPeer_cb = undefined;
pub var _Client_isConnected: basis.bindings.generated_types.basis_zig_Client_isConnected_cb = undefined;

// ===============================

// class Server

pub var _Server_getGameSession: basis.bindings.generated_types.basis_zig_Server_getGameSession_cb = undefined;
pub var _Server_getGameState: basis.bindings.generated_types.basis_zig_Server_getGameState_cb = undefined;
pub var _Server_getPhysicsEnginePtr: basis.bindings.generated_types.basis_zig_Server_getPhysicsEnginePtr_cb = undefined;
pub var _Server_getPrimaryPhysicsScene: basis.bindings.generated_types.basis_zig_Server_getPrimaryPhysicsScene_cb = undefined;
pub var _Server_createMessageNode: basis.bindings.generated_types.basis_zig_Server_createMessageNode_cb = undefined;
pub var _Server_addRPCListener: basis.bindings.generated_types.basis_zig_Server_addRPCListener_cb = undefined;
pub var _Server_removeRPCListener: basis.bindings.generated_types.basis_zig_Server_removeRPCListener_cb = undefined;
pub var _Server_sendNetworkMessageToHostID: basis.bindings.generated_types.basis_zig_Server_sendNetworkMessageToHostID_cb = undefined;
pub var _Server_sendNetworkMessageToPeer: basis.bindings.generated_types.basis_zig_Server_sendNetworkMessageToPeer_cb = undefined;
pub var _Server_endGameSession: basis.bindings.generated_types.basis_zig_Server_endGameSession_cb = undefined;

// ===============================

// class CommandPrompt

pub var _CommandPrompt_parseCommand: basis.bindings.generated_types.basis_zig_CommandPrompt_parseCommand_cb = undefined;
pub var _CommandPrompt_registerIntValue: basis.bindings.generated_types.basis_zig_CommandPrompt_registerIntValue_cb = undefined;
pub var _CommandPrompt_registerFloatValue: basis.bindings.generated_types.basis_zig_CommandPrompt_registerFloatValue_cb = undefined;
pub var _CommandPrompt_registerBoolValue: basis.bindings.generated_types.basis_zig_CommandPrompt_registerBoolValue_cb = undefined;
pub var _CommandPrompt_registerFunction: basis.bindings.generated_types.basis_zig_CommandPrompt_registerFunction_cb = undefined;
pub var _CommandPrompt_unregister: basis.bindings.generated_types.basis_zig_CommandPrompt_unregister_cb = undefined;
pub var _CommandPrompt_outputLine: basis.bindings.generated_types.basis_zig_CommandPrompt_outputLine_cb = undefined;
pub var _CommandPrompt_outputErrorLine: basis.bindings.generated_types.basis_zig_CommandPrompt_outputErrorLine_cb = undefined;
pub var _CommandPrompt_getIntParameter: basis.bindings.generated_types.basis_zig_CommandPrompt_getIntParameter_cb = undefined;
pub var _CommandPrompt_getFloatParameter: basis.bindings.generated_types.basis_zig_CommandPrompt_getFloatParameter_cb = undefined;
pub var _CommandPrompt_getBoolParameter: basis.bindings.generated_types.basis_zig_CommandPrompt_getBoolParameter_cb = undefined;
pub var _CommandPrompt_getStringParameter: basis.bindings.generated_types.basis_zig_CommandPrompt_getStringParameter_cb = undefined;

// ===============================

// class ConfigOptions

pub var _ConfigOptions_addString: basis.bindings.generated_types.basis_zig_ConfigOptions_addString_cb = undefined;
pub var _ConfigOptions_addFloat: basis.bindings.generated_types.basis_zig_ConfigOptions_addFloat_cb = undefined;
pub var _ConfigOptions_addInteger: basis.bindings.generated_types.basis_zig_ConfigOptions_addInteger_cb = undefined;
pub var _ConfigOptions_addBool: basis.bindings.generated_types.basis_zig_ConfigOptions_addBool_cb = undefined;
pub var _ConfigOptions_getString: basis.bindings.generated_types.basis_zig_ConfigOptions_getString_cb = undefined;
pub var _ConfigOptions_getFloat: basis.bindings.generated_types.basis_zig_ConfigOptions_getFloat_cb = undefined;
pub var _ConfigOptions_getInteger: basis.bindings.generated_types.basis_zig_ConfigOptions_getInteger_cb = undefined;
pub var _ConfigOptions_getBool: basis.bindings.generated_types.basis_zig_ConfigOptions_getBool_cb = undefined;
pub var _ConfigOptions_setString: basis.bindings.generated_types.basis_zig_ConfigOptions_setString_cb = undefined;
pub var _ConfigOptions_setFloat: basis.bindings.generated_types.basis_zig_ConfigOptions_setFloat_cb = undefined;
pub var _ConfigOptions_setInteger: basis.bindings.generated_types.basis_zig_ConfigOptions_setInteger_cb = undefined;
pub var _ConfigOptions_setBool: basis.bindings.generated_types.basis_zig_ConfigOptions_setBool_cb = undefined;
pub var _ConfigOptions_hasString: basis.bindings.generated_types.basis_zig_ConfigOptions_hasString_cb = undefined;
pub var _ConfigOptions_hasFloat: basis.bindings.generated_types.basis_zig_ConfigOptions_hasFloat_cb = undefined;
pub var _ConfigOptions_hasInteger: basis.bindings.generated_types.basis_zig_ConfigOptions_hasInteger_cb = undefined;
pub var _ConfigOptions_hasBool: basis.bindings.generated_types.basis_zig_ConfigOptions_hasBool_cb = undefined;
pub var _ConfigOptions_save: basis.bindings.generated_types.basis_zig_ConfigOptions_save_cb = undefined;

// ===============================

// class PlayerController

pub var _PlayerController_getClient: basis.bindings.generated_types.basis_zig_PlayerController_getClient_cb = undefined;
pub var _PlayerController_getServer: basis.bindings.generated_types.basis_zig_PlayerController_getServer_cb = undefined;
pub var _PlayerController_getInputRange: basis.bindings.generated_types.basis_zig_PlayerController_getInputRange_cb = undefined;
pub var _PlayerController_getInputState: basis.bindings.generated_types.basis_zig_PlayerController_getInputState_cb = undefined;
pub var _PlayerController_getInputAction: basis.bindings.generated_types.basis_zig_PlayerController_getInputAction_cb = undefined;
pub var _PlayerController_subscribeToMessageCategory: basis.bindings.generated_types.basis_zig_PlayerController_subscribeToMessageCategory_cb = undefined;
pub var _PlayerController_allocMsgParams: basis.bindings.generated_types.basis_zig_PlayerController_allocMsgParams_cb = undefined;
pub var _PlayerController_sendMessage: basis.bindings.generated_types.basis_zig_PlayerController_sendMessage_cb = undefined;

// ===============================

// class DebugDraw

pub var _DebugDraw_drawLine2D: basis.bindings.generated_types.basis_zig_DebugDraw_drawLine2D_cb = undefined;
pub var _DebugDraw_drawLine3D: basis.bindings.generated_types.basis_zig_DebugDraw_drawLine3D_cb = undefined;
pub var _DebugDraw_drawAxisCross: basis.bindings.generated_types.basis_zig_DebugDraw_drawAxisCross_cb = undefined;
pub var _DebugDraw_drawSphere: basis.bindings.generated_types.basis_zig_DebugDraw_drawSphere_cb = undefined;
pub var _DebugDraw_drawTriangle3D: basis.bindings.generated_types.basis_zig_DebugDraw_drawTriangle3D_cb = undefined;
pub var _DebugDraw_drawString: basis.bindings.generated_types.basis_zig_DebugDraw_drawString_cb = undefined;
pub var _DebugDraw_drawStringXY: basis.bindings.generated_types.basis_zig_DebugDraw_drawStringXY_cb = undefined;

// ===============================

// class GameObject

pub var _GameObject_getName: basis.bindings.generated_types.basis_zig_GameObject_getName_cb = undefined;
pub var _GameObject_getType: basis.bindings.generated_types.basis_zig_GameObject_getType_cb = undefined;
pub var _GameObject_getComponentPtrByShortName: basis.bindings.generated_types.basis_zig_GameObject_getComponentPtrByShortName_cb = undefined;
pub var _GameObject_getComponentPtrByTypeName: basis.bindings.generated_types.basis_zig_GameObject_getComponentPtrByTypeName_cb = undefined;
pub var _GameObject_addGameObjectMeshInstanceMapping: basis.bindings.generated_types.basis_zig_GameObject_addGameObjectMeshInstanceMapping_cb = undefined;
pub var _GameObject_removeGameObjectMeshInstanceMapping: basis.bindings.generated_types.basis_zig_GameObject_removeGameObjectMeshInstanceMapping_cb = undefined;
pub var _GameObject_getNameHash: basis.bindings.generated_types.basis_zig_GameObject_getNameHash_cb = undefined;
pub var _GameObject_getWorldTransform: basis.bindings.generated_types.basis_zig_GameObject_getWorldTransform_cb = undefined;
pub var _GameObject_setWorldTransform: basis.bindings.generated_types.basis_zig_GameObject_setWorldTransform_cb = undefined;
pub var _GameObject_getMeshComponentData: basis.bindings.generated_types.basis_zig_GameObject_getMeshComponentData_cb = undefined;
pub var _GameObject_getPhysicsActor: basis.bindings.generated_types.basis_zig_GameObject_getPhysicsActor_cb = undefined;
pub var _GameObject_setGameTag: basis.bindings.generated_types.basis_zig_GameObject_setGameTag_cb = undefined;
pub var _GameObject_getGameTag: basis.bindings.generated_types.basis_zig_GameObject_getGameTag_cb = undefined;
pub var _GameObject_getRenderSceneNode: basis.bindings.generated_types.basis_zig_GameObject_getRenderSceneNode_cb = undefined;
pub var _GameObject_getNavMeshObstacleIDs: basis.bindings.generated_types.basis_zig_GameObject_getNavMeshObstacleIDs_cb = undefined;

// ===============================

// class ComponentContext

pub var _ComponentContext_getName: basis.bindings.generated_types.basis_zig_ComponentContext_getName_cb = undefined;
pub var _ComponentContext_onClient: basis.bindings.generated_types.basis_zig_ComponentContext_onClient_cb = undefined;
pub var _ComponentContext_inEditor: basis.bindings.generated_types.basis_zig_ComponentContext_inEditor_cb = undefined;
pub var _ComponentContext_getClient: basis.bindings.generated_types.basis_zig_ComponentContext_getClient_cb = undefined;
pub var _ComponentContext_getServer: basis.bindings.generated_types.basis_zig_ComponentContext_getServer_cb = undefined;
pub var _ComponentContext_getGameObject: basis.bindings.generated_types.basis_zig_ComponentContext_getGameObject_cb = undefined;
pub var _ComponentContext_subscribeToMessageCategory: basis.bindings.generated_types.basis_zig_ComponentContext_subscribeToMessageCategory_cb = undefined;
pub var _ComponentContext_allocMsgParams: basis.bindings.generated_types.basis_zig_ComponentContext_allocMsgParams_cb = undefined;
pub var _ComponentContext_sendMessage: basis.bindings.generated_types.basis_zig_ComponentContext_sendMessage_cb = undefined;
pub var _ComponentContext_getPhysicsEnginePtr: basis.bindings.generated_types.basis_zig_ComponentContext_getPhysicsEnginePtr_cb = undefined;
pub var _ComponentContext_getPrimaryPhysicsScene: basis.bindings.generated_types.basis_zig_ComponentContext_getPrimaryPhysicsScene_cb = undefined;
pub var _ComponentContext_getRenderer: basis.bindings.generated_types.basis_zig_ComponentContext_getRenderer_cb = undefined;
pub var _ComponentContext_getGameSession: basis.bindings.generated_types.basis_zig_ComponentContext_getGameSession_cb = undefined;
pub var _ComponentContext_getGameState: basis.bindings.generated_types.basis_zig_ComponentContext_getGameState_cb = undefined;
pub var _ComponentContext_getPosition: basis.bindings.generated_types.basis_zig_ComponentContext_getPosition_cb = undefined;
pub var _ComponentContext_setPosition: basis.bindings.generated_types.basis_zig_ComponentContext_setPosition_cb = undefined;
pub var _ComponentContext_getOrientation: basis.bindings.generated_types.basis_zig_ComponentContext_getOrientation_cb = undefined;
pub var _ComponentContext_setOrientation: basis.bindings.generated_types.basis_zig_ComponentContext_setOrientation_cb = undefined;
pub var _ComponentContext_getLinearVelocity: basis.bindings.generated_types.basis_zig_ComponentContext_getLinearVelocity_cb = undefined;
pub var _ComponentContext_getAngularVelocity: basis.bindings.generated_types.basis_zig_ComponentContext_getAngularVelocity_cb = undefined;
pub var _ComponentContext_setTransform: basis.bindings.generated_types.basis_zig_ComponentContext_setTransform_cb = undefined;
pub var _ComponentContext_setTransformWithVelocities: basis.bindings.generated_types.basis_zig_ComponentContext_setTransformWithVelocities_cb = undefined;
pub var _ComponentContext_getWorldMatrix: basis.bindings.generated_types.basis_zig_ComponentContext_getWorldMatrix_cb = undefined;
pub var _ComponentContext_getRenderSceneNode: basis.bindings.generated_types.basis_zig_ComponentContext_getRenderSceneNode_cb = undefined;
pub var _ComponentContext_isClientLocalAvatar: basis.bindings.generated_types.basis_zig_ComponentContext_isClientLocalAvatar_cb = undefined;
pub var _ComponentContext_getAvatarHostID: basis.bindings.generated_types.basis_zig_ComponentContext_getAvatarHostID_cb = undefined;
pub var _ComponentContext_getInputRange: basis.bindings.generated_types.basis_zig_ComponentContext_getInputRange_cb = undefined;
pub var _ComponentContext_getInputState: basis.bindings.generated_types.basis_zig_ComponentContext_getInputState_cb = undefined;
pub var _ComponentContext_getInputAction: basis.bindings.generated_types.basis_zig_ComponentContext_getInputAction_cb = undefined;
pub var _ComponentContext_getCharacterController: basis.bindings.generated_types.basis_zig_ComponentContext_getCharacterController_cb = undefined;
pub var _ComponentContext_getPhysicsActor: basis.bindings.generated_types.basis_zig_ComponentContext_getPhysicsActor_cb = undefined;
pub var _ComponentContext_flushExposedProperties: basis.bindings.generated_types.basis_zig_ComponentContext_flushExposedProperties_cb = undefined;
pub var _ComponentContext_getParentGameObject: basis.bindings.generated_types.basis_zig_ComponentContext_getParentGameObject_cb = undefined;
pub var _ComponentContext_registerPipe: basis.bindings.generated_types.basis_zig_ComponentContext_registerPipe_cb = undefined;
pub var _ComponentContext_writeToPipe: basis.bindings.generated_types.basis_zig_ComponentContext_writeToPipe_cb = undefined;
pub var _ComponentContext_callScriptOnTick: basis.bindings.generated_types.basis_zig_ComponentContext_callScriptOnTick_cb = undefined;
pub var _ComponentContext_getScriptFunctionByDecl: basis.bindings.generated_types.basis_zig_ComponentContext_getScriptFunctionByDecl_cb = undefined;
pub var _ComponentContext_getScriptFunctionByASFuncPtr: basis.bindings.generated_types.basis_zig_ComponentContext_getScriptFunctionByASFuncPtr_cb = undefined;
pub var _ComponentContext_setScriptGlobalHandle: basis.bindings.generated_types.basis_zig_ComponentContext_setScriptGlobalHandle_cb = undefined;

// ===============================

// class AngelScriptFunction

pub var _AngelScriptFunction_prepareCall: basis.bindings.generated_types.basis_zig_AngelScriptFunction_prepareCall_cb = undefined;
pub var _AngelScriptFunction_setBoolParam: basis.bindings.generated_types.basis_zig_AngelScriptFunction_setBoolParam_cb = undefined;
pub var _AngelScriptFunction_setIntParam: basis.bindings.generated_types.basis_zig_AngelScriptFunction_setIntParam_cb = undefined;
pub var _AngelScriptFunction_setUintParam: basis.bindings.generated_types.basis_zig_AngelScriptFunction_setUintParam_cb = undefined;
pub var _AngelScriptFunction_setFloatParam: basis.bindings.generated_types.basis_zig_AngelScriptFunction_setFloatParam_cb = undefined;
pub var _AngelScriptFunction_setStringParam: basis.bindings.generated_types.basis_zig_AngelScriptFunction_setStringParam_cb = undefined;
pub var _AngelScriptFunction_setGameObjectRefParam: basis.bindings.generated_types.basis_zig_AngelScriptFunction_setGameObjectRefParam_cb = undefined;
pub var _AngelScriptFunction_getReturnBool: basis.bindings.generated_types.basis_zig_AngelScriptFunction_getReturnBool_cb = undefined;
pub var _AngelScriptFunction_getReturnInt: basis.bindings.generated_types.basis_zig_AngelScriptFunction_getReturnInt_cb = undefined;
pub var _AngelScriptFunction_getReturnUint: basis.bindings.generated_types.basis_zig_AngelScriptFunction_getReturnUint_cb = undefined;
pub var _AngelScriptFunction_getReturnFloat: basis.bindings.generated_types.basis_zig_AngelScriptFunction_getReturnFloat_cb = undefined;
pub var _AngelScriptFunction_executeCall: basis.bindings.generated_types.basis_zig_AngelScriptFunction_executeCall_cb = undefined;

// ===============================

// class MessageParameters

pub var _MessageParameters_addInt: basis.bindings.generated_types.basis_zig_MessageParameters_addInt_cb = undefined;
pub var _MessageParameters_getInt: basis.bindings.generated_types.basis_zig_MessageParameters_getInt_cb = undefined;
pub var _MessageParameters_addUint: basis.bindings.generated_types.basis_zig_MessageParameters_addUint_cb = undefined;
pub var _MessageParameters_getUint: basis.bindings.generated_types.basis_zig_MessageParameters_getUint_cb = undefined;
pub var _MessageParameters_addUint64: basis.bindings.generated_types.basis_zig_MessageParameters_addUint64_cb = undefined;
pub var _MessageParameters_getUint64: basis.bindings.generated_types.basis_zig_MessageParameters_getUint64_cb = undefined;
pub var _MessageParameters_addFloat: basis.bindings.generated_types.basis_zig_MessageParameters_addFloat_cb = undefined;
pub var _MessageParameters_getFloat: basis.bindings.generated_types.basis_zig_MessageParameters_getFloat_cb = undefined;
pub var _MessageParameters_addVec3: basis.bindings.generated_types.basis_zig_MessageParameters_addVec3_cb = undefined;
pub var _MessageParameters_getVec3: basis.bindings.generated_types.basis_zig_MessageParameters_getVec3_cb = undefined;
pub var _MessageParameters_addVec4: basis.bindings.generated_types.basis_zig_MessageParameters_addVec4_cb = undefined;
pub var _MessageParameters_getVec4: basis.bindings.generated_types.basis_zig_MessageParameters_getVec4_cb = undefined;
pub var _MessageParameters_addQuaternion: basis.bindings.generated_types.basis_zig_MessageParameters_addQuaternion_cb = undefined;
pub var _MessageParameters_getQuaternion: basis.bindings.generated_types.basis_zig_MessageParameters_getQuaternion_cb = undefined;
pub var _MessageParameters_addString: basis.bindings.generated_types.basis_zig_MessageParameters_addString_cb = undefined;
pub var _MessageParameters_getString: basis.bindings.generated_types.basis_zig_MessageParameters_getString_cb = undefined;

// ===============================

// class MessageNode

pub var _MessageNode_destroy: basis.bindings.generated_types.basis_zig_MessageNode_destroy_cb = undefined;
pub var _MessageNode_subscribeToMessageCategory: basis.bindings.generated_types.basis_zig_MessageNode_subscribeToMessageCategory_cb = undefined;
pub var _MessageNode_allocMsgParams: basis.bindings.generated_types.basis_zig_MessageNode_allocMsgParams_cb = undefined;
pub var _MessageNode_sendMessage: basis.bindings.generated_types.basis_zig_MessageNode_sendMessage_cb = undefined;

// ===============================

// class InputManager

pub var _InputManager_addGameInputContextToFront: basis.bindings.generated_types.basis_zig_InputManager_addGameInputContextToFront_cb = undefined;
pub var _InputManager_addGameInputContextToBack: basis.bindings.generated_types.basis_zig_InputManager_addGameInputContextToBack_cb = undefined;
pub var _InputManager_isGameInputContextEnabled: basis.bindings.generated_types.basis_zig_InputManager_isGameInputContextEnabled_cb = undefined;
pub var _InputManager_removeGameInputContext: basis.bindings.generated_types.basis_zig_InputManager_removeGameInputContext_cb = undefined;
pub var _InputManager_getNFirstEnabledInputContexts: basis.bindings.generated_types.basis_zig_InputManager_getNFirstEnabledInputContexts_cb = undefined;
pub var _InputManager_isCursorLocked: basis.bindings.generated_types.basis_zig_InputManager_isCursorLocked_cb = undefined;
pub var _InputManager_lockCursor: basis.bindings.generated_types.basis_zig_InputManager_lockCursor_cb = undefined;
pub var _InputManager_releaseCursor: basis.bindings.generated_types.basis_zig_InputManager_releaseCursor_cb = undefined;
pub var _InputManager_getGameInputMode: basis.bindings.generated_types.basis_zig_InputManager_getGameInputMode_cb = undefined;
pub var _InputManager_isKeyPressed: basis.bindings.generated_types.basis_zig_InputManager_isKeyPressed_cb = undefined;
pub var _InputManager_isMouseButtonPressed: basis.bindings.generated_types.basis_zig_InputManager_isMouseButtonPressed_cb = undefined;
pub var _InputManager_isGamepadButtonDown: basis.bindings.generated_types.basis_zig_InputManager_isGamepadButtonDown_cb = undefined;
pub var _InputManager_setGamepadVibration: basis.bindings.generated_types.basis_zig_InputManager_setGamepadVibration_cb = undefined;
pub var _InputManager_getMappedKeyCode: basis.bindings.generated_types.basis_zig_InputManager_getMappedKeyCode_cb = undefined;
pub var _InputManager_getMappedMouseButton: basis.bindings.generated_types.basis_zig_InputManager_getMappedMouseButton_cb = undefined;
pub var _InputManager_getMappedGamepadButton: basis.bindings.generated_types.basis_zig_InputManager_getMappedGamepadButton_cb = undefined;
pub var _InputManager_getMappedInputSource: basis.bindings.generated_types.basis_zig_InputManager_getMappedInputSource_cb = undefined;
pub var _InputManager_getFirstPressedKey: basis.bindings.generated_types.basis_zig_InputManager_getFirstPressedKey_cb = undefined;
pub var _InputManager_getFirstPressedMouseButton: basis.bindings.generated_types.basis_zig_InputManager_getFirstPressedMouseButton_cb = undefined;
pub var _InputManager_getKeyName: basis.bindings.generated_types.basis_zig_InputManager_getKeyName_cb = undefined;

// ===============================

// class PropagatedValue

pub var _PropagatedValue_createFloat: basis.bindings.generated_types.basis_zig_PropagatedValue_createFloat_cb = undefined;
pub var _PropagatedValue_createDouble: basis.bindings.generated_types.basis_zig_PropagatedValue_createDouble_cb = undefined;
pub var _PropagatedValue_createInt32: basis.bindings.generated_types.basis_zig_PropagatedValue_createInt32_cb = undefined;
pub var _PropagatedValue_createUint32: basis.bindings.generated_types.basis_zig_PropagatedValue_createUint32_cb = undefined;
pub var _PropagatedValue_createInt16: basis.bindings.generated_types.basis_zig_PropagatedValue_createInt16_cb = undefined;
pub var _PropagatedValue_createUint16: basis.bindings.generated_types.basis_zig_PropagatedValue_createUint16_cb = undefined;
pub var _PropagatedValue_createInt64: basis.bindings.generated_types.basis_zig_PropagatedValue_createInt64_cb = undefined;
pub var _PropagatedValue_createUint64: basis.bindings.generated_types.basis_zig_PropagatedValue_createUint64_cb = undefined;
pub var _PropagatedValue_createInt8: basis.bindings.generated_types.basis_zig_PropagatedValue_createInt8_cb = undefined;
pub var _PropagatedValue_createUint8: basis.bindings.generated_types.basis_zig_PropagatedValue_createUint8_cb = undefined;
pub var _PropagatedValue_createBool: basis.bindings.generated_types.basis_zig_PropagatedValue_createBool_cb = undefined;
pub var _PropagatedValue_createVec2: basis.bindings.generated_types.basis_zig_PropagatedValue_createVec2_cb = undefined;
pub var _PropagatedValue_createVec3: basis.bindings.generated_types.basis_zig_PropagatedValue_createVec3_cb = undefined;
pub var _PropagatedValue_createVec4: basis.bindings.generated_types.basis_zig_PropagatedValue_createVec4_cb = undefined;
pub var _PropagatedValue_createQuaternion: basis.bindings.generated_types.basis_zig_PropagatedValue_createQuaternion_cb = undefined;
pub var _PropagatedValue_createMat43: basis.bindings.generated_types.basis_zig_PropagatedValue_createMat43_cb = undefined;
pub var _PropagatedValue_setFloat: basis.bindings.generated_types.basis_zig_PropagatedValue_setFloat_cb = undefined;
pub var _PropagatedValue_setDouble: basis.bindings.generated_types.basis_zig_PropagatedValue_setDouble_cb = undefined;
pub var _PropagatedValue_setInt32: basis.bindings.generated_types.basis_zig_PropagatedValue_setInt32_cb = undefined;
pub var _PropagatedValue_setUint32: basis.bindings.generated_types.basis_zig_PropagatedValue_setUint32_cb = undefined;
pub var _PropagatedValue_setInt16: basis.bindings.generated_types.basis_zig_PropagatedValue_setInt16_cb = undefined;
pub var _PropagatedValue_setUint16: basis.bindings.generated_types.basis_zig_PropagatedValue_setUint16_cb = undefined;
pub var _PropagatedValue_setInt64: basis.bindings.generated_types.basis_zig_PropagatedValue_setInt64_cb = undefined;
pub var _PropagatedValue_setUint64: basis.bindings.generated_types.basis_zig_PropagatedValue_setUint64_cb = undefined;
pub var _PropagatedValue_setInt8: basis.bindings.generated_types.basis_zig_PropagatedValue_setInt8_cb = undefined;
pub var _PropagatedValue_setUint8: basis.bindings.generated_types.basis_zig_PropagatedValue_setUint8_cb = undefined;
pub var _PropagatedValue_setBool: basis.bindings.generated_types.basis_zig_PropagatedValue_setBool_cb = undefined;
pub var _PropagatedValue_setVec2: basis.bindings.generated_types.basis_zig_PropagatedValue_setVec2_cb = undefined;
pub var _PropagatedValue_setVec3: basis.bindings.generated_types.basis_zig_PropagatedValue_setVec3_cb = undefined;
pub var _PropagatedValue_setVec4: basis.bindings.generated_types.basis_zig_PropagatedValue_setVec4_cb = undefined;
pub var _PropagatedValue_setQuaternion: basis.bindings.generated_types.basis_zig_PropagatedValue_setQuaternion_cb = undefined;
pub var _PropagatedValue_setMat43: basis.bindings.generated_types.basis_zig_PropagatedValue_setMat43_cb = undefined;
pub var _PropagatedValue_createAction: basis.bindings.generated_types.basis_zig_PropagatedValue_createAction_cb = undefined;
pub var _PropagatedValue_fireAction: basis.bindings.generated_types.basis_zig_PropagatedValue_fireAction_cb = undefined;

// ===============================

// class SceneNode

pub var _SceneNode_newNode: basis.bindings.generated_types.basis_zig_SceneNode_newNode_cb = undefined;
pub var _SceneNode_deleteNode: basis.bindings.generated_types.basis_zig_SceneNode_deleteNode_cb = undefined;
pub var _SceneNode_createChildNode: basis.bindings.generated_types.basis_zig_SceneNode_createChildNode_cb = undefined;
pub var _SceneNode_destroyChildNode: basis.bindings.generated_types.basis_zig_SceneNode_destroyChildNode_cb = undefined;
pub var _SceneNode_detachAll: basis.bindings.generated_types.basis_zig_SceneNode_detachAll_cb = undefined;
pub var _SceneNode_destroyAllChildNodes: basis.bindings.generated_types.basis_zig_SceneNode_destroyAllChildNodes_cb = undefined;
pub var _SceneNode_setPosition: basis.bindings.generated_types.basis_zig_SceneNode_setPosition_cb = undefined;
pub var _SceneNode_getPosition: basis.bindings.generated_types.basis_zig_SceneNode_getPosition_cb = undefined;
pub var _SceneNode_setOrientation: basis.bindings.generated_types.basis_zig_SceneNode_setOrientation_cb = undefined;
pub var _SceneNode_getOrientation: basis.bindings.generated_types.basis_zig_SceneNode_getOrientation_cb = undefined;
pub var _SceneNode_setScale: basis.bindings.generated_types.basis_zig_SceneNode_setScale_cb = undefined;
pub var _SceneNode_getScale: basis.bindings.generated_types.basis_zig_SceneNode_getScale_cb = undefined;
pub var _SceneNode_translate: basis.bindings.generated_types.basis_zig_SceneNode_translate_cb = undefined;
pub var _SceneNode_yaw: basis.bindings.generated_types.basis_zig_SceneNode_yaw_cb = undefined;
pub var _SceneNode_pitch: basis.bindings.generated_types.basis_zig_SceneNode_pitch_cb = undefined;
pub var _SceneNode_roll: basis.bindings.generated_types.basis_zig_SceneNode_roll_cb = undefined;
pub var _SceneNode_lookAtSceneNode: basis.bindings.generated_types.basis_zig_SceneNode_lookAtSceneNode_cb = undefined;
pub var _SceneNode_attachMeshInstance: basis.bindings.generated_types.basis_zig_SceneNode_attachMeshInstance_cb = undefined;
pub var _SceneNode_detachMeshInstance: basis.bindings.generated_types.basis_zig_SceneNode_detachMeshInstance_cb = undefined;
pub var _SceneNode_isMeshInstanceAttached: basis.bindings.generated_types.basis_zig_SceneNode_isMeshInstanceAttached_cb = undefined;
pub var _SceneNode_attachCamera: basis.bindings.generated_types.basis_zig_SceneNode_attachCamera_cb = undefined;
pub var _SceneNode_detachCamera: basis.bindings.generated_types.basis_zig_SceneNode_detachCamera_cb = undefined;
pub var _SceneNode_isCameraAttached: basis.bindings.generated_types.basis_zig_SceneNode_isCameraAttached_cb = undefined;
pub var _SceneNode_getLocalToParentTransform: basis.bindings.generated_types.basis_zig_SceneNode_getLocalToParentTransform_cb = undefined;
pub var _SceneNode_getLocalToWorldTransform: basis.bindings.generated_types.basis_zig_SceneNode_getLocalToWorldTransform_cb = undefined;
pub var _SceneNode_getLocalToAncestorTransform: basis.bindings.generated_types.basis_zig_SceneNode_getLocalToAncestorTransform_cb = undefined;

// ===============================

// class PhysicsScene

pub var _PhysicsScene_addActor: basis.bindings.generated_types.basis_zig_PhysicsScene_addActor_cb = undefined;
pub var _PhysicsScene_removeActor: basis.bindings.generated_types.basis_zig_PhysicsScene_removeActor_cb = undefined;
pub var _PhysicsScene_addVehicleController: basis.bindings.generated_types.basis_zig_PhysicsScene_addVehicleController_cb = undefined;
pub var _PhysicsScene_removeVehicleController: basis.bindings.generated_types.basis_zig_PhysicsScene_removeVehicleController_cb = undefined;
pub var _PhysicsScene_addJoint: basis.bindings.generated_types.basis_zig_PhysicsScene_addJoint_cb = undefined;
pub var _PhysicsScene_removeJoint: basis.bindings.generated_types.basis_zig_PhysicsScene_removeJoint_cb = undefined;
pub var _PhysicsScene_applyRadialForce: basis.bindings.generated_types.basis_zig_PhysicsScene_applyRadialForce_cb = undefined;
pub var _PhysicsScene_applyRadialImpulse: basis.bindings.generated_types.basis_zig_PhysicsScene_applyRadialImpulse_cb = undefined;
pub var _PhysicsScene_sphereSweep: basis.bindings.generated_types.basis_zig_PhysicsScene_sphereSweep_cb = undefined;
pub var _PhysicsScene_sphereSweepEx: basis.bindings.generated_types.basis_zig_PhysicsScene_sphereSweepEx_cb = undefined;
pub var _PhysicsScene_getSphereOverlapping: basis.bindings.generated_types.basis_zig_PhysicsScene_getSphereOverlapping_cb = undefined;
pub var _PhysicsScene_castRay: basis.bindings.generated_types.basis_zig_PhysicsScene_castRay_cb = undefined;
pub var _PhysicsScene_castRayEx: basis.bindings.generated_types.basis_zig_PhysicsScene_castRayEx_cb = undefined;
pub var _PhysicsScene_castRayWithCallback: basis.bindings.generated_types.basis_zig_PhysicsScene_castRayWithCallback_cb = undefined;
pub var _PhysicsScene_setCollisionCallbacksEnabled: basis.bindings.generated_types.basis_zig_PhysicsScene_setCollisionCallbacksEnabled_cb = undefined;

// ===============================

// class PhysicsMaterial

pub var _PhysicsMaterial_getDefaultMaterial: basis.bindings.generated_types.basis_zig_PhysicsMaterial_getDefaultMaterial_cb = undefined;
pub var _PhysicsMaterial_getBaseMaterial: basis.bindings.generated_types.basis_zig_PhysicsMaterial_getBaseMaterial_cb = undefined;
pub var _PhysicsMaterial_createMaterial: basis.bindings.generated_types.basis_zig_PhysicsMaterial_createMaterial_cb = undefined;
pub var _PhysicsMaterial_getBasePhysicsMaterialName: basis.bindings.generated_types.basis_zig_PhysicsMaterial_getBasePhysicsMaterialName_cb = undefined;
pub var _PhysicsMaterial_addRef: basis.bindings.generated_types.basis_zig_PhysicsMaterial_addRef_cb = undefined;
pub var _PhysicsMaterial_release: basis.bindings.generated_types.basis_zig_PhysicsMaterial_release_cb = undefined;

// ===============================

// class PhysicsShape

pub var _PhysicsShape_createBox: basis.bindings.generated_types.basis_zig_PhysicsShape_createBox_cb = undefined;
pub var _PhysicsShape_createSphere: basis.bindings.generated_types.basis_zig_PhysicsShape_createSphere_cb = undefined;
pub var _PhysicsShape_createCapsule: basis.bindings.generated_types.basis_zig_PhysicsShape_createCapsule_cb = undefined;
pub var _PhysicsShape_createCylinder: basis.bindings.generated_types.basis_zig_PhysicsShape_createCylinder_cb = undefined;
pub var _PhysicsShape_createCylinderX: basis.bindings.generated_types.basis_zig_PhysicsShape_createCylinderX_cb = undefined;
pub var _PhysicsShape_createCylinderZ: basis.bindings.generated_types.basis_zig_PhysicsShape_createCylinderZ_cb = undefined;
pub var _PhysicsShape_addRef: basis.bindings.generated_types.basis_zig_PhysicsShape_addRef_cb = undefined;
pub var _PhysicsShape_release: basis.bindings.generated_types.basis_zig_PhysicsShape_release_cb = undefined;

// ===============================

// class PhysicsActor

pub var _PhysicsActor_createRigidBodyDynamic: basis.bindings.generated_types.basis_zig_PhysicsActor_createRigidBodyDynamic_cb = undefined;
pub var _PhysicsActor_createRigidBodyStatic: basis.bindings.generated_types.basis_zig_PhysicsActor_createRigidBodyStatic_cb = undefined;
pub var _PhysicsActor_createBoxTrigger: basis.bindings.generated_types.basis_zig_PhysicsActor_createBoxTrigger_cb = undefined;
pub var _PhysicsActor_createSphereTrigger: basis.bindings.generated_types.basis_zig_PhysicsActor_createSphereTrigger_cb = undefined;
pub var _PhysicsActor_setWorldTransform: basis.bindings.generated_types.basis_zig_PhysicsActor_setWorldTransform_cb = undefined;
pub var _PhysicsActor_getWorldTransform: basis.bindings.generated_types.basis_zig_PhysicsActor_getWorldTransform_cb = undefined;
pub var _PhysicsActor_setKinematicTarget: basis.bindings.generated_types.basis_zig_PhysicsActor_setKinematicTarget_cb = undefined;
pub var _PhysicsActor_setMassData: basis.bindings.generated_types.basis_zig_PhysicsActor_setMassData_cb = undefined;
pub var _PhysicsActor_setContactReportThreshold: basis.bindings.generated_types.basis_zig_PhysicsActor_setContactReportThreshold_cb = undefined;
pub var _PhysicsActor_setSolverIterationCounts: basis.bindings.generated_types.basis_zig_PhysicsActor_setSolverIterationCounts_cb = undefined;
pub var _PhysicsActor_setAngularDamping: basis.bindings.generated_types.basis_zig_PhysicsActor_setAngularDamping_cb = undefined;
pub var _PhysicsActor_setMaxAngularVelocity: basis.bindings.generated_types.basis_zig_PhysicsActor_setMaxAngularVelocity_cb = undefined;
pub var _PhysicsActor_getWorldBounds: basis.bindings.generated_types.basis_zig_PhysicsActor_getWorldBounds_cb = undefined;
pub var _PhysicsActor_associateWithGameObject: basis.bindings.generated_types.basis_zig_PhysicsActor_associateWithGameObject_cb = undefined;
pub var _PhysicsActor_getAssociatedGameObject: basis.bindings.generated_types.basis_zig_PhysicsActor_getAssociatedGameObject_cb = undefined;
pub var _PhysicsActor_isSleeping: basis.bindings.generated_types.basis_zig_PhysicsActor_isSleeping_cb = undefined;
pub var _PhysicsActor_wakeUp: basis.bindings.generated_types.basis_zig_PhysicsActor_wakeUp_cb = undefined;
pub var _PhysicsActor_putToSleep: basis.bindings.generated_types.basis_zig_PhysicsActor_putToSleep_cb = undefined;
pub var _PhysicsActor_setLinearVelocity: basis.bindings.generated_types.basis_zig_PhysicsActor_setLinearVelocity_cb = undefined;
pub var _PhysicsActor_getLinearVelocity: basis.bindings.generated_types.basis_zig_PhysicsActor_getLinearVelocity_cb = undefined;
pub var _PhysicsActor_setAngularVelocity: basis.bindings.generated_types.basis_zig_PhysicsActor_setAngularVelocity_cb = undefined;
pub var _PhysicsActor_getAngularVelocity: basis.bindings.generated_types.basis_zig_PhysicsActor_getAngularVelocity_cb = undefined;
pub var _PhysicsActor_addForce: basis.bindings.generated_types.basis_zig_PhysicsActor_addForce_cb = undefined;
pub var _PhysicsActor_addImpulse: basis.bindings.generated_types.basis_zig_PhysicsActor_addImpulse_cb = undefined;
pub var _PhysicsActor_addRef: basis.bindings.generated_types.basis_zig_PhysicsActor_addRef_cb = undefined;
pub var _PhysicsActor_release: basis.bindings.generated_types.basis_zig_PhysicsActor_release_cb = undefined;

// ===============================

// class PhysicsJoint

pub var _PhysicsJoint_createFixedJoint: basis.bindings.generated_types.basis_zig_PhysicsJoint_createFixedJoint_cb = undefined;
pub var _PhysicsJoint_createSphericalJoint: basis.bindings.generated_types.basis_zig_PhysicsJoint_createSphericalJoint_cb = undefined;
pub var _PhysicsJoint_createDistanceJoint: basis.bindings.generated_types.basis_zig_PhysicsJoint_createDistanceJoint_cb = undefined;
pub var _PhysicsJoint_createDof6Joint: basis.bindings.generated_types.basis_zig_PhysicsJoint_createDof6Joint_cb = undefined;
pub var _PhysicsJoint_createSphericalSpringJoint: basis.bindings.generated_types.basis_zig_PhysicsJoint_createSphericalSpringJoint_cb = undefined;
pub var _PhysicsJoint_enableProjection: basis.bindings.generated_types.basis_zig_PhysicsJoint_enableProjection_cb = undefined;
pub var _PhysicsJoint_setBreakForce: basis.bindings.generated_types.basis_zig_PhysicsJoint_setBreakForce_cb = undefined;
pub var _PhysicsJoint_setDof6Motion: basis.bindings.generated_types.basis_zig_PhysicsJoint_setDof6Motion_cb = undefined;
pub var _PhysicsJoint_setDof6Drive: basis.bindings.generated_types.basis_zig_PhysicsJoint_setDof6Drive_cb = undefined;
pub var _PhysicsJoint_setDof6TwistLimit: basis.bindings.generated_types.basis_zig_PhysicsJoint_setDof6TwistLimit_cb = undefined;
pub var _PhysicsJoint_setDriveGoalPose: basis.bindings.generated_types.basis_zig_PhysicsJoint_setDriveGoalPose_cb = undefined;
pub var _PhysicsJoint_getConstraintForce: basis.bindings.generated_types.basis_zig_PhysicsJoint_getConstraintForce_cb = undefined;
pub var _PhysicsJoint_setInvMassScale0: basis.bindings.generated_types.basis_zig_PhysicsJoint_setInvMassScale0_cb = undefined;
pub var _PhysicsJoint_setInvInertiaScale0: basis.bindings.generated_types.basis_zig_PhysicsJoint_setInvInertiaScale0_cb = undefined;
pub var _PhysicsJoint_setInvMassScale1: basis.bindings.generated_types.basis_zig_PhysicsJoint_setInvMassScale1_cb = undefined;
pub var _PhysicsJoint_setInvInertiaScale1: basis.bindings.generated_types.basis_zig_PhysicsJoint_setInvInertiaScale1_cb = undefined;
pub var _PhysicsJoint_getInvMassScale0: basis.bindings.generated_types.basis_zig_PhysicsJoint_getInvMassScale0_cb = undefined;
pub var _PhysicsJoint_getInvInertiaScale0: basis.bindings.generated_types.basis_zig_PhysicsJoint_getInvInertiaScale0_cb = undefined;
pub var _PhysicsJoint_getInvMassScale1: basis.bindings.generated_types.basis_zig_PhysicsJoint_getInvMassScale1_cb = undefined;
pub var _PhysicsJoint_getInvInertiaScale1: basis.bindings.generated_types.basis_zig_PhysicsJoint_getInvInertiaScale1_cb = undefined;
pub var _PhysicsJoint_addRef: basis.bindings.generated_types.basis_zig_PhysicsJoint_addRef_cb = undefined;
pub var _PhysicsJoint_release: basis.bindings.generated_types.basis_zig_PhysicsJoint_release_cb = undefined;

// ===============================

// class PhysicsTriMesh

pub var _PhysicsTriMesh_createTriMesh: basis.bindings.generated_types.basis_zig_PhysicsTriMesh_createTriMesh_cb = undefined;
pub var _PhysicsTriMesh_getTriangleCount: basis.bindings.generated_types.basis_zig_PhysicsTriMesh_getTriangleCount_cb = undefined;
pub var _PhysicsTriMesh_getTriangleVertices: basis.bindings.generated_types.basis_zig_PhysicsTriMesh_getTriangleVertices_cb = undefined;
pub var _PhysicsTriMesh_pointDistance: basis.bindings.generated_types.basis_zig_PhysicsTriMesh_pointDistance_cb = undefined;
pub var _PhysicsTriMesh_addRef: basis.bindings.generated_types.basis_zig_PhysicsTriMesh_addRef_cb = undefined;
pub var _PhysicsTriMesh_release: basis.bindings.generated_types.basis_zig_PhysicsTriMesh_release_cb = undefined;

// ===============================

// class CharacterController

pub var _CharacterController_setMovementVector: basis.bindings.generated_types.basis_zig_CharacterController_setMovementVector_cb = undefined;
pub var _CharacterController_getMovementVector: basis.bindings.generated_types.basis_zig_CharacterController_getMovementVector_cb = undefined;
pub var _CharacterController_getLinearVelocity: basis.bindings.generated_types.basis_zig_CharacterController_getLinearVelocity_cb = undefined;
pub var _CharacterController_addRef: basis.bindings.generated_types.basis_zig_CharacterController_addRef_cb = undefined;
pub var _CharacterController_release: basis.bindings.generated_types.basis_zig_CharacterController_release_cb = undefined;

// ===============================

// class VehicleController

pub var _VehicleController_createVehicleController: basis.bindings.generated_types.basis_zig_VehicleController_createVehicleController_cb = undefined;
pub var _VehicleController_reinit: basis.bindings.generated_types.basis_zig_VehicleController_reinit_cb = undefined;
pub var _VehicleController_setInputData: basis.bindings.generated_types.basis_zig_VehicleController_setInputData_cb = undefined;
pub var _VehicleController_getInputData: basis.bindings.generated_types.basis_zig_VehicleController_getInputData_cb = undefined;
pub var _VehicleController_startGearChange: basis.bindings.generated_types.basis_zig_VehicleController_startGearChange_cb = undefined;
pub var _VehicleController_forceGearChange: basis.bindings.generated_types.basis_zig_VehicleController_forceGearChange_cb = undefined;
pub var _VehicleController_freezeInputData: basis.bindings.generated_types.basis_zig_VehicleController_freezeInputData_cb = undefined;
pub var _VehicleController_unfreezeInputData: basis.bindings.generated_types.basis_zig_VehicleController_unfreezeInputData_cb = undefined;
pub var _VehicleController_getWheelCount: basis.bindings.generated_types.basis_zig_VehicleController_getWheelCount_cb = undefined;
pub var _VehicleController_getWheelStateInfo: basis.bindings.generated_types.basis_zig_VehicleController_getWheelStateInfo_cb = undefined;
pub var _VehicleController_getStateInfo: basis.bindings.generated_types.basis_zig_VehicleController_getStateInfo_cb = undefined;
pub var _VehicleController_getFastestWheelRotationSpeed: basis.bindings.generated_types.basis_zig_VehicleController_getFastestWheelRotationSpeed_cb = undefined;
pub var _VehicleController_addRef: basis.bindings.generated_types.basis_zig_VehicleController_addRef_cb = undefined;
pub var _VehicleController_release: basis.bindings.generated_types.basis_zig_VehicleController_release_cb = undefined;

// ===============================

// class ResourceManager

pub var _ResourceManager_init: basis.bindings.generated_types.basis_zig_ResourceManager_init_cb = undefined;
pub var _ResourceManager_deinit: basis.bindings.generated_types.basis_zig_ResourceManager_deinit_cb = undefined;
pub var _ResourceManager_acquireResource: basis.bindings.generated_types.basis_zig_ResourceManager_acquireResource_cb = undefined;
pub var _ResourceManager_lock: basis.bindings.generated_types.basis_zig_ResourceManager_lock_cb = undefined;
pub var _ResourceManager_unlock: basis.bindings.generated_types.basis_zig_ResourceManager_unlock_cb = undefined;
pub var _ResourceManager_registerResourceReloadedCallback: basis.bindings.generated_types.basis_zig_ResourceManager_registerResourceReloadedCallback_cb = undefined;
pub var _ResourceManager_unregisterResourceReloadedCallback: basis.bindings.generated_types.basis_zig_ResourceManager_unregisterResourceReloadedCallback_cb = undefined;
pub var _ResourceManager_beginGetResourcesWithFileExtension: basis.bindings.generated_types.basis_zig_ResourceManager_beginGetResourcesWithFileExtension_cb = undefined;
pub var _ResourceManager_endGetResourcesWithFileExtension: basis.bindings.generated_types.basis_zig_ResourceManager_endGetResourcesWithFileExtension_cb = undefined;
pub var _ResourceManager_addLooseFileResourcePack: basis.bindings.generated_types.basis_zig_ResourceManager_addLooseFileResourcePack_cb = undefined;
pub var _ResourceManager_getSourceFilePathForResource: basis.bindings.generated_types.basis_zig_ResourceManager_getSourceFilePathForResource_cb = undefined;

// ===============================

// class Resource

pub var _Resource_getSharedMesh: basis.bindings.generated_types.basis_zig_Resource_getSharedMesh_cb = undefined;
pub var _Resource_hasPhysicsMesh: basis.bindings.generated_types.basis_zig_Resource_hasPhysicsMesh_cb = undefined;
pub var _Resource_getPhysicsMeshData: basis.bindings.generated_types.basis_zig_Resource_getPhysicsMeshData_cb = undefined;
pub var _Resource_getSharedMaterial: basis.bindings.generated_types.basis_zig_Resource_getSharedMaterial_cb = undefined;
pub var _Resource_getRawData: basis.bindings.generated_types.basis_zig_Resource_getRawData_cb = undefined;
pub var _Resource_addRef: basis.bindings.generated_types.basis_zig_Resource_addRef_cb = undefined;
pub var _Resource_release: basis.bindings.generated_types.basis_zig_Resource_release_cb = undefined;

// ===============================

// class Renderer

pub var _Renderer_getPrimaryScene: basis.bindings.generated_types.basis_zig_Renderer_getPrimaryScene_cb = undefined;
pub var _Renderer_addCameraToBackOfQueue: basis.bindings.generated_types.basis_zig_Renderer_addCameraToBackOfQueue_cb = undefined;
pub var _Renderer_addCameraToFrontOfQueue: basis.bindings.generated_types.basis_zig_Renderer_addCameraToFrontOfQueue_cb = undefined;
pub var _Renderer_removeCameraFromQueue: basis.bindings.generated_types.basis_zig_Renderer_removeCameraFromQueue_cb = undefined;
pub var _Renderer_getMainCamera: basis.bindings.generated_types.basis_zig_Renderer_getMainCamera_cb = undefined;
pub var _Renderer_getWindowWidth: basis.bindings.generated_types.basis_zig_Renderer_getWindowWidth_cb = undefined;
pub var _Renderer_getWindowHeight: basis.bindings.generated_types.basis_zig_Renderer_getWindowHeight_cb = undefined;
pub var _Renderer_getRenderWidth: basis.bindings.generated_types.basis_zig_Renderer_getRenderWidth_cb = undefined;
pub var _Renderer_getRenderHeight: basis.bindings.generated_types.basis_zig_Renderer_getRenderHeight_cb = undefined;
pub var _Renderer_getRenderScale: basis.bindings.generated_types.basis_zig_Renderer_getRenderScale_cb = undefined;
pub var _Renderer_setRenderScale: basis.bindings.generated_types.basis_zig_Renderer_setRenderScale_cb = undefined;
pub var _Renderer_setGraphicsOption: basis.bindings.generated_types.basis_zig_Renderer_setGraphicsOption_cb = undefined;
pub var _Renderer_createMesh: basis.bindings.generated_types.basis_zig_Renderer_createMesh_cb = undefined;
pub var _Renderer_createMeshManual: basis.bindings.generated_types.basis_zig_Renderer_createMeshManual_cb = undefined;
pub var _Renderer_captureSinglePre2DFrame: basis.bindings.generated_types.basis_zig_Renderer_captureSinglePre2DFrame_cb = undefined;
pub var _Renderer_captureSingleFullEndUserFrame: basis.bindings.generated_types.basis_zig_Renderer_captureSingleFullEndUserFrame_cb = undefined;
pub var _Renderer_captureSingleFullFrame: basis.bindings.generated_types.basis_zig_Renderer_captureSingleFullFrame_cb = undefined;
pub var _Renderer_startCapturingPre2DFrames: basis.bindings.generated_types.basis_zig_Renderer_startCapturingPre2DFrames_cb = undefined;
pub var _Renderer_startCapturingFullEndUserFrames: basis.bindings.generated_types.basis_zig_Renderer_startCapturingFullEndUserFrames_cb = undefined;
pub var _Renderer_startCapturingFullFrames: basis.bindings.generated_types.basis_zig_Renderer_startCapturingFullFrames_cb = undefined;
pub var _Renderer_stopCapturingFrames: basis.bindings.generated_types.basis_zig_Renderer_stopCapturingFrames_cb = undefined;
pub var _Renderer_applyDisplayOptions: basis.bindings.generated_types.basis_zig_Renderer_applyDisplayOptions_cb = undefined;
pub var _Renderer_applyVsyncAndFramerateLimit: basis.bindings.generated_types.basis_zig_Renderer_applyVsyncAndFramerateLimit_cb = undefined;
pub var _Renderer_getWindowMode: basis.bindings.generated_types.basis_zig_Renderer_getWindowMode_cb = undefined;
pub var _Renderer_getDisplacementEffectRenderer: basis.bindings.generated_types.basis_zig_Renderer_getDisplacementEffectRenderer_cb = undefined;

// ===============================

// class RenderScene

pub var _RenderScene_getRootSceneNode: basis.bindings.generated_types.basis_zig_RenderScene_getRootSceneNode_cb = undefined;
pub var _RenderScene_destroySceneNode: basis.bindings.generated_types.basis_zig_RenderScene_destroySceneNode_cb = undefined;
pub var _RenderScene_createCamera: basis.bindings.generated_types.basis_zig_RenderScene_createCamera_cb = undefined;
pub var _RenderScene_destroyCamera: basis.bindings.generated_types.basis_zig_RenderScene_destroyCamera_cb = undefined;
pub var _RenderScene_createDynamicMeshInstance: basis.bindings.generated_types.basis_zig_RenderScene_createDynamicMeshInstance_cb = undefined;
pub var _RenderScene_createStaticMeshInstance: basis.bindings.generated_types.basis_zig_RenderScene_createStaticMeshInstance_cb = undefined;
pub var _RenderScene_destroyMeshInstance: basis.bindings.generated_types.basis_zig_RenderScene_destroyMeshInstance_cb = undefined;
pub var _RenderScene_castRay: basis.bindings.generated_types.basis_zig_RenderScene_castRay_cb = undefined;
pub var _RenderScene_getTireTrackRenderer: basis.bindings.generated_types.basis_zig_RenderScene_getTireTrackRenderer_cb = undefined;

// ===============================

// class TireTrackRenderer

pub var _TireTrackRenderer_clear: basis.bindings.generated_types.basis_zig_TireTrackRenderer_clear_cb = undefined;
pub var _TireTrackRenderer_registerTire: basis.bindings.generated_types.basis_zig_TireTrackRenderer_registerTire_cb = undefined;
pub var _TireTrackRenderer_unregisterTire: basis.bindings.generated_types.basis_zig_TireTrackRenderer_unregisterTire_cb = undefined;
pub var _TireTrackRenderer_beginTireTrack: basis.bindings.generated_types.basis_zig_TireTrackRenderer_beginTireTrack_cb = undefined;
pub var _TireTrackRenderer_endTireTrack: basis.bindings.generated_types.basis_zig_TireTrackRenderer_endTireTrack_cb = undefined;
pub var _TireTrackRenderer_updateTireTrack: basis.bindings.generated_types.basis_zig_TireTrackRenderer_updateTireTrack_cb = undefined;
pub var _TireTrackRenderer_beginStaticTireTrack: basis.bindings.generated_types.basis_zig_TireTrackRenderer_beginStaticTireTrack_cb = undefined;
pub var _TireTrackRenderer_addPointToStaticTireTrack: basis.bindings.generated_types.basis_zig_TireTrackRenderer_addPointToStaticTireTrack_cb = undefined;
pub var _TireTrackRenderer_endStaticTireTrack: basis.bindings.generated_types.basis_zig_TireTrackRenderer_endStaticTireTrack_cb = undefined;
pub var _TireTrackRenderer_removeStaticTireTrack: basis.bindings.generated_types.basis_zig_TireTrackRenderer_removeStaticTireTrack_cb = undefined;

// ===============================

// class MeshGeometry

pub var _MeshGeometry_newGeometry: basis.bindings.generated_types.basis_zig_MeshGeometry_newGeometry_cb = undefined;
pub var _MeshGeometry_deleteGeometry: basis.bindings.generated_types.basis_zig_MeshGeometry_deleteGeometry_cb = undefined;
pub var _MeshGeometry_clear: basis.bindings.generated_types.basis_zig_MeshGeometry_clear_cb = undefined;
pub var _MeshGeometry_addLodLevel: basis.bindings.generated_types.basis_zig_MeshGeometry_addLodLevel_cb = undefined;
pub var _MeshGeometry_getLodLevel: basis.bindings.generated_types.basis_zig_MeshGeometry_getLodLevel_cb = undefined;
pub var _MeshGeometry_getLodLevelCount: basis.bindings.generated_types.basis_zig_MeshGeometry_getLodLevelCount_cb = undefined;

// ===============================

// class MeshGeometryLodLevel

pub var _MeshGeometryLodLevel_clear: basis.bindings.generated_types.basis_zig_MeshGeometryLodLevel_clear_cb = undefined;
pub var _MeshGeometryLodLevel_addSubMesh: basis.bindings.generated_types.basis_zig_MeshGeometryLodLevel_addSubMesh_cb = undefined;
pub var _MeshGeometryLodLevel_getSubMesh: basis.bindings.generated_types.basis_zig_MeshGeometryLodLevel_getSubMesh_cb = undefined;
pub var _MeshGeometryLodLevel_getSubMeshCount: basis.bindings.generated_types.basis_zig_MeshGeometryLodLevel_getSubMeshCount_cb = undefined;

// ===============================

// class MeshGeometrySubMesh

pub var _MeshGeometrySubMesh_clear: basis.bindings.generated_types.basis_zig_MeshGeometrySubMesh_clear_cb = undefined;
pub var _MeshGeometrySubMesh_addIndex: basis.bindings.generated_types.basis_zig_MeshGeometrySubMesh_addIndex_cb = undefined;
pub var _MeshGeometrySubMesh_addFace: basis.bindings.generated_types.basis_zig_MeshGeometrySubMesh_addFace_cb = undefined;
pub var _MeshGeometrySubMesh_addVertex: basis.bindings.generated_types.basis_zig_MeshGeometrySubMesh_addVertex_cb = undefined;
pub var _MeshGeometrySubMesh_getVertexFormatType: basis.bindings.generated_types.basis_zig_MeshGeometrySubMesh_getVertexFormatType_cb = undefined;
pub var _MeshGeometrySubMesh_getVertexCount: basis.bindings.generated_types.basis_zig_MeshGeometrySubMesh_getVertexCount_cb = undefined;
pub var _MeshGeometrySubMesh_getIndexCount: basis.bindings.generated_types.basis_zig_MeshGeometrySubMesh_getIndexCount_cb = undefined;

// ===============================

// class Mesh

pub var _Mesh_getLodLevelCount: basis.bindings.generated_types.basis_zig_Mesh_getLodLevelCount_cb = undefined;
pub var _Mesh_getLodLevel: basis.bindings.generated_types.basis_zig_Mesh_getLodLevel_cb = undefined;
pub var _Mesh_addRef: basis.bindings.generated_types.basis_zig_Mesh_addRef_cb = undefined;
pub var _Mesh_release: basis.bindings.generated_types.basis_zig_Mesh_release_cb = undefined;

// ===============================

// class MeshLodLevel

pub var _MeshLodLevel_getSubMeshCount: basis.bindings.generated_types.basis_zig_MeshLodLevel_getSubMeshCount_cb = undefined;
pub var _MeshLodLevel_setSubMeshCount: basis.bindings.generated_types.basis_zig_MeshLodLevel_setSubMeshCount_cb = undefined;
pub var _MeshLodLevel_getSubMesh: basis.bindings.generated_types.basis_zig_MeshLodLevel_getSubMesh_cb = undefined;
pub var _MeshLodLevel_getBounds: basis.bindings.generated_types.basis_zig_MeshLodLevel_getBounds_cb = undefined;
pub var _MeshLodLevel_setBounds: basis.bindings.generated_types.basis_zig_MeshLodLevel_setBounds_cb = undefined;

// ===============================

// class MeshSubMesh

pub var _MeshSubMesh_getVertexFormatType: basis.bindings.generated_types.basis_zig_MeshSubMesh_getVertexFormatType_cb = undefined;
pub var _MeshSubMesh_getVertexCount: basis.bindings.generated_types.basis_zig_MeshSubMesh_getVertexCount_cb = undefined;
pub var _MeshSubMesh_setVertexCount: basis.bindings.generated_types.basis_zig_MeshSubMesh_setVertexCount_cb = undefined;
pub var _MeshSubMesh_getIndexCount: basis.bindings.generated_types.basis_zig_MeshSubMesh_getIndexCount_cb = undefined;
pub var _MeshSubMesh_setIndexCount: basis.bindings.generated_types.basis_zig_MeshSubMesh_setIndexCount_cb = undefined;
pub var _MeshSubMesh_getVertices: basis.bindings.generated_types.basis_zig_MeshSubMesh_getVertices_cb = undefined;
pub var _MeshSubMesh_getIndices: basis.bindings.generated_types.basis_zig_MeshSubMesh_getIndices_cb = undefined;

// ===============================

// class Material

pub var _Material_addRef: basis.bindings.generated_types.basis_zig_Material_addRef_cb = undefined;
pub var _Material_release: basis.bindings.generated_types.basis_zig_Material_release_cb = undefined;

// ===============================

// class MeshInstance

pub var _MeshInstance_setVisible: basis.bindings.generated_types.basis_zig_MeshInstance_setVisible_cb = undefined;
pub var _MeshInstance_isVisible: basis.bindings.generated_types.basis_zig_MeshInstance_isVisible_cb = undefined;
pub var _MeshInstance_getMaterial: basis.bindings.generated_types.basis_zig_MeshInstance_getMaterial_cb = undefined;
pub var _MeshInstance_setMaterial: basis.bindings.generated_types.basis_zig_MeshInstance_setMaterial_cb = undefined;
pub var _MeshInstance_getFlags: basis.bindings.generated_types.basis_zig_MeshInstance_getFlags_cb = undefined;
pub var _MeshInstance_isFlagSet: basis.bindings.generated_types.basis_zig_MeshInstance_isFlagSet_cb = undefined;
pub var _MeshInstance_setFlagValue: basis.bindings.generated_types.basis_zig_MeshInstance_setFlagValue_cb = undefined;
pub var _MeshInstance_updateLightProbeData: basis.bindings.generated_types.basis_zig_MeshInstance_updateLightProbeData_cb = undefined;
pub var _MeshInstance_getParentSceneNode: basis.bindings.generated_types.basis_zig_MeshInstance_getParentSceneNode_cb = undefined;
pub var _MeshInstance_setCullDistanceMultiplier: basis.bindings.generated_types.basis_zig_MeshInstance_setCullDistanceMultiplier_cb = undefined;
pub var _MeshInstance_getCullDistanceMultiplier: basis.bindings.generated_types.basis_zig_MeshInstance_getCullDistanceMultiplier_cb = undefined;

// ===============================

// class Camera

pub var _Camera_setPerspective: basis.bindings.generated_types.basis_zig_Camera_setPerspective_cb = undefined;
pub var _Camera_setOrthographic: basis.bindings.generated_types.basis_zig_Camera_setOrthographic_cb = undefined;
pub var _Camera_getWorldPosition: basis.bindings.generated_types.basis_zig_Camera_getWorldPosition_cb = undefined;
pub var _Camera_getForwardDirection: basis.bindings.generated_types.basis_zig_Camera_getForwardDirection_cb = undefined;
pub var _Camera_getFovY: basis.bindings.generated_types.basis_zig_Camera_getFovY_cb = undefined;
pub var _Camera_getFovX: basis.bindings.generated_types.basis_zig_Camera_getFovX_cb = undefined;
pub var _Camera_getNearClip: basis.bindings.generated_types.basis_zig_Camera_getNearClip_cb = undefined;
pub var _Camera_getFarClip: basis.bindings.generated_types.basis_zig_Camera_getFarClip_cb = undefined;
pub var _Camera_getPickRay: basis.bindings.generated_types.basis_zig_Camera_getPickRay_cb = undefined;
pub var _Camera_worldToScreen: basis.bindings.generated_types.basis_zig_Camera_worldToScreen_cb = undefined;
pub var _Camera_worldToScreenUnbounded: basis.bindings.generated_types.basis_zig_Camera_worldToScreenUnbounded_cb = undefined;
pub var _Camera_getViewMatrix: basis.bindings.generated_types.basis_zig_Camera_getViewMatrix_cb = undefined;
pub var _Camera_getProjectionMatrix: basis.bindings.generated_types.basis_zig_Camera_getProjectionMatrix_cb = undefined;
pub var _Camera_getParentSceneNode: basis.bindings.generated_types.basis_zig_Camera_getParentSceneNode_cb = undefined;

// ===============================

// class DisplacementEffectRenderer

pub var _DisplacementEffectRenderer_createShockwaveEffect: basis.bindings.generated_types.basis_zig_DisplacementEffectRenderer_createShockwaveEffect_cb = undefined;
pub var _DisplacementEffectRenderer_createForceFieldEffect: basis.bindings.generated_types.basis_zig_DisplacementEffectRenderer_createForceFieldEffect_cb = undefined;
pub var _DisplacementEffectRenderer_createGravityCraneEffect: basis.bindings.generated_types.basis_zig_DisplacementEffectRenderer_createGravityCraneEffect_cb = undefined;
pub var _DisplacementEffectRenderer_setEffectCutoffDistance: basis.bindings.generated_types.basis_zig_DisplacementEffectRenderer_setEffectCutoffDistance_cb = undefined;
pub var _DisplacementEffectRenderer_setEffectPosition: basis.bindings.generated_types.basis_zig_DisplacementEffectRenderer_setEffectPosition_cb = undefined;
pub var _DisplacementEffectRenderer_setEffectStrength: basis.bindings.generated_types.basis_zig_DisplacementEffectRenderer_setEffectStrength_cb = undefined;
pub var _DisplacementEffectRenderer_stopEffect: basis.bindings.generated_types.basis_zig_DisplacementEffectRenderer_stopEffect_cb = undefined;
pub var _DisplacementEffectRenderer_killEffect: basis.bindings.generated_types.basis_zig_DisplacementEffectRenderer_killEffect_cb = undefined;
pub var _DisplacementEffectRenderer_killAllEffects: basis.bindings.generated_types.basis_zig_DisplacementEffectRenderer_killAllEffects_cb = undefined;

// ===============================

// class GameSession

pub var _GameSession_getSessionType: basis.bindings.generated_types.basis_zig_GameSession_getSessionType_cb = undefined;
pub var _GameSession_getClientCount: basis.bindings.generated_types.basis_zig_GameSession_getClientCount_cb = undefined;
pub var _GameSession_getClient: basis.bindings.generated_types.basis_zig_GameSession_getClient_cb = undefined;
pub var _GameSession_isPaused: basis.bindings.generated_types.basis_zig_GameSession_isPaused_cb = undefined;
pub var _GameSession_requestPause: basis.bindings.generated_types.basis_zig_GameSession_requestPause_cb = undefined;
pub var _GameSession_getTickLevel: basis.bindings.generated_types.basis_zig_GameSession_getTickLevel_cb = undefined;
pub var _GameSession_setTickLevel: basis.bindings.generated_types.basis_zig_GameSession_setTickLevel_cb = undefined;
pub var _GameSession_requestSetTickLevel: basis.bindings.generated_types.basis_zig_GameSession_requestSetTickLevel_cb = undefined;
pub var _GameSession_hasStarted: basis.bindings.generated_types.basis_zig_GameSession_hasStarted_cb = undefined;
pub var _GameSession_hasEnded: basis.bindings.generated_types.basis_zig_GameSession_hasEnded_cb = undefined;
pub var _GameSession_getLevelData: basis.bindings.generated_types.basis_zig_GameSession_getLevelData_cb = undefined;
pub var _GameSession_isContinuousSession: basis.bindings.generated_types.basis_zig_GameSession_isContinuousSession_cb = undefined;

// ===============================

// class GameState

pub var _GameState_getGameObject: basis.bindings.generated_types.basis_zig_GameState_getGameObject_cb = undefined;
pub var _GameState_getGameObjectFromRenderable: basis.bindings.generated_types.basis_zig_GameState_getGameObjectFromRenderable_cb = undefined;
pub var _GameState_createGameObject: basis.bindings.generated_types.basis_zig_GameState_createGameObject_cb = undefined;
pub var _GameState_createGameObjectWithStartTransform: basis.bindings.generated_types.basis_zig_GameState_createGameObjectWithStartTransform_cb = undefined;
pub var _GameState_createGameObjectWithSpawnPointIndex: basis.bindings.generated_types.basis_zig_GameState_createGameObjectWithSpawnPointIndex_cb = undefined;
pub var _GameState_createGameObjectWithSpawnPointName: basis.bindings.generated_types.basis_zig_GameState_createGameObjectWithSpawnPointName_cb = undefined;
pub var _GameState_createGameObjectWithParameters: basis.bindings.generated_types.basis_zig_GameState_createGameObjectWithParameters_cb = undefined;
pub var _GameState_destroyGameObject: basis.bindings.generated_types.basis_zig_GameState_destroyGameObject_cb = undefined;
pub var _GameState_hasGameObject: basis.bindings.generated_types.basis_zig_GameState_hasGameObject_cb = undefined;
pub var _GameState_setAvatarObject: basis.bindings.generated_types.basis_zig_GameState_setAvatarObject_cb = undefined;
pub var _GameState_clearAvatarObject: basis.bindings.generated_types.basis_zig_GameState_clearAvatarObject_cb = undefined;
pub var _GameState_getAvatarObjectByHostID: basis.bindings.generated_types.basis_zig_GameState_getAvatarObjectByHostID_cb = undefined;
pub var _GameState_getHostIDByAvatarObject: basis.bindings.generated_types.basis_zig_GameState_getHostIDByAvatarObject_cb = undefined;
pub var _GameState_broadcastScriptMessage: basis.bindings.generated_types.basis_zig_GameState_broadcastScriptMessage_cb = undefined;
pub var _GameState_sendScriptMessageToGameObject: basis.bindings.generated_types.basis_zig_GameState_sendScriptMessageToGameObject_cb = undefined;
pub var _GameState_generateGameObjectName: basis.bindings.generated_types.basis_zig_GameState_generateGameObjectName_cb = undefined;

// ===============================

// class LevelData

pub var _LevelData_getDataBlockManager: basis.bindings.generated_types.basis_zig_LevelData_getDataBlockManager_cb = undefined;

// ===============================

// class LevelDataBlockManager

pub var _LevelDataBlockManager_getDataBlock: basis.bindings.generated_types.basis_zig_LevelDataBlockManager_getDataBlock_cb = undefined;
pub var _LevelDataBlockManager_addDataBlock: basis.bindings.generated_types.basis_zig_LevelDataBlockManager_addDataBlock_cb = undefined;
pub var _LevelDataBlockManager_addDataBlockIfDoesNotExist: basis.bindings.generated_types.basis_zig_LevelDataBlockManager_addDataBlockIfDoesNotExist_cb = undefined;
pub var _LevelDataBlockManager_getMutableDataBlock: basis.bindings.generated_types.basis_zig_LevelDataBlockManager_getMutableDataBlock_cb = undefined;
pub var _LevelDataBlockManager_hasDataBlock: basis.bindings.generated_types.basis_zig_LevelDataBlockManager_hasDataBlock_cb = undefined;

// ===============================

// class LevelDataBlock

pub var _LevelDataBlock_getReadBuffer: basis.bindings.generated_types.basis_zig_LevelDataBlock_getReadBuffer_cb = undefined;
pub var _LevelDataBlock_getChunkStartReadBufferPosition: basis.bindings.generated_types.basis_zig_LevelDataBlock_getChunkStartReadBufferPosition_cb = undefined;
pub var _LevelDataBlock_setReadBufferPosition: basis.bindings.generated_types.basis_zig_LevelDataBlock_setReadBufferPosition_cb = undefined;
pub var _LevelDataBlock_getWriteBuffer: basis.bindings.generated_types.basis_zig_LevelDataBlock_getWriteBuffer_cb = undefined;
pub var _LevelDataBlock_beginWritingChunk: basis.bindings.generated_types.basis_zig_LevelDataBlock_beginWritingChunk_cb = undefined;
pub var _LevelDataBlock_finishWritingChunk: basis.bindings.generated_types.basis_zig_LevelDataBlock_finishWritingChunk_cb = undefined;
pub var _LevelDataBlock_getChunkCount: basis.bindings.generated_types.basis_zig_LevelDataBlock_getChunkCount_cb = undefined;

// ===============================

// class NavMeshRuntime

pub var _NavMeshRuntime_hasNavMesh: basis.bindings.generated_types.basis_zig_NavMeshRuntime_hasNavMesh_cb = undefined;
pub var _NavMeshRuntime_findPath: basis.bindings.generated_types.basis_zig_NavMeshRuntime_findPath_cb = undefined;
pub var _NavMeshRuntime_findClosestPointOnNavMesh: basis.bindings.generated_types.basis_zig_NavMeshRuntime_findClosestPointOnNavMesh_cb = undefined;
pub var _NavMeshRuntime_findRandomPointAroundCircle: basis.bindings.generated_types.basis_zig_NavMeshRuntime_findRandomPointAroundCircle_cb = undefined;
pub var _NavMeshRuntime_overlapsNavMesh: basis.bindings.generated_types.basis_zig_NavMeshRuntime_overlapsNavMesh_cb = undefined;
pub var _NavMeshRuntime_addObstacle: basis.bindings.generated_types.basis_zig_NavMeshRuntime_addObstacle_cb = undefined;
pub var _NavMeshRuntime_updateObstacle: basis.bindings.generated_types.basis_zig_NavMeshRuntime_updateObstacle_cb = undefined;
pub var _NavMeshRuntime_removeObstacle: basis.bindings.generated_types.basis_zig_NavMeshRuntime_removeObstacle_cb = undefined;

// ===============================

// class StreamingUtils

pub var _StreamingUtils_setStreamingPosition: basis.bindings.generated_types.basis_zig_StreamingUtils_setStreamingPosition_cb = undefined;
pub var _StreamingUtils_getStreamingPosition: basis.bindings.generated_types.basis_zig_StreamingUtils_getStreamingPosition_cb = undefined;
pub var _StreamingUtils_setStreamingPositionUpdateMode: basis.bindings.generated_types.basis_zig_StreamingUtils_setStreamingPositionUpdateMode_cb = undefined;
pub var _StreamingUtils_getStreamingPositionUpdateMode: basis.bindings.generated_types.basis_zig_StreamingUtils_getStreamingPositionUpdateMode_cb = undefined;

// ===============================

// class ScreenFade

pub var _ScreenFade_isActive: basis.bindings.generated_types.basis_zig_ScreenFade_isActive_cb = undefined;
pub var _ScreenFade_fade: basis.bindings.generated_types.basis_zig_ScreenFade_fade_cb = undefined;
pub var _ScreenFade_fadeWithCallback: basis.bindings.generated_types.basis_zig_ScreenFade_fadeWithCallback_cb = undefined;
pub var _ScreenFade_setColor: basis.bindings.generated_types.basis_zig_ScreenFade_setColor_cb = undefined;
pub var _ScreenFade_clear: basis.bindings.generated_types.basis_zig_ScreenFade_clear_cb = undefined;

// ===============================

// class StateMachine

pub var _StateMachine_registerFlowState: basis.bindings.generated_types.basis_zig_StateMachine_registerFlowState_cb = undefined;
pub var _StateMachine_setCallbacksForGroup: basis.bindings.generated_types.basis_zig_StateMachine_setCallbacksForGroup_cb = undefined;
pub var _StateMachine_clearCallbacksForGroup: basis.bindings.generated_types.basis_zig_StateMachine_clearCallbacksForGroup_cb = undefined;

// ===============================

// class FlowState

pub var _FlowState_startTransition: basis.bindings.generated_types.basis_zig_FlowState_startTransition_cb = undefined;
pub var _FlowState_subscribeToMessageCategory: basis.bindings.generated_types.basis_zig_FlowState_subscribeToMessageCategory_cb = undefined;
pub var _FlowState_allocMsgParams: basis.bindings.generated_types.basis_zig_FlowState_allocMsgParams_cb = undefined;
pub var _FlowState_sendMessage: basis.bindings.generated_types.basis_zig_FlowState_sendMessage_cb = undefined;
pub var _FlowState_getClient: basis.bindings.generated_types.basis_zig_FlowState_getClient_cb = undefined;
pub var _FlowState_getServer: basis.bindings.generated_types.basis_zig_FlowState_getServer_cb = undefined;

// ===============================

// class DebugOverlay

pub var _DebugOverlay_isVisible: basis.bindings.generated_types.basis_zig_DebugOverlay_isVisible_cb = undefined;
pub var _DebugOverlay_setImGuiMenuBarCallbackEnabled: basis.bindings.generated_types.basis_zig_DebugOverlay_setImGuiMenuBarCallbackEnabled_cb = undefined;
pub var _DebugOverlay_setImGuiCallbackEnabled: basis.bindings.generated_types.basis_zig_DebugOverlay_setImGuiCallbackEnabled_cb = undefined;
pub var _DebugOverlay_debugTrace: basis.bindings.generated_types.basis_zig_DebugOverlay_debugTrace_cb = undefined;
pub var _DebugOverlay_debugWarning: basis.bindings.generated_types.basis_zig_DebugOverlay_debugWarning_cb = undefined;
pub var _DebugOverlay_areDebugObjectWindowKeysPressed: basis.bindings.generated_types.basis_zig_DebugOverlay_areDebugObjectWindowKeysPressed_cb = undefined;
pub var _DebugOverlay_showDebugActionAtPosition: basis.bindings.generated_types.basis_zig_DebugOverlay_showDebugActionAtPosition_cb = undefined;
pub var _DebugOverlay_addDebugSpawnableObjectType: basis.bindings.generated_types.basis_zig_DebugOverlay_addDebugSpawnableObjectType_cb = undefined;

// ===============================

// class Editor

pub var _Editor_printInfo: basis.bindings.generated_types.basis_zig_Editor_printInfo_cb = undefined;
pub var _Editor_printWarning: basis.bindings.generated_types.basis_zig_Editor_printWarning_cb = undefined;
pub var _Editor_printError: basis.bindings.generated_types.basis_zig_Editor_printError_cb = undefined;
pub var _Editor_getEditorCamera: basis.bindings.generated_types.basis_zig_Editor_getEditorCamera_cb = undefined;

// ===============================

// class ImGui

pub var _ImGui_begin: basis.bindings.generated_types.basis_zig_ImGui_begin_cb = undefined;
pub var _ImGui_beginEx: basis.bindings.generated_types.basis_zig_ImGui_beginEx_cb = undefined;
pub var _ImGui_end: basis.bindings.generated_types.basis_zig_ImGui_end_cb = undefined;
pub var _ImGui_beginMenu: basis.bindings.generated_types.basis_zig_ImGui_beginMenu_cb = undefined;
pub var _ImGui_endMenu: basis.bindings.generated_types.basis_zig_ImGui_endMenu_cb = undefined;
pub var _ImGui_menuItem: basis.bindings.generated_types.basis_zig_ImGui_menuItem_cb = undefined;
pub var _ImGui_openPopup: basis.bindings.generated_types.basis_zig_ImGui_openPopup_cb = undefined;
pub var _ImGui_beginPopup: basis.bindings.generated_types.basis_zig_ImGui_beginPopup_cb = undefined;
pub var _ImGui_endPopup: basis.bindings.generated_types.basis_zig_ImGui_endPopup_cb = undefined;
pub var _ImGui_beginPopupModal: basis.bindings.generated_types.basis_zig_ImGui_beginPopupModal_cb = undefined;
pub var _ImGui_closeCurrentPopup: basis.bindings.generated_types.basis_zig_ImGui_closeCurrentPopup_cb = undefined;
pub var _ImGui_setItemDefaultFocus: basis.bindings.generated_types.basis_zig_ImGui_setItemDefaultFocus_cb = undefined;
pub var _ImGui_dummy: basis.bindings.generated_types.basis_zig_ImGui_dummy_cb = undefined;
pub var _ImGui_getMainViewportCenter: basis.bindings.generated_types.basis_zig_ImGui_getMainViewportCenter_cb = undefined;
pub var _ImGui_pushStyleColor: basis.bindings.generated_types.basis_zig_ImGui_pushStyleColor_cb = undefined;
pub var _ImGui_popStyleColor: basis.bindings.generated_types.basis_zig_ImGui_popStyleColor_cb = undefined;
pub var _ImGui_separator: basis.bindings.generated_types.basis_zig_ImGui_separator_cb = undefined;
pub var _ImGui_text: basis.bindings.generated_types.basis_zig_ImGui_text_cb = undefined;
pub var _ImGui_textColored: basis.bindings.generated_types.basis_zig_ImGui_textColored_cb = undefined;
pub var _ImGui_sameline: basis.bindings.generated_types.basis_zig_ImGui_sameline_cb = undefined;
pub var _ImGui_collapsingHeader: basis.bindings.generated_types.basis_zig_ImGui_collapsingHeader_cb = undefined;
pub var _ImGui_button: basis.bindings.generated_types.basis_zig_ImGui_button_cb = undefined;
pub var _ImGui_isItemHovered: basis.bindings.generated_types.basis_zig_ImGui_isItemHovered_cb = undefined;
pub var _ImGui_setTooltip: basis.bindings.generated_types.basis_zig_ImGui_setTooltip_cb = undefined;
pub var _ImGui_endTooltip: basis.bindings.generated_types.basis_zig_ImGui_endTooltip_cb = undefined;
pub var _ImGui_setNextWindowPos: basis.bindings.generated_types.basis_zig_ImGui_setNextWindowPos_cb = undefined;
pub var _ImGui_setNextWindowSize: basis.bindings.generated_types.basis_zig_ImGui_setNextWindowSize_cb = undefined;
pub var _ImGui_setNextWindowBgAlpha: basis.bindings.generated_types.basis_zig_ImGui_setNextWindowBgAlpha_cb = undefined;
pub var _ImGui_beginListBox: basis.bindings.generated_types.basis_zig_ImGui_beginListBox_cb = undefined;
pub var _ImGui_endListBox: basis.bindings.generated_types.basis_zig_ImGui_endListBox_cb = undefined;
pub var _ImGui_radioButton: basis.bindings.generated_types.basis_zig_ImGui_radioButton_cb = undefined;
pub var _ImGui_getScrollX: basis.bindings.generated_types.basis_zig_ImGui_getScrollX_cb = undefined;
pub var _ImGui_getScrollY: basis.bindings.generated_types.basis_zig_ImGui_getScrollY_cb = undefined;
pub var _ImGui_setScrollX: basis.bindings.generated_types.basis_zig_ImGui_setScrollX_cb = undefined;
pub var _ImGui_setScrollY: basis.bindings.generated_types.basis_zig_ImGui_setScrollY_cb = undefined;
pub var _ImGui_getScrollMaxX: basis.bindings.generated_types.basis_zig_ImGui_getScrollMaxX_cb = undefined;
pub var _ImGui_getScrollMaxY: basis.bindings.generated_types.basis_zig_ImGui_getScrollMaxY_cb = undefined;
pub var _ImGui_setScrollHereX: basis.bindings.generated_types.basis_zig_ImGui_setScrollHereX_cb = undefined;
pub var _ImGui_setScrollHereY: basis.bindings.generated_types.basis_zig_ImGui_setScrollHereY_cb = undefined;
pub var _ImGui_setScrollFromPosX: basis.bindings.generated_types.basis_zig_ImGui_setScrollFromPosX_cb = undefined;
pub var _ImGui_setScrollFromPosY: basis.bindings.generated_types.basis_zig_ImGui_setScrollFromPosY_cb = undefined;
pub var _ImGui_dragFloat: basis.bindings.generated_types.basis_zig_ImGui_dragFloat_cb = undefined;
pub var _ImGui_dragInt: basis.bindings.generated_types.basis_zig_ImGui_dragInt_cb = undefined;
pub var _ImGui_sliderFloat: basis.bindings.generated_types.basis_zig_ImGui_sliderFloat_cb = undefined;
pub var _ImGui_sliderInt: basis.bindings.generated_types.basis_zig_ImGui_sliderInt_cb = undefined;
pub var _ImGui_plotMultiLines: basis.bindings.generated_types.basis_zig_ImGui_plotMultiLines_cb = undefined;
pub var _ImGui_getContentRegionAvail: basis.bindings.generated_types.basis_zig_ImGui_getContentRegionAvail_cb = undefined;
pub var _ImGui_pushID: basis.bindings.generated_types.basis_zig_ImGui_pushID_cb = undefined;
pub var _ImGui_pushIDPtr: basis.bindings.generated_types.basis_zig_ImGui_pushIDPtr_cb = undefined;
pub var _ImGui_popID: basis.bindings.generated_types.basis_zig_ImGui_popID_cb = undefined;

// ===============================

// class ImPlot

pub var _ImPlot_beginPlot: basis.bindings.generated_types.basis_zig_ImPlot_beginPlot_cb = undefined;
pub var _ImPlot_endPlot: basis.bindings.generated_types.basis_zig_ImPlot_endPlot_cb = undefined;
pub var _ImPlot_setupAxis: basis.bindings.generated_types.basis_zig_ImPlot_setupAxis_cb = undefined;
pub var _ImPlot_setupAxisLimits: basis.bindings.generated_types.basis_zig_ImPlot_setupAxisLimits_cb = undefined;
pub var _ImPlot_setupLegend: basis.bindings.generated_types.basis_zig_ImPlot_setupLegend_cb = undefined;
pub var _ImPlot_plotLine: basis.bindings.generated_types.basis_zig_ImPlot_plotLine_cb = undefined;
pub var _ImPlot_plotLineEx: basis.bindings.generated_types.basis_zig_ImPlot_plotLineEx_cb = undefined;
pub var _ImPlot_plotScatter: basis.bindings.generated_types.basis_zig_ImPlot_plotScatter_cb = undefined;
pub var _ImPlot_plotScatterEx: basis.bindings.generated_types.basis_zig_ImPlot_plotScatterEx_cb = undefined;
pub var _ImPlot_dragPoint: basis.bindings.generated_types.basis_zig_ImPlot_dragPoint_cb = undefined;

// ===============================

// class GameObjectCreationParameters

pub var _GameObjectCreationParameters_newParams: basis.bindings.generated_types.basis_zig_GameObjectCreationParameters_newParams_cb = undefined;
pub var _GameObjectCreationParameters_newParamsWithNameAndType: basis.bindings.generated_types.basis_zig_GameObjectCreationParameters_newParamsWithNameAndType_cb = undefined;
pub var _GameObjectCreationParameters_deleteParams: basis.bindings.generated_types.basis_zig_GameObjectCreationParameters_deleteParams_cb = undefined;
pub var _GameObjectCreationParameters_setStartTransform: basis.bindings.generated_types.basis_zig_GameObjectCreationParameters_setStartTransform_cb = undefined;
pub var _GameObjectCreationParameters_setPropertyBundlePath: basis.bindings.generated_types.basis_zig_GameObjectCreationParameters_setPropertyBundlePath_cb = undefined;

// ===============================

// class OSUtility

pub var _OSUtility_writeStringToClipboard: basis.bindings.generated_types.basis_zig_OSUtility_writeStringToClipboard_cb = undefined;
pub var _OSUtility_readStringFromClipboard: basis.bindings.generated_types.basis_zig_OSUtility_readStringFromClipboard_cb = undefined;

// ===============================

// class ExposedPropertyLayoutReader

pub var _ExposedPropertyLayoutReader_init: basis.bindings.generated_types.basis_zig_ExposedPropertyLayoutReader_init_cb = undefined;
pub var _ExposedPropertyLayoutReader_processProperty: basis.bindings.generated_types.basis_zig_ExposedPropertyLayoutReader_processProperty_cb = undefined;
pub var _ExposedPropertyLayoutReader_processString: basis.bindings.generated_types.basis_zig_ExposedPropertyLayoutReader_processString_cb = undefined;
pub var _ExposedPropertyLayoutReader_processResourceRef: basis.bindings.generated_types.basis_zig_ExposedPropertyLayoutReader_processResourceRef_cb = undefined;
pub var _ExposedPropertyLayoutReader_processButton: basis.bindings.generated_types.basis_zig_ExposedPropertyLayoutReader_processButton_cb = undefined;
pub var _ExposedPropertyLayoutReader_processCategory: basis.bindings.generated_types.basis_zig_ExposedPropertyLayoutReader_processCategory_cb = undefined;
pub var _ExposedPropertyLayoutReader_processEnum: basis.bindings.generated_types.basis_zig_ExposedPropertyLayoutReader_processEnum_cb = undefined;
pub var _ExposedPropertyLayoutReader_allPropertiesProcessed: basis.bindings.generated_types.basis_zig_ExposedPropertyLayoutReader_allPropertiesProcessed_cb = undefined;

// ===============================

// class ZigAngelScriptTypeRegistration

pub var _ZigAngelScriptTypeRegistration_registerEnumType: basis.bindings.generated_types.basis_zig_ZigAngelScriptTypeRegistration_registerEnumType_cb = undefined;
pub var _ZigAngelScriptTypeRegistration_registerEnumValue: basis.bindings.generated_types.basis_zig_ZigAngelScriptTypeRegistration_registerEnumValue_cb = undefined;

// ===============================

// class ZigAngelScriptComponentRegistration

pub var _ZigAngelScriptComponentRegistration_registerComponentType: basis.bindings.generated_types.basis_zig_ZigAngelScriptComponentRegistration_registerComponentType_cb = undefined;
pub var _ZigAngelScriptComponentRegistration_registerComponentMethod: basis.bindings.generated_types.basis_zig_ZigAngelScriptComponentRegistration_registerComponentMethod_cb = undefined;
pub var _ZigAngelScriptComponentRegistration_registerComponentEventAutoComplete: basis.bindings.generated_types.basis_zig_ZigAngelScriptComponentRegistration_registerComponentEventAutoComplete_cb = undefined;

// ===============================

// class AngelScriptUtils

pub var _AngelScriptUtils_getStringRefConstIn: basis.bindings.generated_types.basis_zig_AngelScriptUtils_getStringRefConstIn_cb = undefined;
pub var _AngelScriptUtils_setStringRefOut: basis.bindings.generated_types.basis_zig_AngelScriptUtils_setStringRefOut_cb = undefined;
pub var _AngelScriptUtils_getGameObjectRefConstIn: basis.bindings.generated_types.basis_zig_AngelScriptUtils_getGameObjectRefConstIn_cb = undefined;
pub var _AngelScriptUtils_getHashFromGameObjectRefConstIn: basis.bindings.generated_types.basis_zig_AngelScriptUtils_getHashFromGameObjectRefConstIn_cb = undefined;
pub var _AngelScriptUtils_setGameObjectRefOut: basis.bindings.generated_types.basis_zig_AngelScriptUtils_setGameObjectRefOut_cb = undefined;
pub var _AngelScriptUtils_getColorRefConstIn: basis.bindings.generated_types.basis_zig_AngelScriptUtils_getColorRefConstIn_cb = undefined;
pub var _AngelScriptUtils_setColorRefOut: basis.bindings.generated_types.basis_zig_AngelScriptUtils_setColorRefOut_cb = undefined;
pub var _AngelScriptUtils_addRefToASFuncPtr: basis.bindings.generated_types.basis_zig_AngelScriptUtils_addRefToASFuncPtr_cb = undefined;
pub var _AngelScriptUtils_releaseASFuncPtr: basis.bindings.generated_types.basis_zig_AngelScriptUtils_releaseASFuncPtr_cb = undefined;

// ===============================

