// ----------------------------------------------------
// Copyright (c) 2018-2026 Madrigal Ltd.
// This file is part of the Basis SDK, and is subject to the
// terms and conditions of the Basis SDK License Agreement.
// https://www.madrigalgames.com
// ----------------------------------------------------

// This file was generated by Sir Bindalot, the binding generator. Ne pas toucher!

const basis = @import("basis");
const timbre = @import("../timbre.zig");

// class TimbreSoundManager

pub var _TimbreSoundManager_getMasterGroupBus: timbre.bindings.generated_types.basis_zig_TimbreSoundManager_getMasterGroupBus_cb = undefined;
pub var _TimbreSoundManager_getGroupBus: timbre.bindings.generated_types.basis_zig_TimbreSoundManager_getGroupBus_cb = undefined;
pub var _TimbreSoundManager_getEventDesc: timbre.bindings.generated_types.basis_zig_TimbreSoundManager_getEventDesc_cb = undefined;
pub var _TimbreSoundManager_playAndForget2D: timbre.bindings.generated_types.basis_zig_TimbreSoundManager_playAndForget2D_cb = undefined;
pub var _TimbreSoundManager_playAndForget3D: timbre.bindings.generated_types.basis_zig_TimbreSoundManager_playAndForget3D_cb = undefined;
pub var _TimbreSoundManager_playByPathAndForget2D: timbre.bindings.generated_types.basis_zig_TimbreSoundManager_playByPathAndForget2D_cb = undefined;
pub var _TimbreSoundManager_playByPathAndForget3D: timbre.bindings.generated_types.basis_zig_TimbreSoundManager_playByPathAndForget3D_cb = undefined;
pub var _TimbreSoundManager_getBulkAudioAssetDuration: timbre.bindings.generated_types.basis_zig_TimbreSoundManager_getBulkAudioAssetDuration_cb = undefined;
pub var _TimbreSoundManager_getBulkAudioAssetDurationByHash: timbre.bindings.generated_types.basis_zig_TimbreSoundManager_getBulkAudioAssetDurationByHash_cb = undefined;
pub var _TimbreSoundManager_getBulkAudioAssetID: timbre.bindings.generated_types.basis_zig_TimbreSoundManager_getBulkAudioAssetID_cb = undefined;
pub var _TimbreSoundManager_getBulkAudioAssetData: timbre.bindings.generated_types.basis_zig_TimbreSoundManager_getBulkAudioAssetData_cb = undefined;

// ===============================

// class GroupBus

pub var _GroupBus_getVolume: timbre.bindings.generated_types.basis_zig_GroupBus_getVolume_cb = undefined;
pub var _GroupBus_setVolume: timbre.bindings.generated_types.basis_zig_GroupBus_setVolume_cb = undefined;

// ===============================

// class EventDescription

pub var _EventDescription_createInstance: timbre.bindings.generated_types.basis_zig_EventDescription_createInstance_cb = undefined;
pub var _EventDescription_createInstanceWithAutoPauseTickLevel: timbre.bindings.generated_types.basis_zig_EventDescription_createInstanceWithAutoPauseTickLevel_cb = undefined;
pub var _EventDescription_getParameterIndex: timbre.bindings.generated_types.basis_zig_EventDescription_getParameterIndex_cb = undefined;
pub var _EventDescription_getLength: timbre.bindings.generated_types.basis_zig_EventDescription_getLength_cb = undefined;

// ===============================

// class EventInstance

pub var _EventInstance_release: timbre.bindings.generated_types.basis_zig_EventInstance_release_cb = undefined;
pub var _EventInstance_releaseWhenFinished: timbre.bindings.generated_types.basis_zig_EventInstance_releaseWhenFinished_cb = undefined;
pub var _EventInstance_releaseAfterFadeOut: timbre.bindings.generated_types.basis_zig_EventInstance_releaseAfterFadeOut_cb = undefined;
pub var _EventInstance_getState: timbre.bindings.generated_types.basis_zig_EventInstance_getState_cb = undefined;
pub var _EventInstance_start: timbre.bindings.generated_types.basis_zig_EventInstance_start_cb = undefined;
pub var _EventInstance_pause: timbre.bindings.generated_types.basis_zig_EventInstance_pause_cb = undefined;
pub var _EventInstance_unpause: timbre.bindings.generated_types.basis_zig_EventInstance_unpause_cb = undefined;
pub var _EventInstance_stop: timbre.bindings.generated_types.basis_zig_EventInstance_stop_cb = undefined;
pub var _EventInstance_setParameterByName: timbre.bindings.generated_types.basis_zig_EventInstance_setParameterByName_cb = undefined;
pub var _EventInstance_setParameterByIndex: timbre.bindings.generated_types.basis_zig_EventInstance_setParameterByIndex_cb = undefined;
pub var _EventInstance_setWaveAssetRefParameterByName: timbre.bindings.generated_types.basis_zig_EventInstance_setWaveAssetRefParameterByName_cb = undefined;
pub var _EventInstance_setWaveAssetRefParameterByIndex: timbre.bindings.generated_types.basis_zig_EventInstance_setWaveAssetRefParameterByIndex_cb = undefined;
pub var _EventInstance_set3DParameters: timbre.bindings.generated_types.basis_zig_EventInstance_set3DParameters_cb = undefined;
pub var _EventInstance_sendSignal: timbre.bindings.generated_types.basis_zig_EventInstance_sendSignal_cb = undefined;
pub var _EventInstance_fadeIn: timbre.bindings.generated_types.basis_zig_EventInstance_fadeIn_cb = undefined;
pub var _EventInstance_getVolumeMultiplier: timbre.bindings.generated_types.basis_zig_EventInstance_getVolumeMultiplier_cb = undefined;
pub var _EventInstance_setVolumeMultiplier: timbre.bindings.generated_types.basis_zig_EventInstance_setVolumeMultiplier_cb = undefined;

// ===============================

