// ----------------------------------------------------
// Copyright (c) 2018-2025 Madrigal Ltd.
// This file is part of the Basis SDK, and is subject to the
// terms and conditions of the Basis SDK License Agreement.
// https://www.madrigalgames.com
// ----------------------------------------------------

// This file was generated by Sir Bindalot, the binding generator. Ne pas toucher!

const basis = @import("basis");
const timbre = @import("../timbre.zig");

// class TimbreSoundManager

export fn bindTimbreSoundManager(
	getMasterGroupBus: timbre.bindings.generated_types.basis_zig_TimbreSoundManager_getMasterGroupBus_cb,
	getGroupBus: timbre.bindings.generated_types.basis_zig_TimbreSoundManager_getGroupBus_cb,
	getEventDesc: timbre.bindings.generated_types.basis_zig_TimbreSoundManager_getEventDesc_cb,
	playAndForget2D: timbre.bindings.generated_types.basis_zig_TimbreSoundManager_playAndForget2D_cb,
	playAndForget3D: timbre.bindings.generated_types.basis_zig_TimbreSoundManager_playAndForget3D_cb,
	playByPathAndForget2D: timbre.bindings.generated_types.basis_zig_TimbreSoundManager_playByPathAndForget2D_cb,
	playByPathAndForget3D: timbre.bindings.generated_types.basis_zig_TimbreSoundManager_playByPathAndForget3D_cb,
) void {
	timbre.bindings.generated_function_pointers._TimbreSoundManager_getMasterGroupBus = getMasterGroupBus;
	timbre.bindings.generated_function_pointers._TimbreSoundManager_getGroupBus = getGroupBus;
	timbre.bindings.generated_function_pointers._TimbreSoundManager_getEventDesc = getEventDesc;
	timbre.bindings.generated_function_pointers._TimbreSoundManager_playAndForget2D = playAndForget2D;
	timbre.bindings.generated_function_pointers._TimbreSoundManager_playAndForget3D = playAndForget3D;
	timbre.bindings.generated_function_pointers._TimbreSoundManager_playByPathAndForget2D = playByPathAndForget2D;
	timbre.bindings.generated_function_pointers._TimbreSoundManager_playByPathAndForget3D = playByPathAndForget3D;
}

// ===============================

// class GroupBus

export fn bindGroupBus(
	getVolume: timbre.bindings.generated_types.basis_zig_GroupBus_getVolume_cb,
	setVolume: timbre.bindings.generated_types.basis_zig_GroupBus_setVolume_cb,
) void {
	timbre.bindings.generated_function_pointers._GroupBus_getVolume = getVolume;
	timbre.bindings.generated_function_pointers._GroupBus_setVolume = setVolume;
}

// ===============================

// class EventDescription

export fn bindEventDescription(
	createInstance: timbre.bindings.generated_types.basis_zig_EventDescription_createInstance_cb,
	getParameterIndex: timbre.bindings.generated_types.basis_zig_EventDescription_getParameterIndex_cb,
	getLength: timbre.bindings.generated_types.basis_zig_EventDescription_getLength_cb,
) void {
	timbre.bindings.generated_function_pointers._EventDescription_createInstance = createInstance;
	timbre.bindings.generated_function_pointers._EventDescription_getParameterIndex = getParameterIndex;
	timbre.bindings.generated_function_pointers._EventDescription_getLength = getLength;
}

// ===============================

// class EventInstance

export fn bindEventInstance(
	release: timbre.bindings.generated_types.basis_zig_EventInstance_release_cb,
	releaseWhenFinished: timbre.bindings.generated_types.basis_zig_EventInstance_releaseWhenFinished_cb,
	releaseAfterFadeOut: timbre.bindings.generated_types.basis_zig_EventInstance_releaseAfterFadeOut_cb,
	getState: timbre.bindings.generated_types.basis_zig_EventInstance_getState_cb,
	start: timbre.bindings.generated_types.basis_zig_EventInstance_start_cb,
	pause: timbre.bindings.generated_types.basis_zig_EventInstance_pause_cb,
	stop: timbre.bindings.generated_types.basis_zig_EventInstance_stop_cb,
	setParameterByName: timbre.bindings.generated_types.basis_zig_EventInstance_setParameterByName_cb,
	setParameterByIndex: timbre.bindings.generated_types.basis_zig_EventInstance_setParameterByIndex_cb,
	set3DParameters: timbre.bindings.generated_types.basis_zig_EventInstance_set3DParameters_cb,
	sendSignal: timbre.bindings.generated_types.basis_zig_EventInstance_sendSignal_cb,
	fadeIn: timbre.bindings.generated_types.basis_zig_EventInstance_fadeIn_cb,
) void {
	timbre.bindings.generated_function_pointers._EventInstance_release = release;
	timbre.bindings.generated_function_pointers._EventInstance_releaseWhenFinished = releaseWhenFinished;
	timbre.bindings.generated_function_pointers._EventInstance_releaseAfterFadeOut = releaseAfterFadeOut;
	timbre.bindings.generated_function_pointers._EventInstance_getState = getState;
	timbre.bindings.generated_function_pointers._EventInstance_start = start;
	timbre.bindings.generated_function_pointers._EventInstance_pause = pause;
	timbre.bindings.generated_function_pointers._EventInstance_stop = stop;
	timbre.bindings.generated_function_pointers._EventInstance_setParameterByName = setParameterByName;
	timbre.bindings.generated_function_pointers._EventInstance_setParameterByIndex = setParameterByIndex;
	timbre.bindings.generated_function_pointers._EventInstance_set3DParameters = set3DParameters;
	timbre.bindings.generated_function_pointers._EventInstance_sendSignal = sendSignal;
	timbre.bindings.generated_function_pointers._EventInstance_fadeIn = fadeIn;
}

// ===============================

