// ----------------------------------------------------
// Copyright (c) 2018-2025 Madrigal Ltd.
// This file is part of the Basis SDK, and is subject to the
// terms and conditions of the Basis SDK License Agreement.
// https://www.madrigalgames.com
// ----------------------------------------------------

// This file was generated by Sir Bindalot, the binding generator. Ne pas toucher!

const basis = @import("basis");
const trampoline = @import("../trampoline.zig");

// class Localization

export fn bindLocalization(
	isValidLocalizationKey: trampoline.bindings.generated_types.basis_zig_Localization_isValidLocalizationKey_cb,
	getLocalizedStringByName: trampoline.bindings.generated_types.basis_zig_Localization_getLocalizedStringByName_cb,
	getLocalizedStringByNameWithParams1: trampoline.bindings.generated_types.basis_zig_Localization_getLocalizedStringByNameWithParams1_cb,
	getLocalizedStringByNameWithParams2: trampoline.bindings.generated_types.basis_zig_Localization_getLocalizedStringByNameWithParams2_cb,
	getLocalizedStringByNameWithParams3: trampoline.bindings.generated_types.basis_zig_Localization_getLocalizedStringByNameWithParams3_cb,
	getLocalizedVec2ByName: trampoline.bindings.generated_types.basis_zig_Localization_getLocalizedVec2ByName_cb,
	setUILanguage: trampoline.bindings.generated_types.basis_zig_Localization_setUILanguage_cb,
) void {
	trampoline.bindings.generated_function_pointers._Localization_isValidLocalizationKey = isValidLocalizationKey;
	trampoline.bindings.generated_function_pointers._Localization_getLocalizedStringByName = getLocalizedStringByName;
	trampoline.bindings.generated_function_pointers._Localization_getLocalizedStringByNameWithParams1 = getLocalizedStringByNameWithParams1;
	trampoline.bindings.generated_function_pointers._Localization_getLocalizedStringByNameWithParams2 = getLocalizedStringByNameWithParams2;
	trampoline.bindings.generated_function_pointers._Localization_getLocalizedStringByNameWithParams3 = getLocalizedStringByNameWithParams3;
	trampoline.bindings.generated_function_pointers._Localization_getLocalizedVec2ByName = getLocalizedVec2ByName;
	trampoline.bindings.generated_function_pointers._Localization_setUILanguage = setUILanguage;
}

// ===============================

// class MainLib

export fn bindMainLib(
	MainLib_callU64: trampoline.bindings.generated_types.basis_zig_MainLib_MainLib_callU64_cb,
) void {
	trampoline.bindings.generated_function_pointers._MainLib_MainLib_callU64 = MainLib_callU64;
}

// ===============================

// class TimbreUtils

export fn bindTimbreUtils(
	loadAdditiveProject: trampoline.bindings.generated_types.basis_zig_TimbreUtils_loadAdditiveProject_cb,
) void {
	trampoline.bindings.generated_function_pointers._TimbreUtils_loadAdditiveProject = loadAdditiveProject;
}

// ===============================

