// ----------------------------------------------------
// Copyright (c) 2018-2025 Madrigal Ltd.
// This file is part of the Basis SDK, and is subject to the
// terms and conditions of the Basis SDK License Agreement.
// https://www.madrigalgames.com
// ----------------------------------------------------

// This file was generated by Sir Bindalot, the binding generator. Ne pas toucher!

const basis = @import("basis");
const trampoline = @import("../trampoline.zig");

// class Localization

pub const basis_zig_Localization_isValidLocalizationKey_cb = *const fn ([*c]const basis.bindings.InteropString) callconv(.c) bool;
pub const basis_zig_Localization_getLocalizedStringByName_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_Localization_getLocalizedStringByNameWithParams1_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, [*c]basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_Localization_getLocalizedStringByNameWithParams2_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, [*c]basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_Localization_getLocalizedStringByNameWithParams3_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString, [*c]basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_Localization_getLocalizedVec2ByName_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]basis.bindings.InteropVec2) callconv(.c) void;
pub const basis_zig_Localization_setUILanguage_cb = *const fn (c_int) callconv(.c) void;

// ===============================

// class MainLib

pub const basis_zig_MainLib_MainLib_callU64_cb = *const fn (u64, u64) callconv(.c) u64;

// ===============================

// class TimbreUtils

pub const basis_zig_TimbreUtils_loadAdditiveProject_cb = *const fn ([*c]const u8, u32) callconv(.c) void;

// ===============================

