// ----------------------------------------------------
// Copyright (c) 2018-2026 Madrigal Ltd.
// This file is part of the Basis SDK, and is subject to the
// terms and conditions of the Basis SDK License Agreement.
// https://www.madrigalgames.com
// ----------------------------------------------------

// This file was generated by Sir Bindalot, the binding generator. Ne pas toucher!

const basis = @import("basis");
const trampoline = @import("../trampoline.zig");

// class Localization

pub var _Localization_isValidLocalizationKey: trampoline.bindings.generated_types.basis_zig_Localization_isValidLocalizationKey_cb = undefined;
pub var _Localization_getLocalizedStringByName: trampoline.bindings.generated_types.basis_zig_Localization_getLocalizedStringByName_cb = undefined;
pub var _Localization_getLocalizedStringByNameWithParams1: trampoline.bindings.generated_types.basis_zig_Localization_getLocalizedStringByNameWithParams1_cb = undefined;
pub var _Localization_getLocalizedStringByNameWithParams2: trampoline.bindings.generated_types.basis_zig_Localization_getLocalizedStringByNameWithParams2_cb = undefined;
pub var _Localization_getLocalizedStringByNameWithParams3: trampoline.bindings.generated_types.basis_zig_Localization_getLocalizedStringByNameWithParams3_cb = undefined;
pub var _Localization_getLocalizedVec2ByName: trampoline.bindings.generated_types.basis_zig_Localization_getLocalizedVec2ByName_cb = undefined;
pub var _Localization_setUILanguage: trampoline.bindings.generated_types.basis_zig_Localization_setUILanguage_cb = undefined;
pub var _Localization_getUILanguage: trampoline.bindings.generated_types.basis_zig_Localization_getUILanguage_cb = undefined;

// ===============================

// class MainLib

pub var _MainLib_MainLib_callU64: trampoline.bindings.generated_types.basis_zig_MainLib_MainLib_callU64_cb = undefined;

// ===============================

// class TimbreUtils

pub var _TimbreUtils_loadAdditiveProject: trampoline.bindings.generated_types.basis_zig_TimbreUtils_loadAdditiveProject_cb = undefined;

// ===============================

