// ----------------------------------------------------
// Copyright (c) 2018-2026 Madrigal Ltd.
// This file is part of the Basis SDK, and is subject to the
// terms and conditions of the Basis SDK License Agreement.
// https://www.madrigalgames.com
// ----------------------------------------------------

// This file was generated by Sir Bindalot, the binding generator. Ne pas toucher!

const basis = @import("basis");
const goofy = @import("../goofy.zig");

// class GoofyManager

pub var _GoofyManager_setAspectRatio: goofy.bindings.generated_types.basis_zig_GoofyManager_setAspectRatio_cb = undefined;
pub var _GoofyManager_setFitMode: goofy.bindings.generated_types.basis_zig_GoofyManager_setFitMode_cb = undefined;
pub var _GoofyManager_createView: goofy.bindings.generated_types.basis_zig_GoofyManager_createView_cb = undefined;
pub var _GoofyManager_createViewWithScript: goofy.bindings.generated_types.basis_zig_GoofyManager_createViewWithScript_cb = undefined;
pub var _GoofyManager_destroyView: goofy.bindings.generated_types.basis_zig_GoofyManager_destroyView_cb = undefined;
pub var _GoofyManager_pushViewOntoStack: goofy.bindings.generated_types.basis_zig_GoofyManager_pushViewOntoStack_cb = undefined;
pub var _GoofyManager_pushModalViewOntoStack: goofy.bindings.generated_types.basis_zig_GoofyManager_pushModalViewOntoStack_cb = undefined;
pub var _GoofyManager_removeViewFromStack: goofy.bindings.generated_types.basis_zig_GoofyManager_removeViewFromStack_cb = undefined;
pub var _GoofyManager_clearViewStack: goofy.bindings.generated_types.basis_zig_GoofyManager_clearViewStack_cb = undefined;
pub var _GoofyManager_createFont: goofy.bindings.generated_types.basis_zig_GoofyManager_createFont_cb = undefined;
pub var _GoofyManager_registerAction: goofy.bindings.generated_types.basis_zig_GoofyManager_registerAction_cb = undefined;
pub var _GoofyManager_fireAction: goofy.bindings.generated_types.basis_zig_GoofyManager_fireAction_cb = undefined;
pub var _GoofyManager_setActionCallback: goofy.bindings.generated_types.basis_zig_GoofyManager_setActionCallback_cb = undefined;
pub var _GoofyManager_clearActionCallback: goofy.bindings.generated_types.basis_zig_GoofyManager_clearActionCallback_cb = undefined;
pub var _GoofyManager_registerProperty: goofy.bindings.generated_types.basis_zig_GoofyManager_registerProperty_cb = undefined;
pub var _GoofyManager_getPropertyType: goofy.bindings.generated_types.basis_zig_GoofyManager_getPropertyType_cb = undefined;
pub var _GoofyManager_getPropertyValue: goofy.bindings.generated_types.basis_zig_GoofyManager_getPropertyValue_cb = undefined;
pub var _GoofyManager_setPropertyValue: goofy.bindings.generated_types.basis_zig_GoofyManager_setPropertyValue_cb = undefined;
pub var _GoofyManager_registerStringProperty: goofy.bindings.generated_types.basis_zig_GoofyManager_registerStringProperty_cb = undefined;
pub var _GoofyManager_getStringPropertyValue: goofy.bindings.generated_types.basis_zig_GoofyManager_getStringPropertyValue_cb = undefined;
pub var _GoofyManager_setStringPropertyValue: goofy.bindings.generated_types.basis_zig_GoofyManager_setStringPropertyValue_cb = undefined;
pub var _GoofyManager_setZigEventHandlingEnabled: goofy.bindings.generated_types.basis_zig_GoofyManager_setZigEventHandlingEnabled_cb = undefined;
pub var _GoofyManager_setPeripheryColor: goofy.bindings.generated_types.basis_zig_GoofyManager_setPeripheryColor_cb = undefined;
pub var _GoofyManager_clearPeripheryColor: goofy.bindings.generated_types.basis_zig_GoofyManager_clearPeripheryColor_cb = undefined;
pub var _GoofyManager_getNVGcontext: goofy.bindings.generated_types.basis_zig_GoofyManager_getNVGcontext_cb = undefined;
pub var _GoofyManager_getUIPosFromPixelPos: goofy.bindings.generated_types.basis_zig_GoofyManager_getUIPosFromPixelPos_cb = undefined;

// ===============================

// class GoofySkins

pub var _GoofySkins_registerSkin: goofy.bindings.generated_types.basis_zig_GoofySkins_registerSkin_cb = undefined;
pub var _GoofySkins_setButtonRenderCallback: goofy.bindings.generated_types.basis_zig_GoofySkins_setButtonRenderCallback_cb = undefined;
pub var _GoofySkins_setSpinBoxRenderCallback: goofy.bindings.generated_types.basis_zig_GoofySkins_setSpinBoxRenderCallback_cb = undefined;

// ===============================

// class NanoVG

pub var _NanoVG_nvgSave: goofy.bindings.generated_types.basis_zig_NanoVG_nvgSave_cb = undefined;
pub var _NanoVG_nvgRestore: goofy.bindings.generated_types.basis_zig_NanoVG_nvgRestore_cb = undefined;
pub var _NanoVG_nvgReset: goofy.bindings.generated_types.basis_zig_NanoVG_nvgReset_cb = undefined;
pub var _NanoVG_nvgShapeAntiAlias: goofy.bindings.generated_types.basis_zig_NanoVG_nvgShapeAntiAlias_cb = undefined;
pub var _NanoVG_nvgStrokeColor: goofy.bindings.generated_types.basis_zig_NanoVG_nvgStrokeColor_cb = undefined;
pub var _NanoVG_nvgStrokePaint: goofy.bindings.generated_types.basis_zig_NanoVG_nvgStrokePaint_cb = undefined;
pub var _NanoVG_nvgFillColor: goofy.bindings.generated_types.basis_zig_NanoVG_nvgFillColor_cb = undefined;
pub var _NanoVG_nvgFillPaint: goofy.bindings.generated_types.basis_zig_NanoVG_nvgFillPaint_cb = undefined;
pub var _NanoVG_nvgMiterLimit: goofy.bindings.generated_types.basis_zig_NanoVG_nvgMiterLimit_cb = undefined;
pub var _NanoVG_nvgStrokeWidth: goofy.bindings.generated_types.basis_zig_NanoVG_nvgStrokeWidth_cb = undefined;
pub var _NanoVG_nvgLineCap: goofy.bindings.generated_types.basis_zig_NanoVG_nvgLineCap_cb = undefined;
pub var _NanoVG_nvgLineJoin: goofy.bindings.generated_types.basis_zig_NanoVG_nvgLineJoin_cb = undefined;
pub var _NanoVG_nvgGlobalAlpha: goofy.bindings.generated_types.basis_zig_NanoVG_nvgGlobalAlpha_cb = undefined;
pub var _NanoVG_nvgResetTransform: goofy.bindings.generated_types.basis_zig_NanoVG_nvgResetTransform_cb = undefined;
pub var _NanoVG_nvgTransform: goofy.bindings.generated_types.basis_zig_NanoVG_nvgTransform_cb = undefined;
pub var _NanoVG_nvgTranslate: goofy.bindings.generated_types.basis_zig_NanoVG_nvgTranslate_cb = undefined;
pub var _NanoVG_nvgRotate: goofy.bindings.generated_types.basis_zig_NanoVG_nvgRotate_cb = undefined;
pub var _NanoVG_nvgSkewX: goofy.bindings.generated_types.basis_zig_NanoVG_nvgSkewX_cb = undefined;
pub var _NanoVG_nvgSkewY: goofy.bindings.generated_types.basis_zig_NanoVG_nvgSkewY_cb = undefined;
pub var _NanoVG_nvgScale: goofy.bindings.generated_types.basis_zig_NanoVG_nvgScale_cb = undefined;
pub var _NanoVG_nvgCurrentTransform: goofy.bindings.generated_types.basis_zig_NanoVG_nvgCurrentTransform_cb = undefined;
pub var _NanoVG_nvgScissor: goofy.bindings.generated_types.basis_zig_NanoVG_nvgScissor_cb = undefined;
pub var _NanoVG_nvgIntersectScissor: goofy.bindings.generated_types.basis_zig_NanoVG_nvgIntersectScissor_cb = undefined;
pub var _NanoVG_nvgResetScissor: goofy.bindings.generated_types.basis_zig_NanoVG_nvgResetScissor_cb = undefined;
pub var _NanoVG_nvgBeginPath: goofy.bindings.generated_types.basis_zig_NanoVG_nvgBeginPath_cb = undefined;
pub var _NanoVG_nvgMoveTo: goofy.bindings.generated_types.basis_zig_NanoVG_nvgMoveTo_cb = undefined;
pub var _NanoVG_nvgLineTo: goofy.bindings.generated_types.basis_zig_NanoVG_nvgLineTo_cb = undefined;
pub var _NanoVG_nvgBezierTo: goofy.bindings.generated_types.basis_zig_NanoVG_nvgBezierTo_cb = undefined;
pub var _NanoVG_nvgQuadTo: goofy.bindings.generated_types.basis_zig_NanoVG_nvgQuadTo_cb = undefined;
pub var _NanoVG_nvgArcTo: goofy.bindings.generated_types.basis_zig_NanoVG_nvgArcTo_cb = undefined;
pub var _NanoVG_nvgClosePath: goofy.bindings.generated_types.basis_zig_NanoVG_nvgClosePath_cb = undefined;
pub var _NanoVG_nvgPathWinding: goofy.bindings.generated_types.basis_zig_NanoVG_nvgPathWinding_cb = undefined;
pub var _NanoVG_nvgArc: goofy.bindings.generated_types.basis_zig_NanoVG_nvgArc_cb = undefined;
pub var _NanoVG_nvgRect: goofy.bindings.generated_types.basis_zig_NanoVG_nvgRect_cb = undefined;
pub var _NanoVG_nvgRoundedRect: goofy.bindings.generated_types.basis_zig_NanoVG_nvgRoundedRect_cb = undefined;
pub var _NanoVG_nvgRoundedRectVarying: goofy.bindings.generated_types.basis_zig_NanoVG_nvgRoundedRectVarying_cb = undefined;
pub var _NanoVG_nvgEllipse: goofy.bindings.generated_types.basis_zig_NanoVG_nvgEllipse_cb = undefined;
pub var _NanoVG_nvgCircle: goofy.bindings.generated_types.basis_zig_NanoVG_nvgCircle_cb = undefined;
pub var _NanoVG_nvgFill: goofy.bindings.generated_types.basis_zig_NanoVG_nvgFill_cb = undefined;
pub var _NanoVG_nvgStroke: goofy.bindings.generated_types.basis_zig_NanoVG_nvgStroke_cb = undefined;
pub var _NanoVG_nvgFindFont: goofy.bindings.generated_types.basis_zig_NanoVG_nvgFindFont_cb = undefined;
pub var _NanoVG_nvgFontSize: goofy.bindings.generated_types.basis_zig_NanoVG_nvgFontSize_cb = undefined;
pub var _NanoVG_nvgFontBlur: goofy.bindings.generated_types.basis_zig_NanoVG_nvgFontBlur_cb = undefined;
pub var _NanoVG_nvgTextLetterSpacing: goofy.bindings.generated_types.basis_zig_NanoVG_nvgTextLetterSpacing_cb = undefined;
pub var _NanoVG_nvgTextLineHeight: goofy.bindings.generated_types.basis_zig_NanoVG_nvgTextLineHeight_cb = undefined;
pub var _NanoVG_nvgTextAlign: goofy.bindings.generated_types.basis_zig_NanoVG_nvgTextAlign_cb = undefined;
pub var _NanoVG_nvgFontFaceId: goofy.bindings.generated_types.basis_zig_NanoVG_nvgFontFaceId_cb = undefined;
pub var _NanoVG_nvgFontFace: goofy.bindings.generated_types.basis_zig_NanoVG_nvgFontFace_cb = undefined;
pub var _NanoVG_nvgText: goofy.bindings.generated_types.basis_zig_NanoVG_nvgText_cb = undefined;
pub var _NanoVG_nvgTextBox: goofy.bindings.generated_types.basis_zig_NanoVG_nvgTextBox_cb = undefined;
pub var _NanoVG_nvgTextBounds: goofy.bindings.generated_types.basis_zig_NanoVG_nvgTextBounds_cb = undefined;
pub var _NanoVG_nvgTextMetrics: goofy.bindings.generated_types.basis_zig_NanoVG_nvgTextMetrics_cb = undefined;
pub var _NanoVG_nvgTextSubset: goofy.bindings.generated_types.basis_zig_NanoVG_nvgTextSubset_cb = undefined;
pub var _NanoVG_nvgTextBoxSubset: goofy.bindings.generated_types.basis_zig_NanoVG_nvgTextBoxSubset_cb = undefined;
pub var _NanoVG_nvgTextCountRows: goofy.bindings.generated_types.basis_zig_NanoVG_nvgTextCountRows_cb = undefined;
pub var _NanoVG_nvgCreateImageFromTextureResource: goofy.bindings.generated_types.basis_zig_NanoVG_nvgCreateImageFromTextureResource_cb = undefined;
pub var _NanoVG_nvgImageSize: goofy.bindings.generated_types.basis_zig_NanoVG_nvgImageSize_cb = undefined;
pub var _NanoVG_nvgDeleteImage: goofy.bindings.generated_types.basis_zig_NanoVG_nvgDeleteImage_cb = undefined;
pub var _NanoVG_nvgSetIGNAmount: goofy.bindings.generated_types.basis_zig_NanoVG_nvgSetIGNAmount_cb = undefined;

// ===============================

// class GoofyUIView

pub var _GoofyUIView_getWidget: goofy.bindings.generated_types.basis_zig_GoofyUIView_getWidget_cb = undefined;
pub var _GoofyUIView_requestFocusChange: goofy.bindings.generated_types.basis_zig_GoofyUIView_requestFocusChange_cb = undefined;
pub var _GoofyUIView_setRecreationCallbackEnabled: goofy.bindings.generated_types.basis_zig_GoofyUIView_setRecreationCallbackEnabled_cb = undefined;
pub var _GoofyUIView_setRaiseNavDirEvents: goofy.bindings.generated_types.basis_zig_GoofyUIView_setRaiseNavDirEvents_cb = undefined;
pub var _GoofyUIView_setRaiseMouseEvents: goofy.bindings.generated_types.basis_zig_GoofyUIView_setRaiseMouseEvents_cb = undefined;

// ===============================

// class GoofyUIWidget

pub var _GoofyUIWidget_getName: goofy.bindings.generated_types.basis_zig_GoofyUIWidget_getName_cb = undefined;
pub var _GoofyUIWidget_setPosition: goofy.bindings.generated_types.basis_zig_GoofyUIWidget_setPosition_cb = undefined;
pub var _GoofyUIWidget_getPosition: goofy.bindings.generated_types.basis_zig_GoofyUIWidget_getPosition_cb = undefined;
pub var _GoofyUIWidget_setSize: goofy.bindings.generated_types.basis_zig_GoofyUIWidget_setSize_cb = undefined;
pub var _GoofyUIWidget_getSize: goofy.bindings.generated_types.basis_zig_GoofyUIWidget_getSize_cb = undefined;
pub var _GoofyUIWidget_setVisible: goofy.bindings.generated_types.basis_zig_GoofyUIWidget_setVisible_cb = undefined;
pub var _GoofyUIWidget_isVisible: goofy.bindings.generated_types.basis_zig_GoofyUIWidget_isVisible_cb = undefined;
pub var _GoofyUIWidget_setEnabled: goofy.bindings.generated_types.basis_zig_GoofyUIWidget_setEnabled_cb = undefined;
pub var _GoofyUIWidget_isEnabled: goofy.bindings.generated_types.basis_zig_GoofyUIWidget_isEnabled_cb = undefined;

// ===============================

// class GoofyUILabel

pub var _GoofyUILabel_setRawText: goofy.bindings.generated_types.basis_zig_GoofyUILabel_setRawText_cb = undefined;
pub var _GoofyUILabel_setLocalizedText: goofy.bindings.generated_types.basis_zig_GoofyUILabel_setLocalizedText_cb = undefined;
pub var _GoofyUILabel_setColor: goofy.bindings.generated_types.basis_zig_GoofyUILabel_setColor_cb = undefined;
pub var _GoofyUILabel_getColor: goofy.bindings.generated_types.basis_zig_GoofyUILabel_getColor_cb = undefined;

// ===============================

// class GoofyUIButton

pub var _GoofyUIButton_setRawText: goofy.bindings.generated_types.basis_zig_GoofyUIButton_setRawText_cb = undefined;
pub var _GoofyUIButton_setLocalizedText: goofy.bindings.generated_types.basis_zig_GoofyUIButton_setLocalizedText_cb = undefined;

// ===============================

// class GoofyUICanvas

pub var _GoofyUICanvas_setRenderCallbackEnabled: goofy.bindings.generated_types.basis_zig_GoofyUICanvas_setRenderCallbackEnabled_cb = undefined;
pub var _GoofyUICanvas_getUserData: goofy.bindings.generated_types.basis_zig_GoofyUICanvas_getUserData_cb = undefined;

// ===============================

// class GoofyUIImageBox

pub var _GoofyUIImageBox_play: goofy.bindings.generated_types.basis_zig_GoofyUIImageBox_play_cb = undefined;
pub var _GoofyUIImageBox_pause: goofy.bindings.generated_types.basis_zig_GoofyUIImageBox_pause_cb = undefined;
pub var _GoofyUIImageBox_stop: goofy.bindings.generated_types.basis_zig_GoofyUIImageBox_stop_cb = undefined;
pub var _GoofyUIImageBox_jumpToEnd: goofy.bindings.generated_types.basis_zig_GoofyUIImageBox_jumpToEnd_cb = undefined;

// ===============================

// class GoofyUISpinBox

pub var _GoofyUISpinBox_addItem: goofy.bindings.generated_types.basis_zig_GoofyUISpinBox_addItem_cb = undefined;
pub var _GoofyUISpinBox_clearItems: goofy.bindings.generated_types.basis_zig_GoofyUISpinBox_clearItems_cb = undefined;
pub var _GoofyUISpinBox_setSelectedValue: goofy.bindings.generated_types.basis_zig_GoofyUISpinBox_setSelectedValue_cb = undefined;
pub var _GoofyUISpinBox_getSelectedValue: goofy.bindings.generated_types.basis_zig_GoofyUISpinBox_getSelectedValue_cb = undefined;

// ===============================

// class GoofyUIUserWidget

pub var _GoofyUIUserWidget_setRenderCallbackEnabled: goofy.bindings.generated_types.basis_zig_GoofyUIUserWidget_setRenderCallbackEnabled_cb = undefined;
pub var _GoofyUIUserWidget_setEventCallbackEnabled: goofy.bindings.generated_types.basis_zig_GoofyUIUserWidget_setEventCallbackEnabled_cb = undefined;
pub var _GoofyUIUserWidget_getUserData: goofy.bindings.generated_types.basis_zig_GoofyUIUserWidget_getUserData_cb = undefined;

// ===============================

// class GoofySVGImage

pub var _GoofySVGImage_newImage: goofy.bindings.generated_types.basis_zig_GoofySVGImage_newImage_cb = undefined;
pub var _GoofySVGImage_deleteImage: goofy.bindings.generated_types.basis_zig_GoofySVGImage_deleteImage_cb = undefined;
pub var _GoofySVGImage_getWidth: goofy.bindings.generated_types.basis_zig_GoofySVGImage_getWidth_cb = undefined;
pub var _GoofySVGImage_getHeight: goofy.bindings.generated_types.basis_zig_GoofySVGImage_getHeight_cb = undefined;
pub var _GoofySVGImage_loadImage: goofy.bindings.generated_types.basis_zig_GoofySVGImage_loadImage_cb = undefined;
pub var _GoofySVGImage_render: goofy.bindings.generated_types.basis_zig_GoofySVGImage_render_cb = undefined;
pub var _GoofySVGImage_renderUnstretched: goofy.bindings.generated_types.basis_zig_GoofySVGImage_renderUnstretched_cb = undefined;
pub var _GoofySVGImage_renderInPixelRect: goofy.bindings.generated_types.basis_zig_GoofySVGImage_renderInPixelRect_cb = undefined;

// ===============================

// class GoofySVGAnimationPlayer

pub var _GoofySVGAnimationPlayer_newPlayer: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_newPlayer_cb = undefined;
pub var _GoofySVGAnimationPlayer_deletePlayer: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_deletePlayer_cb = undefined;
pub var _GoofySVGAnimationPlayer_getWidth: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_getWidth_cb = undefined;
pub var _GoofySVGAnimationPlayer_getHeight: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_getHeight_cb = undefined;
pub var _GoofySVGAnimationPlayer_setDeltaTimeLimitEnabled: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_setDeltaTimeLimitEnabled_cb = undefined;
pub var _GoofySVGAnimationPlayer_loadAnimation: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_loadAnimation_cb = undefined;
pub var _GoofySVGAnimationPlayer_render: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_render_cb = undefined;
pub var _GoofySVGAnimationPlayer_renderUnstretched: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_renderUnstretched_cb = undefined;
pub var _GoofySVGAnimationPlayer_play: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_play_cb = undefined;
pub var _GoofySVGAnimationPlayer_pause: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_pause_cb = undefined;
pub var _GoofySVGAnimationPlayer_stop: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_stop_cb = undefined;
pub var _GoofySVGAnimationPlayer_jumpToEnd: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_jumpToEnd_cb = undefined;
pub var _GoofySVGAnimationPlayer_setLooping: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_setLooping_cb = undefined;
pub var _GoofySVGAnimationPlayer_update: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_update_cb = undefined;
pub var _GoofySVGAnimationPlayer_getState: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_getState_cb = undefined;
pub var _GoofySVGAnimationPlayer_getCurrentTime: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_getCurrentTime_cb = undefined;
pub var _GoofySVGAnimationPlayer_setCurrentTime: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_setCurrentTime_cb = undefined;

// ===============================

