// ----------------------------------------------------
// Copyright (c) 2018-2025 Madrigal Ltd.
// This file is part of the Basis SDK, and is subject to the
// terms and conditions of the Basis SDK License Agreement.
// https://www.madrigalgames.com
// ----------------------------------------------------

// This file was generated by Sir Bindalot, the binding generator. Ne pas toucher!

const basis = @import("basis");
const goofy = @import("../goofy.zig");

// class GoofyManager

pub const basis_zig_GoofyManager_setAspectRatio_cb = *const fn (f32) callconv(.c) void;
pub const basis_zig_GoofyManager_setFitMode_cb = *const fn (u32) callconv(.c) void;
pub const basis_zig_GoofyManager_createView_cb = *const fn ([*c]const basis.bindings.InteropString) callconv(.c) u64;
pub const basis_zig_GoofyManager_createViewWithScript_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString) callconv(.c) u64;
pub const basis_zig_GoofyManager_destroyView_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_GoofyManager_pushViewOntoStack_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_GoofyManager_pushModalViewOntoStack_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_GoofyManager_removeViewFromStack_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_GoofyManager_clearViewStack_cb = *const fn () callconv(.c) void;
pub const basis_zig_GoofyManager_createFont_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString) callconv(.c) c_int;
pub const basis_zig_GoofyManager_registerAction_cb = *const fn ([*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_GoofyManager_fireAction_cb = *const fn ([*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_GoofyManager_setActionCallback_cb = *const fn ([*c]const basis.bindings.InteropString, basis.bindings.FP_void) callconv(.c) void;
pub const basis_zig_GoofyManager_clearActionCallback_cb = *const fn ([*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_GoofyManager_registerProperty_cb = *const fn ([*c]const basis.bindings.InteropString, c_int, [*c]const u8, u32) callconv(.c) void;
pub const basis_zig_GoofyManager_getPropertyType_cb = *const fn ([*c]const basis.bindings.InteropString) callconv(.c) c_int;
pub const basis_zig_GoofyManager_getPropertyValue_cb = *const fn ([*c]const basis.bindings.InteropString, c_int, [*c]u8, u32) callconv(.c) void;
pub const basis_zig_GoofyManager_setPropertyValue_cb = *const fn ([*c]const basis.bindings.InteropString, c_int, [*c]const u8, u32) callconv(.c) void;
pub const basis_zig_GoofyManager_registerStringProperty_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_GoofyManager_getStringPropertyValue_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_GoofyManager_setStringPropertyValue_cb = *const fn ([*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_GoofyManager_setZigEventHandlingEnabled_cb = *const fn (c_int) callconv(.c) void;
pub const basis_zig_GoofyManager_setPeripheryColor_cb = *const fn ([*c]const basis.bindings.InteropColor, c_int) callconv(.c) void;
pub const basis_zig_GoofyManager_clearPeripheryColor_cb = *const fn () callconv(.c) void;
pub const basis_zig_GoofyManager_getNVGcontext_cb = *const fn () callconv(.c) u64;
pub const basis_zig_GoofyManager_getUIPosFromPixelPos_cb = *const fn ([*c]const basis.bindings.InteropVec2, [*c]basis.bindings.InteropVec2) callconv(.c) void;

// ===============================

// class GoofySkins

pub const basis_zig_GoofySkins_registerSkin_cb = *const fn ([*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_GoofySkins_setButtonRenderCallback_cb = *const fn ([*c]const basis.bindings.InteropString, goofy.bindings.InteropButtonRenderCallback) callconv(.c) void;
pub const basis_zig_GoofySkins_setSpinBoxRenderCallback_cb = *const fn ([*c]const basis.bindings.InteropString, goofy.bindings.InteropSpinBoxRenderCallback) callconv(.c) void;

// ===============================

// class NanoVG

pub const basis_zig_NanoVG_nvgSave_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_NanoVG_nvgRestore_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_NanoVG_nvgReset_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_NanoVG_nvgShapeAntiAlias_cb = *const fn (u64, c_int) callconv(.c) void;
pub const basis_zig_NanoVG_nvgStrokeColor_cb = *const fn (u64, [*c]const basis.bindings.InteropColor) callconv(.c) void;
pub const basis_zig_NanoVG_nvgStrokePaint_cb = *const fn (u64, [*c]const goofy.bindings.InteropPaint) callconv(.c) void;
pub const basis_zig_NanoVG_nvgFillColor_cb = *const fn (u64, [*c]const basis.bindings.InteropColor) callconv(.c) void;
pub const basis_zig_NanoVG_nvgFillPaint_cb = *const fn (u64, [*c]const goofy.bindings.InteropPaint) callconv(.c) void;
pub const basis_zig_NanoVG_nvgMiterLimit_cb = *const fn (u64, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgStrokeWidth_cb = *const fn (u64, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgLineCap_cb = *const fn (u64, c_int) callconv(.c) void;
pub const basis_zig_NanoVG_nvgLineJoin_cb = *const fn (u64, c_int) callconv(.c) void;
pub const basis_zig_NanoVG_nvgGlobalAlpha_cb = *const fn (u64, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgResetTransform_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_NanoVG_nvgTransform_cb = *const fn (u64, f32, f32, f32, f32, f32, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgTranslate_cb = *const fn (u64, f32, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgRotate_cb = *const fn (u64, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgSkewX_cb = *const fn (u64, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgSkewY_cb = *const fn (u64, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgScale_cb = *const fn (u64, f32, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgCurrentTransform_cb = *const fn (u64, [*c]f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgScissor_cb = *const fn (u64, f32, f32, f32, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgIntersectScissor_cb = *const fn (u64, f32, f32, f32, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgResetScissor_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_NanoVG_nvgBeginPath_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_NanoVG_nvgMoveTo_cb = *const fn (u64, f32, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgLineTo_cb = *const fn (u64, f32, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgBezierTo_cb = *const fn (u64, f32, f32, f32, f32, f32, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgQuadTo_cb = *const fn (u64, f32, f32, f32, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgArcTo_cb = *const fn (u64, f32, f32, f32, f32, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgClosePath_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_NanoVG_nvgPathWinding_cb = *const fn (u64, c_int) callconv(.c) void;
pub const basis_zig_NanoVG_nvgArc_cb = *const fn (u64, f32, f32, f32, f32, f32, c_int) callconv(.c) void;
pub const basis_zig_NanoVG_nvgRect_cb = *const fn (u64, f32, f32, f32, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgRoundedRect_cb = *const fn (u64, f32, f32, f32, f32, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgRoundedRectVarying_cb = *const fn (u64, f32, f32, f32, f32, f32, f32, f32, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgEllipse_cb = *const fn (u64, f32, f32, f32, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgCircle_cb = *const fn (u64, f32, f32, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgFill_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_NanoVG_nvgStroke_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_NanoVG_nvgFindFont_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) c_int;
pub const basis_zig_NanoVG_nvgFontSize_cb = *const fn (u64, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgFontBlur_cb = *const fn (u64, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgTextLetterSpacing_cb = *const fn (u64, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgTextLineHeight_cb = *const fn (u64, f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgTextAlign_cb = *const fn (u64, c_int) callconv(.c) void;
pub const basis_zig_NanoVG_nvgFontFaceId_cb = *const fn (u64, c_int) callconv(.c) void;
pub const basis_zig_NanoVG_nvgFontFace_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_NanoVG_nvgText_cb = *const fn (u64, f32, f32, [*c]const basis.bindings.InteropString) callconv(.c) f32;
pub const basis_zig_NanoVG_nvgTextBox_cb = *const fn (u64, f32, f32, f32, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_NanoVG_nvgTextBounds_cb = *const fn (u64, f32, f32, [*c]const basis.bindings.InteropString, [*c]f32) callconv(.c) f32;
pub const basis_zig_NanoVG_nvgTextMetrics_cb = *const fn (u64, [*c]f32, [*c]f32, [*c]f32) callconv(.c) void;
pub const basis_zig_NanoVG_nvgTextSubset_cb = *const fn (u64, f32, f32, [*c]const basis.bindings.InteropString, c_int, c_int) callconv(.c) f32;
pub const basis_zig_NanoVG_nvgTextBoxSubset_cb = *const fn (u64, f32, f32, f32, [*c]const basis.bindings.InteropString, c_int, c_int) callconv(.c) void;
pub const basis_zig_NanoVG_nvgTextCountRows_cb = *const fn (u64, [*c]const basis.bindings.InteropString, f32) callconv(.c) c_int;
pub const basis_zig_NanoVG_nvgCreateImageFromTextureResource_cb = *const fn (u64, u64, c_int) callconv(.c) c_int;
pub const basis_zig_NanoVG_nvgImageSize_cb = *const fn (u64, c_int, [*c]c_int, [*c]c_int) callconv(.c) void;
pub const basis_zig_NanoVG_nvgDeleteImage_cb = *const fn (u64, c_int) callconv(.c) void;
pub const basis_zig_NanoVG_nvgSetIGNAmount_cb = *const fn (u64, f32) callconv(.c) f32;

// ===============================

// class GoofyUIView

pub const basis_zig_GoofyUIView_getWidget_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) u64;
pub const basis_zig_GoofyUIView_requestFocusChange_cb = *const fn (u64, u64, u32) callconv(.c) void;
pub const basis_zig_GoofyUIView_setRecreationCallbackEnabled_cb = *const fn (u64, c_int) callconv(.c) void;
pub const basis_zig_GoofyUIView_setRaiseNavDirEvents_cb = *const fn (u64, c_int) callconv(.c) void;
pub const basis_zig_GoofyUIView_setRaiseMouseEvents_cb = *const fn (u64, c_int) callconv(.c) void;

// ===============================

// class GoofyUIWidget

pub const basis_zig_GoofyUIWidget_getName_cb = *const fn (u64, u32, [*c]basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_GoofyUIWidget_setPosition_cb = *const fn (u64, u32, [*c]const basis.bindings.InteropVec2) callconv(.c) void;
pub const basis_zig_GoofyUIWidget_getPosition_cb = *const fn (u64, u32, [*c]basis.bindings.InteropVec2) callconv(.c) void;
pub const basis_zig_GoofyUIWidget_setSize_cb = *const fn (u64, u32, [*c]const basis.bindings.InteropVec2) callconv(.c) void;
pub const basis_zig_GoofyUIWidget_getSize_cb = *const fn (u64, u32, [*c]basis.bindings.InteropVec2) callconv(.c) void;
pub const basis_zig_GoofyUIWidget_setVisible_cb = *const fn (u64, u32, bool) callconv(.c) void;
pub const basis_zig_GoofyUIWidget_isVisible_cb = *const fn (u64, u32) callconv(.c) c_int;
pub const basis_zig_GoofyUIWidget_setEnabled_cb = *const fn (u64, u32, bool) callconv(.c) void;
pub const basis_zig_GoofyUIWidget_isEnabled_cb = *const fn (u64, u32) callconv(.c) c_int;

// ===============================

// class GoofyUILabel

pub const basis_zig_GoofyUILabel_setRawText_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_GoofyUILabel_setLocalizedText_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_GoofyUILabel_setColor_cb = *const fn (u64, [*c]const basis.bindings.InteropColor) callconv(.c) void;
pub const basis_zig_GoofyUILabel_getColor_cb = *const fn (u64, [*c]basis.bindings.InteropColor) callconv(.c) void;

// ===============================

// class GoofyUIButton

pub const basis_zig_GoofyUIButton_setRawText_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_GoofyUIButton_setLocalizedText_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) void;

// ===============================

// class GoofyUICanvas

pub const basis_zig_GoofyUICanvas_setRenderCallbackEnabled_cb = *const fn (u64, c_int) callconv(.c) void;
pub const basis_zig_GoofyUICanvas_getUserData_cb = *const fn (u64, [*c]basis.bindings.InteropVec4) callconv(.c) void;

// ===============================

// class GoofyUIImageBox

pub const basis_zig_GoofyUIImageBox_play_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_GoofyUIImageBox_pause_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_GoofyUIImageBox_stop_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_GoofyUIImageBox_jumpToEnd_cb = *const fn (u64) callconv(.c) void;

// ===============================

// class GoofyUISpinBox

pub const basis_zig_GoofyUISpinBox_addItem_cb = *const fn (u64, c_int, [*c]const basis.bindings.InteropString, bool) callconv(.c) void;
pub const basis_zig_GoofyUISpinBox_clearItems_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_GoofyUISpinBox_setSelectedValue_cb = *const fn (u64, c_int) callconv(.c) void;
pub const basis_zig_GoofyUISpinBox_getSelectedValue_cb = *const fn (u64) callconv(.c) c_int;

// ===============================

// class GoofyUIUserWidget

pub const basis_zig_GoofyUIUserWidget_setRenderCallbackEnabled_cb = *const fn (u64, c_int) callconv(.c) void;
pub const basis_zig_GoofyUIUserWidget_setEventCallbackEnabled_cb = *const fn (u64, c_int) callconv(.c) void;
pub const basis_zig_GoofyUIUserWidget_getUserData_cb = *const fn (u64, [*c]basis.bindings.InteropVec4) callconv(.c) void;

// ===============================

// class GoofySVGImage

pub const basis_zig_GoofySVGImage_newImage_cb = *const fn () callconv(.c) u64;
pub const basis_zig_GoofySVGImage_deleteImage_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_GoofySVGImage_getWidth_cb = *const fn (u64) callconv(.c) f32;
pub const basis_zig_GoofySVGImage_getHeight_cb = *const fn (u64) callconv(.c) f32;
pub const basis_zig_GoofySVGImage_loadImage_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_GoofySVGImage_render_cb = *const fn (u64, [*c]const goofy.bindings.InteropUIRenderContext, [*c]const basis.bindings.InteropVec2, [*c]const basis.bindings.InteropVec2) callconv(.c) void;
pub const basis_zig_GoofySVGImage_renderUnstretched_cb = *const fn (u64, [*c]const goofy.bindings.InteropUIRenderContext, [*c]const basis.bindings.InteropVec2, f32, u32) callconv(.c) void;
pub const basis_zig_GoofySVGImage_renderInPixelRect_cb = *const fn (u64, [*c]const goofy.bindings.InteropUIRenderContext, [*c]const basis.bindings.InteropVec2, [*c]const basis.bindings.InteropVec2) callconv(.c) void;

// ===============================

// class GoofySVGAnimationPlayer

pub const basis_zig_GoofySVGAnimationPlayer_newPlayer_cb = *const fn () callconv(.c) u64;
pub const basis_zig_GoofySVGAnimationPlayer_deletePlayer_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_GoofySVGAnimationPlayer_getWidth_cb = *const fn (u64) callconv(.c) f32;
pub const basis_zig_GoofySVGAnimationPlayer_getHeight_cb = *const fn (u64) callconv(.c) f32;
pub const basis_zig_GoofySVGAnimationPlayer_setDeltaTimeLimitEnabled_cb = *const fn (u64, bool) callconv(.c) void;
pub const basis_zig_GoofySVGAnimationPlayer_loadAnimation_cb = *const fn (u64, u64) callconv(.c) void;
pub const basis_zig_GoofySVGAnimationPlayer_render_cb = *const fn (u64, [*c]const goofy.bindings.InteropUIRenderContext, [*c]const basis.bindings.InteropVec2, [*c]const basis.bindings.InteropVec2) callconv(.c) void;
pub const basis_zig_GoofySVGAnimationPlayer_renderUnstretched_cb = *const fn (u64, [*c]const goofy.bindings.InteropUIRenderContext, [*c]const basis.bindings.InteropVec2, f32, u32) callconv(.c) void;
pub const basis_zig_GoofySVGAnimationPlayer_play_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_GoofySVGAnimationPlayer_pause_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_GoofySVGAnimationPlayer_stop_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_GoofySVGAnimationPlayer_jumpToEnd_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_GoofySVGAnimationPlayer_setLooping_cb = *const fn (u64, bool) callconv(.c) void;
pub const basis_zig_GoofySVGAnimationPlayer_update_cb = *const fn (u64, f32) callconv(.c) void;
pub const basis_zig_GoofySVGAnimationPlayer_getState_cb = *const fn (u64) callconv(.c) u32;
pub const basis_zig_GoofySVGAnimationPlayer_getCurrentTime_cb = *const fn (u64) callconv(.c) f32;
pub const basis_zig_GoofySVGAnimationPlayer_setCurrentTime_cb = *const fn (u64, f32) callconv(.c) void;

// ===============================

