// ----------------------------------------------------
// Copyright (c) 2018-2026 Madrigal Ltd.
// This file is part of the Basis SDK, and is subject to the
// terms and conditions of the Basis SDK License Agreement.
// https://www.madrigalgames.com
// ----------------------------------------------------

// This file was generated by Sir Bindalot, the binding generator. Ne pas toucher!

const basis = @import("basis");
const goofy = @import("../goofy.zig");

// class GoofyManager

export fn bindGoofyManager(
	setAspectRatio: goofy.bindings.generated_types.basis_zig_GoofyManager_setAspectRatio_cb,
	setFitMode: goofy.bindings.generated_types.basis_zig_GoofyManager_setFitMode_cb,
	createView: goofy.bindings.generated_types.basis_zig_GoofyManager_createView_cb,
	createViewWithScript: goofy.bindings.generated_types.basis_zig_GoofyManager_createViewWithScript_cb,
	destroyView: goofy.bindings.generated_types.basis_zig_GoofyManager_destroyView_cb,
	pushViewOntoStack: goofy.bindings.generated_types.basis_zig_GoofyManager_pushViewOntoStack_cb,
	pushModalViewOntoStack: goofy.bindings.generated_types.basis_zig_GoofyManager_pushModalViewOntoStack_cb,
	removeViewFromStack: goofy.bindings.generated_types.basis_zig_GoofyManager_removeViewFromStack_cb,
	clearViewStack: goofy.bindings.generated_types.basis_zig_GoofyManager_clearViewStack_cb,
	createFont: goofy.bindings.generated_types.basis_zig_GoofyManager_createFont_cb,
	registerAction: goofy.bindings.generated_types.basis_zig_GoofyManager_registerAction_cb,
	fireAction: goofy.bindings.generated_types.basis_zig_GoofyManager_fireAction_cb,
	setActionCallback: goofy.bindings.generated_types.basis_zig_GoofyManager_setActionCallback_cb,
	clearActionCallback: goofy.bindings.generated_types.basis_zig_GoofyManager_clearActionCallback_cb,
	registerProperty: goofy.bindings.generated_types.basis_zig_GoofyManager_registerProperty_cb,
	getPropertyType: goofy.bindings.generated_types.basis_zig_GoofyManager_getPropertyType_cb,
	getPropertyValue: goofy.bindings.generated_types.basis_zig_GoofyManager_getPropertyValue_cb,
	setPropertyValue: goofy.bindings.generated_types.basis_zig_GoofyManager_setPropertyValue_cb,
	registerStringProperty: goofy.bindings.generated_types.basis_zig_GoofyManager_registerStringProperty_cb,
	getStringPropertyValue: goofy.bindings.generated_types.basis_zig_GoofyManager_getStringPropertyValue_cb,
	setStringPropertyValue: goofy.bindings.generated_types.basis_zig_GoofyManager_setStringPropertyValue_cb,
	setZigEventHandlingEnabled: goofy.bindings.generated_types.basis_zig_GoofyManager_setZigEventHandlingEnabled_cb,
	setPeripheryColor: goofy.bindings.generated_types.basis_zig_GoofyManager_setPeripheryColor_cb,
	clearPeripheryColor: goofy.bindings.generated_types.basis_zig_GoofyManager_clearPeripheryColor_cb,
	getNVGcontext: goofy.bindings.generated_types.basis_zig_GoofyManager_getNVGcontext_cb,
	getUIPosFromPixelPos: goofy.bindings.generated_types.basis_zig_GoofyManager_getUIPosFromPixelPos_cb,
) void {
	goofy.bindings.generated_function_pointers._GoofyManager_setAspectRatio = setAspectRatio;
	goofy.bindings.generated_function_pointers._GoofyManager_setFitMode = setFitMode;
	goofy.bindings.generated_function_pointers._GoofyManager_createView = createView;
	goofy.bindings.generated_function_pointers._GoofyManager_createViewWithScript = createViewWithScript;
	goofy.bindings.generated_function_pointers._GoofyManager_destroyView = destroyView;
	goofy.bindings.generated_function_pointers._GoofyManager_pushViewOntoStack = pushViewOntoStack;
	goofy.bindings.generated_function_pointers._GoofyManager_pushModalViewOntoStack = pushModalViewOntoStack;
	goofy.bindings.generated_function_pointers._GoofyManager_removeViewFromStack = removeViewFromStack;
	goofy.bindings.generated_function_pointers._GoofyManager_clearViewStack = clearViewStack;
	goofy.bindings.generated_function_pointers._GoofyManager_createFont = createFont;
	goofy.bindings.generated_function_pointers._GoofyManager_registerAction = registerAction;
	goofy.bindings.generated_function_pointers._GoofyManager_fireAction = fireAction;
	goofy.bindings.generated_function_pointers._GoofyManager_setActionCallback = setActionCallback;
	goofy.bindings.generated_function_pointers._GoofyManager_clearActionCallback = clearActionCallback;
	goofy.bindings.generated_function_pointers._GoofyManager_registerProperty = registerProperty;
	goofy.bindings.generated_function_pointers._GoofyManager_getPropertyType = getPropertyType;
	goofy.bindings.generated_function_pointers._GoofyManager_getPropertyValue = getPropertyValue;
	goofy.bindings.generated_function_pointers._GoofyManager_setPropertyValue = setPropertyValue;
	goofy.bindings.generated_function_pointers._GoofyManager_registerStringProperty = registerStringProperty;
	goofy.bindings.generated_function_pointers._GoofyManager_getStringPropertyValue = getStringPropertyValue;
	goofy.bindings.generated_function_pointers._GoofyManager_setStringPropertyValue = setStringPropertyValue;
	goofy.bindings.generated_function_pointers._GoofyManager_setZigEventHandlingEnabled = setZigEventHandlingEnabled;
	goofy.bindings.generated_function_pointers._GoofyManager_setPeripheryColor = setPeripheryColor;
	goofy.bindings.generated_function_pointers._GoofyManager_clearPeripheryColor = clearPeripheryColor;
	goofy.bindings.generated_function_pointers._GoofyManager_getNVGcontext = getNVGcontext;
	goofy.bindings.generated_function_pointers._GoofyManager_getUIPosFromPixelPos = getUIPosFromPixelPos;
}

// ===============================

// class GoofySkins

export fn bindGoofySkins(
	registerSkin: goofy.bindings.generated_types.basis_zig_GoofySkins_registerSkin_cb,
	setButtonRenderCallback: goofy.bindings.generated_types.basis_zig_GoofySkins_setButtonRenderCallback_cb,
	setSpinBoxRenderCallback: goofy.bindings.generated_types.basis_zig_GoofySkins_setSpinBoxRenderCallback_cb,
) void {
	goofy.bindings.generated_function_pointers._GoofySkins_registerSkin = registerSkin;
	goofy.bindings.generated_function_pointers._GoofySkins_setButtonRenderCallback = setButtonRenderCallback;
	goofy.bindings.generated_function_pointers._GoofySkins_setSpinBoxRenderCallback = setSpinBoxRenderCallback;
}

// ===============================

// class NanoVG

export fn bindNanoVG(
	nvgSave: goofy.bindings.generated_types.basis_zig_NanoVG_nvgSave_cb,
	nvgRestore: goofy.bindings.generated_types.basis_zig_NanoVG_nvgRestore_cb,
	nvgReset: goofy.bindings.generated_types.basis_zig_NanoVG_nvgReset_cb,
	nvgShapeAntiAlias: goofy.bindings.generated_types.basis_zig_NanoVG_nvgShapeAntiAlias_cb,
	nvgStrokeColor: goofy.bindings.generated_types.basis_zig_NanoVG_nvgStrokeColor_cb,
	nvgStrokePaint: goofy.bindings.generated_types.basis_zig_NanoVG_nvgStrokePaint_cb,
	nvgFillColor: goofy.bindings.generated_types.basis_zig_NanoVG_nvgFillColor_cb,
	nvgFillPaint: goofy.bindings.generated_types.basis_zig_NanoVG_nvgFillPaint_cb,
	nvgMiterLimit: goofy.bindings.generated_types.basis_zig_NanoVG_nvgMiterLimit_cb,
	nvgStrokeWidth: goofy.bindings.generated_types.basis_zig_NanoVG_nvgStrokeWidth_cb,
	nvgLineCap: goofy.bindings.generated_types.basis_zig_NanoVG_nvgLineCap_cb,
	nvgLineJoin: goofy.bindings.generated_types.basis_zig_NanoVG_nvgLineJoin_cb,
	nvgGlobalAlpha: goofy.bindings.generated_types.basis_zig_NanoVG_nvgGlobalAlpha_cb,
	nvgResetTransform: goofy.bindings.generated_types.basis_zig_NanoVG_nvgResetTransform_cb,
	nvgTransform: goofy.bindings.generated_types.basis_zig_NanoVG_nvgTransform_cb,
	nvgTranslate: goofy.bindings.generated_types.basis_zig_NanoVG_nvgTranslate_cb,
	nvgRotate: goofy.bindings.generated_types.basis_zig_NanoVG_nvgRotate_cb,
	nvgSkewX: goofy.bindings.generated_types.basis_zig_NanoVG_nvgSkewX_cb,
	nvgSkewY: goofy.bindings.generated_types.basis_zig_NanoVG_nvgSkewY_cb,
	nvgScale: goofy.bindings.generated_types.basis_zig_NanoVG_nvgScale_cb,
	nvgCurrentTransform: goofy.bindings.generated_types.basis_zig_NanoVG_nvgCurrentTransform_cb,
	nvgScissor: goofy.bindings.generated_types.basis_zig_NanoVG_nvgScissor_cb,
	nvgIntersectScissor: goofy.bindings.generated_types.basis_zig_NanoVG_nvgIntersectScissor_cb,
	nvgResetScissor: goofy.bindings.generated_types.basis_zig_NanoVG_nvgResetScissor_cb,
	nvgBeginPath: goofy.bindings.generated_types.basis_zig_NanoVG_nvgBeginPath_cb,
	nvgMoveTo: goofy.bindings.generated_types.basis_zig_NanoVG_nvgMoveTo_cb,
	nvgLineTo: goofy.bindings.generated_types.basis_zig_NanoVG_nvgLineTo_cb,
	nvgBezierTo: goofy.bindings.generated_types.basis_zig_NanoVG_nvgBezierTo_cb,
	nvgQuadTo: goofy.bindings.generated_types.basis_zig_NanoVG_nvgQuadTo_cb,
	nvgArcTo: goofy.bindings.generated_types.basis_zig_NanoVG_nvgArcTo_cb,
	nvgClosePath: goofy.bindings.generated_types.basis_zig_NanoVG_nvgClosePath_cb,
	nvgPathWinding: goofy.bindings.generated_types.basis_zig_NanoVG_nvgPathWinding_cb,
	nvgArc: goofy.bindings.generated_types.basis_zig_NanoVG_nvgArc_cb,
	nvgRect: goofy.bindings.generated_types.basis_zig_NanoVG_nvgRect_cb,
	nvgRoundedRect: goofy.bindings.generated_types.basis_zig_NanoVG_nvgRoundedRect_cb,
	nvgRoundedRectVarying: goofy.bindings.generated_types.basis_zig_NanoVG_nvgRoundedRectVarying_cb,
	nvgEllipse: goofy.bindings.generated_types.basis_zig_NanoVG_nvgEllipse_cb,
	nvgCircle: goofy.bindings.generated_types.basis_zig_NanoVG_nvgCircle_cb,
	nvgFill: goofy.bindings.generated_types.basis_zig_NanoVG_nvgFill_cb,
	nvgStroke: goofy.bindings.generated_types.basis_zig_NanoVG_nvgStroke_cb,
	nvgFindFont: goofy.bindings.generated_types.basis_zig_NanoVG_nvgFindFont_cb,
	nvgFontSize: goofy.bindings.generated_types.basis_zig_NanoVG_nvgFontSize_cb,
	nvgFontBlur: goofy.bindings.generated_types.basis_zig_NanoVG_nvgFontBlur_cb,
	nvgTextLetterSpacing: goofy.bindings.generated_types.basis_zig_NanoVG_nvgTextLetterSpacing_cb,
	nvgTextLineHeight: goofy.bindings.generated_types.basis_zig_NanoVG_nvgTextLineHeight_cb,
	nvgTextAlign: goofy.bindings.generated_types.basis_zig_NanoVG_nvgTextAlign_cb,
	nvgFontFaceId: goofy.bindings.generated_types.basis_zig_NanoVG_nvgFontFaceId_cb,
	nvgFontFace: goofy.bindings.generated_types.basis_zig_NanoVG_nvgFontFace_cb,
	nvgText: goofy.bindings.generated_types.basis_zig_NanoVG_nvgText_cb,
	nvgTextBox: goofy.bindings.generated_types.basis_zig_NanoVG_nvgTextBox_cb,
	nvgTextBounds: goofy.bindings.generated_types.basis_zig_NanoVG_nvgTextBounds_cb,
	nvgTextMetrics: goofy.bindings.generated_types.basis_zig_NanoVG_nvgTextMetrics_cb,
	nvgTextSubset: goofy.bindings.generated_types.basis_zig_NanoVG_nvgTextSubset_cb,
	nvgTextBoxSubset: goofy.bindings.generated_types.basis_zig_NanoVG_nvgTextBoxSubset_cb,
	nvgTextCountRows: goofy.bindings.generated_types.basis_zig_NanoVG_nvgTextCountRows_cb,
	nvgCreateImageFromTextureResource: goofy.bindings.generated_types.basis_zig_NanoVG_nvgCreateImageFromTextureResource_cb,
	nvgImageSize: goofy.bindings.generated_types.basis_zig_NanoVG_nvgImageSize_cb,
	nvgDeleteImage: goofy.bindings.generated_types.basis_zig_NanoVG_nvgDeleteImage_cb,
	nvgSetIGNAmount: goofy.bindings.generated_types.basis_zig_NanoVG_nvgSetIGNAmount_cb,
) void {
	goofy.bindings.generated_function_pointers._NanoVG_nvgSave = nvgSave;
	goofy.bindings.generated_function_pointers._NanoVG_nvgRestore = nvgRestore;
	goofy.bindings.generated_function_pointers._NanoVG_nvgReset = nvgReset;
	goofy.bindings.generated_function_pointers._NanoVG_nvgShapeAntiAlias = nvgShapeAntiAlias;
	goofy.bindings.generated_function_pointers._NanoVG_nvgStrokeColor = nvgStrokeColor;
	goofy.bindings.generated_function_pointers._NanoVG_nvgStrokePaint = nvgStrokePaint;
	goofy.bindings.generated_function_pointers._NanoVG_nvgFillColor = nvgFillColor;
	goofy.bindings.generated_function_pointers._NanoVG_nvgFillPaint = nvgFillPaint;
	goofy.bindings.generated_function_pointers._NanoVG_nvgMiterLimit = nvgMiterLimit;
	goofy.bindings.generated_function_pointers._NanoVG_nvgStrokeWidth = nvgStrokeWidth;
	goofy.bindings.generated_function_pointers._NanoVG_nvgLineCap = nvgLineCap;
	goofy.bindings.generated_function_pointers._NanoVG_nvgLineJoin = nvgLineJoin;
	goofy.bindings.generated_function_pointers._NanoVG_nvgGlobalAlpha = nvgGlobalAlpha;
	goofy.bindings.generated_function_pointers._NanoVG_nvgResetTransform = nvgResetTransform;
	goofy.bindings.generated_function_pointers._NanoVG_nvgTransform = nvgTransform;
	goofy.bindings.generated_function_pointers._NanoVG_nvgTranslate = nvgTranslate;
	goofy.bindings.generated_function_pointers._NanoVG_nvgRotate = nvgRotate;
	goofy.bindings.generated_function_pointers._NanoVG_nvgSkewX = nvgSkewX;
	goofy.bindings.generated_function_pointers._NanoVG_nvgSkewY = nvgSkewY;
	goofy.bindings.generated_function_pointers._NanoVG_nvgScale = nvgScale;
	goofy.bindings.generated_function_pointers._NanoVG_nvgCurrentTransform = nvgCurrentTransform;
	goofy.bindings.generated_function_pointers._NanoVG_nvgScissor = nvgScissor;
	goofy.bindings.generated_function_pointers._NanoVG_nvgIntersectScissor = nvgIntersectScissor;
	goofy.bindings.generated_function_pointers._NanoVG_nvgResetScissor = nvgResetScissor;
	goofy.bindings.generated_function_pointers._NanoVG_nvgBeginPath = nvgBeginPath;
	goofy.bindings.generated_function_pointers._NanoVG_nvgMoveTo = nvgMoveTo;
	goofy.bindings.generated_function_pointers._NanoVG_nvgLineTo = nvgLineTo;
	goofy.bindings.generated_function_pointers._NanoVG_nvgBezierTo = nvgBezierTo;
	goofy.bindings.generated_function_pointers._NanoVG_nvgQuadTo = nvgQuadTo;
	goofy.bindings.generated_function_pointers._NanoVG_nvgArcTo = nvgArcTo;
	goofy.bindings.generated_function_pointers._NanoVG_nvgClosePath = nvgClosePath;
	goofy.bindings.generated_function_pointers._NanoVG_nvgPathWinding = nvgPathWinding;
	goofy.bindings.generated_function_pointers._NanoVG_nvgArc = nvgArc;
	goofy.bindings.generated_function_pointers._NanoVG_nvgRect = nvgRect;
	goofy.bindings.generated_function_pointers._NanoVG_nvgRoundedRect = nvgRoundedRect;
	goofy.bindings.generated_function_pointers._NanoVG_nvgRoundedRectVarying = nvgRoundedRectVarying;
	goofy.bindings.generated_function_pointers._NanoVG_nvgEllipse = nvgEllipse;
	goofy.bindings.generated_function_pointers._NanoVG_nvgCircle = nvgCircle;
	goofy.bindings.generated_function_pointers._NanoVG_nvgFill = nvgFill;
	goofy.bindings.generated_function_pointers._NanoVG_nvgStroke = nvgStroke;
	goofy.bindings.generated_function_pointers._NanoVG_nvgFindFont = nvgFindFont;
	goofy.bindings.generated_function_pointers._NanoVG_nvgFontSize = nvgFontSize;
	goofy.bindings.generated_function_pointers._NanoVG_nvgFontBlur = nvgFontBlur;
	goofy.bindings.generated_function_pointers._NanoVG_nvgTextLetterSpacing = nvgTextLetterSpacing;
	goofy.bindings.generated_function_pointers._NanoVG_nvgTextLineHeight = nvgTextLineHeight;
	goofy.bindings.generated_function_pointers._NanoVG_nvgTextAlign = nvgTextAlign;
	goofy.bindings.generated_function_pointers._NanoVG_nvgFontFaceId = nvgFontFaceId;
	goofy.bindings.generated_function_pointers._NanoVG_nvgFontFace = nvgFontFace;
	goofy.bindings.generated_function_pointers._NanoVG_nvgText = nvgText;
	goofy.bindings.generated_function_pointers._NanoVG_nvgTextBox = nvgTextBox;
	goofy.bindings.generated_function_pointers._NanoVG_nvgTextBounds = nvgTextBounds;
	goofy.bindings.generated_function_pointers._NanoVG_nvgTextMetrics = nvgTextMetrics;
	goofy.bindings.generated_function_pointers._NanoVG_nvgTextSubset = nvgTextSubset;
	goofy.bindings.generated_function_pointers._NanoVG_nvgTextBoxSubset = nvgTextBoxSubset;
	goofy.bindings.generated_function_pointers._NanoVG_nvgTextCountRows = nvgTextCountRows;
	goofy.bindings.generated_function_pointers._NanoVG_nvgCreateImageFromTextureResource = nvgCreateImageFromTextureResource;
	goofy.bindings.generated_function_pointers._NanoVG_nvgImageSize = nvgImageSize;
	goofy.bindings.generated_function_pointers._NanoVG_nvgDeleteImage = nvgDeleteImage;
	goofy.bindings.generated_function_pointers._NanoVG_nvgSetIGNAmount = nvgSetIGNAmount;
}

// ===============================

// class GoofyUIView

export fn bindGoofyUIView(
	getWidget: goofy.bindings.generated_types.basis_zig_GoofyUIView_getWidget_cb,
	requestFocusChange: goofy.bindings.generated_types.basis_zig_GoofyUIView_requestFocusChange_cb,
	setRecreationCallbackEnabled: goofy.bindings.generated_types.basis_zig_GoofyUIView_setRecreationCallbackEnabled_cb,
	setRaiseNavDirEvents: goofy.bindings.generated_types.basis_zig_GoofyUIView_setRaiseNavDirEvents_cb,
	setRaiseMouseEvents: goofy.bindings.generated_types.basis_zig_GoofyUIView_setRaiseMouseEvents_cb,
) void {
	goofy.bindings.generated_function_pointers._GoofyUIView_getWidget = getWidget;
	goofy.bindings.generated_function_pointers._GoofyUIView_requestFocusChange = requestFocusChange;
	goofy.bindings.generated_function_pointers._GoofyUIView_setRecreationCallbackEnabled = setRecreationCallbackEnabled;
	goofy.bindings.generated_function_pointers._GoofyUIView_setRaiseNavDirEvents = setRaiseNavDirEvents;
	goofy.bindings.generated_function_pointers._GoofyUIView_setRaiseMouseEvents = setRaiseMouseEvents;
}

// ===============================

// class GoofyUIWidget

export fn bindGoofyUIWidget(
	getName: goofy.bindings.generated_types.basis_zig_GoofyUIWidget_getName_cb,
	setPosition: goofy.bindings.generated_types.basis_zig_GoofyUIWidget_setPosition_cb,
	getPosition: goofy.bindings.generated_types.basis_zig_GoofyUIWidget_getPosition_cb,
	setSize: goofy.bindings.generated_types.basis_zig_GoofyUIWidget_setSize_cb,
	getSize: goofy.bindings.generated_types.basis_zig_GoofyUIWidget_getSize_cb,
	setVisible: goofy.bindings.generated_types.basis_zig_GoofyUIWidget_setVisible_cb,
	isVisible: goofy.bindings.generated_types.basis_zig_GoofyUIWidget_isVisible_cb,
	setEnabled: goofy.bindings.generated_types.basis_zig_GoofyUIWidget_setEnabled_cb,
	isEnabled: goofy.bindings.generated_types.basis_zig_GoofyUIWidget_isEnabled_cb,
) void {
	goofy.bindings.generated_function_pointers._GoofyUIWidget_getName = getName;
	goofy.bindings.generated_function_pointers._GoofyUIWidget_setPosition = setPosition;
	goofy.bindings.generated_function_pointers._GoofyUIWidget_getPosition = getPosition;
	goofy.bindings.generated_function_pointers._GoofyUIWidget_setSize = setSize;
	goofy.bindings.generated_function_pointers._GoofyUIWidget_getSize = getSize;
	goofy.bindings.generated_function_pointers._GoofyUIWidget_setVisible = setVisible;
	goofy.bindings.generated_function_pointers._GoofyUIWidget_isVisible = isVisible;
	goofy.bindings.generated_function_pointers._GoofyUIWidget_setEnabled = setEnabled;
	goofy.bindings.generated_function_pointers._GoofyUIWidget_isEnabled = isEnabled;
}

// ===============================

// class GoofyUILabel

export fn bindGoofyUILabel(
	setRawText: goofy.bindings.generated_types.basis_zig_GoofyUILabel_setRawText_cb,
	setLocalizedText: goofy.bindings.generated_types.basis_zig_GoofyUILabel_setLocalizedText_cb,
	setColor: goofy.bindings.generated_types.basis_zig_GoofyUILabel_setColor_cb,
	getColor: goofy.bindings.generated_types.basis_zig_GoofyUILabel_getColor_cb,
) void {
	goofy.bindings.generated_function_pointers._GoofyUILabel_setRawText = setRawText;
	goofy.bindings.generated_function_pointers._GoofyUILabel_setLocalizedText = setLocalizedText;
	goofy.bindings.generated_function_pointers._GoofyUILabel_setColor = setColor;
	goofy.bindings.generated_function_pointers._GoofyUILabel_getColor = getColor;
}

// ===============================

// class GoofyUIButton

export fn bindGoofyUIButton(
	setRawText: goofy.bindings.generated_types.basis_zig_GoofyUIButton_setRawText_cb,
	setLocalizedText: goofy.bindings.generated_types.basis_zig_GoofyUIButton_setLocalizedText_cb,
) void {
	goofy.bindings.generated_function_pointers._GoofyUIButton_setRawText = setRawText;
	goofy.bindings.generated_function_pointers._GoofyUIButton_setLocalizedText = setLocalizedText;
}

// ===============================

// class GoofyUICanvas

export fn bindGoofyUICanvas(
	setRenderCallbackEnabled: goofy.bindings.generated_types.basis_zig_GoofyUICanvas_setRenderCallbackEnabled_cb,
	getUserData: goofy.bindings.generated_types.basis_zig_GoofyUICanvas_getUserData_cb,
) void {
	goofy.bindings.generated_function_pointers._GoofyUICanvas_setRenderCallbackEnabled = setRenderCallbackEnabled;
	goofy.bindings.generated_function_pointers._GoofyUICanvas_getUserData = getUserData;
}

// ===============================

// class GoofyUIImageBox

export fn bindGoofyUIImageBox(
	play: goofy.bindings.generated_types.basis_zig_GoofyUIImageBox_play_cb,
	pause: goofy.bindings.generated_types.basis_zig_GoofyUIImageBox_pause_cb,
	stop: goofy.bindings.generated_types.basis_zig_GoofyUIImageBox_stop_cb,
	jumpToEnd: goofy.bindings.generated_types.basis_zig_GoofyUIImageBox_jumpToEnd_cb,
) void {
	goofy.bindings.generated_function_pointers._GoofyUIImageBox_play = play;
	goofy.bindings.generated_function_pointers._GoofyUIImageBox_pause = pause;
	goofy.bindings.generated_function_pointers._GoofyUIImageBox_stop = stop;
	goofy.bindings.generated_function_pointers._GoofyUIImageBox_jumpToEnd = jumpToEnd;
}

// ===============================

// class GoofyUISpinBox

export fn bindGoofyUISpinBox(
	addItem: goofy.bindings.generated_types.basis_zig_GoofyUISpinBox_addItem_cb,
	clearItems: goofy.bindings.generated_types.basis_zig_GoofyUISpinBox_clearItems_cb,
	setSelectedValue: goofy.bindings.generated_types.basis_zig_GoofyUISpinBox_setSelectedValue_cb,
	getSelectedValue: goofy.bindings.generated_types.basis_zig_GoofyUISpinBox_getSelectedValue_cb,
) void {
	goofy.bindings.generated_function_pointers._GoofyUISpinBox_addItem = addItem;
	goofy.bindings.generated_function_pointers._GoofyUISpinBox_clearItems = clearItems;
	goofy.bindings.generated_function_pointers._GoofyUISpinBox_setSelectedValue = setSelectedValue;
	goofy.bindings.generated_function_pointers._GoofyUISpinBox_getSelectedValue = getSelectedValue;
}

// ===============================

// class GoofyUIUserWidget

export fn bindGoofyUIUserWidget(
	setRenderCallbackEnabled: goofy.bindings.generated_types.basis_zig_GoofyUIUserWidget_setRenderCallbackEnabled_cb,
	setEventCallbackEnabled: goofy.bindings.generated_types.basis_zig_GoofyUIUserWidget_setEventCallbackEnabled_cb,
	getUserData: goofy.bindings.generated_types.basis_zig_GoofyUIUserWidget_getUserData_cb,
) void {
	goofy.bindings.generated_function_pointers._GoofyUIUserWidget_setRenderCallbackEnabled = setRenderCallbackEnabled;
	goofy.bindings.generated_function_pointers._GoofyUIUserWidget_setEventCallbackEnabled = setEventCallbackEnabled;
	goofy.bindings.generated_function_pointers._GoofyUIUserWidget_getUserData = getUserData;
}

// ===============================

// class GoofySVGImage

export fn bindGoofySVGImage(
	newImage: goofy.bindings.generated_types.basis_zig_GoofySVGImage_newImage_cb,
	deleteImage: goofy.bindings.generated_types.basis_zig_GoofySVGImage_deleteImage_cb,
	getWidth: goofy.bindings.generated_types.basis_zig_GoofySVGImage_getWidth_cb,
	getHeight: goofy.bindings.generated_types.basis_zig_GoofySVGImage_getHeight_cb,
	loadImage: goofy.bindings.generated_types.basis_zig_GoofySVGImage_loadImage_cb,
	render: goofy.bindings.generated_types.basis_zig_GoofySVGImage_render_cb,
	renderUnstretched: goofy.bindings.generated_types.basis_zig_GoofySVGImage_renderUnstretched_cb,
	renderInPixelRect: goofy.bindings.generated_types.basis_zig_GoofySVGImage_renderInPixelRect_cb,
) void {
	goofy.bindings.generated_function_pointers._GoofySVGImage_newImage = newImage;
	goofy.bindings.generated_function_pointers._GoofySVGImage_deleteImage = deleteImage;
	goofy.bindings.generated_function_pointers._GoofySVGImage_getWidth = getWidth;
	goofy.bindings.generated_function_pointers._GoofySVGImage_getHeight = getHeight;
	goofy.bindings.generated_function_pointers._GoofySVGImage_loadImage = loadImage;
	goofy.bindings.generated_function_pointers._GoofySVGImage_render = render;
	goofy.bindings.generated_function_pointers._GoofySVGImage_renderUnstretched = renderUnstretched;
	goofy.bindings.generated_function_pointers._GoofySVGImage_renderInPixelRect = renderInPixelRect;
}

// ===============================

// class GoofySVGAnimationPlayer

export fn bindGoofySVGAnimationPlayer(
	newPlayer: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_newPlayer_cb,
	deletePlayer: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_deletePlayer_cb,
	getWidth: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_getWidth_cb,
	getHeight: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_getHeight_cb,
	setDeltaTimeLimitEnabled: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_setDeltaTimeLimitEnabled_cb,
	loadAnimation: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_loadAnimation_cb,
	render: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_render_cb,
	renderUnstretched: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_renderUnstretched_cb,
	play: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_play_cb,
	pause: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_pause_cb,
	stop: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_stop_cb,
	jumpToEnd: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_jumpToEnd_cb,
	setLooping: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_setLooping_cb,
	update: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_update_cb,
	getState: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_getState_cb,
	getCurrentTime: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_getCurrentTime_cb,
	setCurrentTime: goofy.bindings.generated_types.basis_zig_GoofySVGAnimationPlayer_setCurrentTime_cb,
) void {
	goofy.bindings.generated_function_pointers._GoofySVGAnimationPlayer_newPlayer = newPlayer;
	goofy.bindings.generated_function_pointers._GoofySVGAnimationPlayer_deletePlayer = deletePlayer;
	goofy.bindings.generated_function_pointers._GoofySVGAnimationPlayer_getWidth = getWidth;
	goofy.bindings.generated_function_pointers._GoofySVGAnimationPlayer_getHeight = getHeight;
	goofy.bindings.generated_function_pointers._GoofySVGAnimationPlayer_setDeltaTimeLimitEnabled = setDeltaTimeLimitEnabled;
	goofy.bindings.generated_function_pointers._GoofySVGAnimationPlayer_loadAnimation = loadAnimation;
	goofy.bindings.generated_function_pointers._GoofySVGAnimationPlayer_render = render;
	goofy.bindings.generated_function_pointers._GoofySVGAnimationPlayer_renderUnstretched = renderUnstretched;
	goofy.bindings.generated_function_pointers._GoofySVGAnimationPlayer_play = play;
	goofy.bindings.generated_function_pointers._GoofySVGAnimationPlayer_pause = pause;
	goofy.bindings.generated_function_pointers._GoofySVGAnimationPlayer_stop = stop;
	goofy.bindings.generated_function_pointers._GoofySVGAnimationPlayer_jumpToEnd = jumpToEnd;
	goofy.bindings.generated_function_pointers._GoofySVGAnimationPlayer_setLooping = setLooping;
	goofy.bindings.generated_function_pointers._GoofySVGAnimationPlayer_update = update;
	goofy.bindings.generated_function_pointers._GoofySVGAnimationPlayer_getState = getState;
	goofy.bindings.generated_function_pointers._GoofySVGAnimationPlayer_getCurrentTime = getCurrentTime;
	goofy.bindings.generated_function_pointers._GoofySVGAnimationPlayer_setCurrentTime = setCurrentTime;
}

// ===============================

