// ----------------------------------------------------
// Copyright (c) 2018-2025 Madrigal Ltd.
// This file is part of the Basis SDK, and is subject to the
// terms and conditions of the Basis SDK License Agreement.
// https://www.madrigalgames.com
// ----------------------------------------------------

// This file was generated by Sir Bindalot, the binding generator. Ne pas toucher!

const basis = @import("basis");
const nemo = @import("../nemo.zig");

// class Database

export fn bindDatabase(
	newDatabase: nemo.bindings.generated_types.basis_zig_Database_newDatabase_cb,
	deleteDatabase: nemo.bindings.generated_types.basis_zig_Database_deleteDatabase_cb,
	loadOnClient: nemo.bindings.generated_types.basis_zig_Database_loadOnClient_cb,
	loadOnServer: nemo.bindings.generated_types.basis_zig_Database_loadOnServer_cb,
	unload: nemo.bindings.generated_types.basis_zig_Database_unload_cb,
	tick: nemo.bindings.generated_types.basis_zig_Database_tick_cb,
	serialize: nemo.bindings.generated_types.basis_zig_Database_serialize_cb,
	deserialize: nemo.bindings.generated_types.basis_zig_Database_deserialize_cb,
	getMissionByPath: nemo.bindings.generated_types.basis_zig_Database_getMissionByPath_cb,
	getMissionByPathHash: nemo.bindings.generated_types.basis_zig_Database_getMissionByPathHash_cb,
	getGlobalVariableSetByPath: nemo.bindings.generated_types.basis_zig_Database_getGlobalVariableSetByPath_cb,
	getGlobalVariableSetByPathHash: nemo.bindings.generated_types.basis_zig_Database_getGlobalVariableSetByPathHash_cb,
	getCharacterDataByPath: nemo.bindings.generated_types.basis_zig_Database_getCharacterDataByPath_cb,
	getCharacterDataByPathHash: nemo.bindings.generated_types.basis_zig_Database_getCharacterDataByPathHash_cb,
) void {
	nemo.bindings.generated_function_pointers._Database_newDatabase = newDatabase;
	nemo.bindings.generated_function_pointers._Database_deleteDatabase = deleteDatabase;
	nemo.bindings.generated_function_pointers._Database_loadOnClient = loadOnClient;
	nemo.bindings.generated_function_pointers._Database_loadOnServer = loadOnServer;
	nemo.bindings.generated_function_pointers._Database_unload = unload;
	nemo.bindings.generated_function_pointers._Database_tick = tick;
	nemo.bindings.generated_function_pointers._Database_serialize = serialize;
	nemo.bindings.generated_function_pointers._Database_deserialize = deserialize;
	nemo.bindings.generated_function_pointers._Database_getMissionByPath = getMissionByPath;
	nemo.bindings.generated_function_pointers._Database_getMissionByPathHash = getMissionByPathHash;
	nemo.bindings.generated_function_pointers._Database_getGlobalVariableSetByPath = getGlobalVariableSetByPath;
	nemo.bindings.generated_function_pointers._Database_getGlobalVariableSetByPathHash = getGlobalVariableSetByPathHash;
	nemo.bindings.generated_function_pointers._Database_getCharacterDataByPath = getCharacterDataByPath;
	nemo.bindings.generated_function_pointers._Database_getCharacterDataByPathHash = getCharacterDataByPathHash;
}

// ===============================

// class Mission

export fn bindMission(
	getPath: nemo.bindings.generated_types.basis_zig_Mission_getPath_cb,
	getState: nemo.bindings.generated_types.basis_zig_Mission_getState_cb,
	start: nemo.bindings.generated_types.basis_zig_Mission_start_cb,
	abort: nemo.bindings.generated_types.basis_zig_Mission_abort_cb,
) void {
	nemo.bindings.generated_function_pointers._Mission_getPath = getPath;
	nemo.bindings.generated_function_pointers._Mission_getState = getState;
	nemo.bindings.generated_function_pointers._Mission_start = start;
	nemo.bindings.generated_function_pointers._Mission_abort = abort;
}

// ===============================

// class GlobalVariableSet

export fn bindGlobalVariableSet(
	getPath: nemo.bindings.generated_types.basis_zig_GlobalVariableSet_getPath_cb,
	readFloat: nemo.bindings.generated_types.basis_zig_GlobalVariableSet_readFloat_cb,
	writeFloat: nemo.bindings.generated_types.basis_zig_GlobalVariableSet_writeFloat_cb,
	readInt: nemo.bindings.generated_types.basis_zig_GlobalVariableSet_readInt_cb,
	writeInt: nemo.bindings.generated_types.basis_zig_GlobalVariableSet_writeInt_cb,
	readBool: nemo.bindings.generated_types.basis_zig_GlobalVariableSet_readBool_cb,
	writeBool: nemo.bindings.generated_types.basis_zig_GlobalVariableSet_writeBool_cb,
	readString: nemo.bindings.generated_types.basis_zig_GlobalVariableSet_readString_cb,
	writeString: nemo.bindings.generated_types.basis_zig_GlobalVariableSet_writeString_cb,
) void {
	nemo.bindings.generated_function_pointers._GlobalVariableSet_getPath = getPath;
	nemo.bindings.generated_function_pointers._GlobalVariableSet_readFloat = readFloat;
	nemo.bindings.generated_function_pointers._GlobalVariableSet_writeFloat = writeFloat;
	nemo.bindings.generated_function_pointers._GlobalVariableSet_readInt = readInt;
	nemo.bindings.generated_function_pointers._GlobalVariableSet_writeInt = writeInt;
	nemo.bindings.generated_function_pointers._GlobalVariableSet_readBool = readBool;
	nemo.bindings.generated_function_pointers._GlobalVariableSet_writeBool = writeBool;
	nemo.bindings.generated_function_pointers._GlobalVariableSet_readString = readString;
	nemo.bindings.generated_function_pointers._GlobalVariableSet_writeString = writeString;
}

// ===============================

// class CharacterData

export fn bindCharacterData(
	getPath: nemo.bindings.generated_types.basis_zig_CharacterData_getPath_cb,
	getFirstName: nemo.bindings.generated_types.basis_zig_CharacterData_getFirstName_cb,
	getLastName: nemo.bindings.generated_types.basis_zig_CharacterData_getLastName_cb,
	getUIColor: nemo.bindings.generated_types.basis_zig_CharacterData_getUIColor_cb,
) void {
	nemo.bindings.generated_function_pointers._CharacterData_getPath = getPath;
	nemo.bindings.generated_function_pointers._CharacterData_getFirstName = getFirstName;
	nemo.bindings.generated_function_pointers._CharacterData_getLastName = getLastName;
	nemo.bindings.generated_function_pointers._CharacterData_getUIColor = getUIColor;
}

// ===============================

