// ----------------------------------------------------
// Copyright (c) 2018-2025 Madrigal Ltd.
// This file is part of the Basis SDK, and is subject to the
// terms and conditions of the Basis SDK License Agreement.
// https://www.madrigalgames.com
// ----------------------------------------------------

// This file was generated by Sir Bindalot, the binding generator. Ne pas toucher!

const basis = @import("basis");
const nemo = @import("../nemo.zig");

// class Database

pub const basis_zig_Database_newDatabase_cb = *const fn () callconv(.c) u64;
pub const basis_zig_Database_deleteDatabase_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_Database_loadOnClient_cb = *const fn (u64, u64, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_Database_loadOnServer_cb = *const fn (u64, u64, [*c]const basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_Database_unload_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_Database_tick_cb = *const fn (u64, f32) callconv(.c) void;
pub const basis_zig_Database_serialize_cb = *const fn (u64, [*c]u8, u32) callconv(.c) u32;
pub const basis_zig_Database_deserialize_cb = *const fn (u64, [*c]const u8, u32) callconv(.c) u32;
pub const basis_zig_Database_getMissionByPath_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) u64;
pub const basis_zig_Database_getMissionByPathHash_cb = *const fn (u64, u32) callconv(.c) u64;
pub const basis_zig_Database_getGlobalVariableSetByPath_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) u64;
pub const basis_zig_Database_getGlobalVariableSetByPathHash_cb = *const fn (u64, u32) callconv(.c) u64;
pub const basis_zig_Database_getCharacterDataByPath_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) u64;
pub const basis_zig_Database_getCharacterDataByPathHash_cb = *const fn (u64, u32) callconv(.c) u64;

// ===============================

// class Mission

pub const basis_zig_Mission_getPath_cb = *const fn (u64, [*c]basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_Mission_getState_cb = *const fn (u64) callconv(.c) u32;
pub const basis_zig_Mission_start_cb = *const fn (u64) callconv(.c) void;
pub const basis_zig_Mission_abort_cb = *const fn (u64) callconv(.c) void;

// ===============================

// class GlobalVariableSet

pub const basis_zig_GlobalVariableSet_getPath_cb = *const fn (u64, [*c]basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_GlobalVariableSet_readFloat_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) f32;
pub const basis_zig_GlobalVariableSet_writeFloat_cb = *const fn (u64, [*c]const basis.bindings.InteropString, f32) callconv(.c) void;
pub const basis_zig_GlobalVariableSet_readInt_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) c_int;
pub const basis_zig_GlobalVariableSet_writeInt_cb = *const fn (u64, [*c]const basis.bindings.InteropString, c_int) callconv(.c) void;
pub const basis_zig_GlobalVariableSet_readBool_cb = *const fn (u64, [*c]const basis.bindings.InteropString) callconv(.c) c_int;
pub const basis_zig_GlobalVariableSet_writeBool_cb = *const fn (u64, [*c]const basis.bindings.InteropString, bool) callconv(.c) void;
pub const basis_zig_GlobalVariableSet_readString_cb = *const fn (u64, [*c]const basis.bindings.InteropString, [*c]basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_GlobalVariableSet_writeString_cb = *const fn (u64, [*c]const basis.bindings.InteropString, [*c]const basis.bindings.InteropString) callconv(.c) void;

// ===============================

// class CharacterData

pub const basis_zig_CharacterData_getPath_cb = *const fn (u64, [*c]basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_CharacterData_getFirstName_cb = *const fn (u64, [*c]basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_CharacterData_getLastName_cb = *const fn (u64, [*c]basis.bindings.InteropString) callconv(.c) void;
pub const basis_zig_CharacterData_getUIColor_cb = *const fn (u64, [*c]basis.bindings.InteropColor) callconv(.c) void;

// ===============================

